### ISSUE TITLE
Add Support for phantomjs npm Package?

### ISSUE THREAD

**Issue by awlayton** [johntitus/node-horseman#101]
When PhantomJS is installed via the phantomjs npm package, horseman does not always find it on the path.

It could be made to work with something similar to what I posted in the discussion of #70. We could have horseman depend on phantomjs, or leave it like it is (not depend on phantomjs) but detect when it is installed and get the binary from it.

What are your thoughts/opinions on it @johntitus?

**Comment by johntitus** [comment]
I'd rather not have a dependency on the npm package, but some sort of auto-detection that the npm package has already installed phantomjs would be good, if it's not found in the path.

**Comment by awlayton** [comment]
I was thinking the order of precedence would be: user supplied path, phantomjs package, PATH. However, that would use the npm package even if it is also on the global path.

My main reason for that order is I already made horseman do that in one of my projects, so I know how to make a patch for it.

**Comment by metaColin** [comment]
+1
I would love to see this feature. It would simplify my build process for Docker if I could use NPM to properly install phantomjs.

**Comment by awlayton** [comment]
@metaColin, you can use the current horseman with the npm phantomjs like so:
```javascript
var Horseman = require('node-horseman');
var phantomjs = require('phantomjs');

var horseman = new Horseman({phantomPath: phantomjs.path});
```

**Comment by metaColin** [comment]
That's exactly what I eventually ended up doing, but I'd still love some automated path detection.

**Comment by awlayton** [comment]
Support is now in v3.
