### ISSUE TITLE
onLoadFinished callback is not called with any arguments

### ISSUE THREAD

**Issue by balrogthane** [johntitus/node-horseman#103]
Any callback given to `on.('loadFinished')` fails to receive the status; it receives `undefined` instead. Upon glancing at the code it's clear that the page status is not even captured, let alone passed along to the callback; in index.js line 111, the function passed in to PhantomJS for `onLoadFinished` takes no arguments, and every time `self.page.onLoadFinished2` is called it is called with no parameters passed.

**Comment by awlayton** [comment]
You are correct. It looks like the `onLoadFinished` callback needs to give its first parameter to `onLoadFinished2`.

**Comment by awlayton** [comment]
This is fixed in v3.
