### ISSUE TITLE
adding setProxy method

### ISSUE THREAD

**Issue by julienmarie** [johntitus/node-horseman#105]
It would be nice to be able to change proxy dynamically ( I use horseman in a scraping mode integrated with rabbitmq )

**Comment by awlayton** [comment]
The proxy settings are supplied to [PhantomJS at startup](http://phantomjs.org/api/command-line.html). Therefore, adding such a function to horseman would be a bit of an  undertaking. Is it that hard for you to just make a new horseman instance with the new settings @julienmarie?

**Comment by julienmarie** [comment]
@awlayton Proxy settings can be supplied also at runtime apparently ( https://github.com/ariya/phantomjs/pull/11829 ) which is way more convenient than restarting the whole stack.

**Comment by awlayton** [comment]
Well how about that.. I don't see it in the documentation, but there sure *is* a `setProxy` method on the phantom instance...

I guess this should be a todo for horseman then.

**Comment by awlayton** [comment]
I have added a `.setProxy` action to v3 @julienmarie. Please note it only works if you use a version of PhantomJS with that function (it looks like 2.0.0 is the minimum?).
