### ISSUE TITLE
resourceRequested events callback requestData undefined?

### ISSUE THREAD

**Issue by zhuyingda** [johntitus/node-horseman#109]
horseman
    .open('http://www.zhuyingda.com')
    .on('resourceRequested', function (requestData, networkRequest) {
        console.log('data:',requestData);
        console.log('network:',networkRequest);
    })

that code I just got an undefined.

**Comment by colinclassic** [comment]
Your listener ```.on('resourceRequested'.......``` needs to be defined before ```.open``` so that horseman can capture all the requests as the page loads.
