### ISSUE TITLE
Are we sure that node-phantom-simple can handle multiple phantomjs instances

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#110]
As soon as I have multiple phantomjs instances, I am starting to get issues of PhantomJS kills. Were there any stress tests of multiple phantomjs instances running at one time?

**Comment by awlayton** [comment]
I have never tried using multiple horseman instances at once. I don't know of a reason for it to not work, but maybe it doesn't.

**Comment by mato75** [comment]
It can handle it, 403 Directory issue is causing pahntomjs to die

**Comment by ohenepee** [comment]
Please RE-OPEN this ISSUE... `403 Directory Listing` Denied is a real headache

**Comment by awlayton** [comment]
Horseman *can* handle multiple instances @ohenepee. Please see #87 about your ***separate*** issue.
