### ISSUE TITLE
Unhandled rejection TypeError: Cannot set property 'lastVal' of undefined

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#113]
What could be the reason for this?

Example:

```
horseman
.open(url)
.waitFor(fn, value)
.then(function (res) { // checking return value of waitFor function })
.waitFor(fn, value)
.then(function (res) { // checking return value of waitFor function })
.close();
```

Can you maybe explain this code?
```
HorsemanPromise.prototype[name] = function() {
		var args = arguments;
		return this.then(function(val) {
                       // this is undefined here
			this.lastVal = val;
			return this[name].apply(this, args);
		});
};
```

**Comment by awlayton** [comment]
That code at the bottom does the magic that makes horseman's API chainable.

Could you post the full stack trace with `BLUEBIRD_DEBUG=1` set?

**Comment by mato75** [comment]
I see the problem, I am writing a function inside horseman:

```
exports.fancy = function () {
var that = this;
that
.open(url)
.waitFor(fn, value)
.then(function (res) { // checking return value of waitFor function })
.waitFor(fn, value)
.then(function (res) { // checking return value of waitFor function })
.close();
}
```

How would you recommend to write this kind of function?

**Comment by awlayton** [comment]
Line 3 should be `return that`.

I don't think that would be what is causing the error though, but maybe. I need a stack trace to really debug it.

**Comment by mato75** [comment]
Sorry, updated code, please check again.

**Comment by awlayton** [comment]
No literally just make line 3 (now line 4) `return that`. It already returns a `HorsemanPromise`, you don't need to make a new one.

Also, you probably don't want to be calling `.close`, the horseman instance won't work anymore after that.

**Comment by mato75** [comment]
No I would like to return special resolve/rejects, but even if I return that..., the issue is still the same.

**Comment by awlayton** [comment]
Did you try it without the `.close`? Also I ***need a stack trace*** to *actually* figure anything out.

**Comment by mato75** [comment]
Yes, sorry.

**Comment by awlayton** [comment]
You never posted a stack trace without `BLUEBIRD_DEBUG=1` though, *please* post one.

**Comment by mato75** [comment]
Unhandled rejection TypeError: Cannot set property 'lastVal' of undefined
    at /vagrant/server/city/officer.js:1747:17
From previous event:
    at Promise.GuardianPromise.(anonymous function) [as waitFor] (/vagrant/server/city/officer.js:1745:15)
    at /vagrant/server/city/officer.js:1656:6
From previous event:
    at Object.Officer.clickTargetsThrough (/vagrant/server/city/officer.js:1639:16)
    at /vagrant/server/city/mayor.js:547:41
    at Array.forEach (native)
    at _addTests (/vagrant/server/city/mayor.js:493:20)
    at Object.Mayor._investigate (/vagrant/server/city/mayor.js:600:11)
    at /vagrant/server/city/mayor.js:327:30
From previous event:
    at /vagrant/server/city/mayor.js:325:22
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by awlayton** [comment]
It's saying the error isn't even happening in one of the horseman files. I thought you function was in the `lib/actions.js` file?

**Comment by mato75** [comment]
I renamed actions to officer.

**Comment by awlayton** [comment]
What did you rename the other horseman files to ?

**Comment by mato75** [comment]
mayor is index.js

**Comment by awlayton** [comment]
Well the line numbers aren't much use since you've changed code inside.

Somehow you have made it so the Promise is no longer bound to the horseman instance, that is the only way `this` would be undefined for the line `this.lastVal = val;`.

**Comment by awlayton** [comment]
You need your action to return `this.ready.then(function() { /* do you stuff here */})`

See if that helps.

**Comment by mato75** [comment]
No, sorry it doesnt help. I will close the issue, because it is more connected to my use-case.
