### ISSUE TITLE
Recommended phantomjs version ?

### ISSUE THREAD

**Issue by didil** [johntitus/node-horseman#118]

**Comment by awlayton** [comment]
`.upload` only works with 3.x (see #80), otherwise 2.x is fine too.

**Comment by didil** [comment]
great thanks, bumping to node-phantom-simple 2.2.3 soon ?

**Comment by awlayton** [comment]
We probably should at some point. It's up to @johntitus if we do it now, or in v3.

Are there any substantial changes/improvements?

**Comment by didil** [comment]
a few phantom die/exit detection improvements which can be handy https://github.com/baudehlo/node-phantom-simple/blob/master/CHANGELOG.md
