### ISSUE TITLE
multiple pdf pages

### ISSUE THREAD

**Issue by ballPointPenguin** [johntitus/node-horseman#121]
When I use the .pdf() method, it seems to be cutting off everything after the first page.
Is there any way to get all the pages to save into the pdf, or is it designed to only create a single page?

**Comment by awlayton** [comment]
I have used it to create multi-page PDFs before. Could you post code for reproducing the problem?

**Comment by ballPointPenguin** [comment]
That's good to know.

this is what I'm doing:

```
horseman
    .cookies(cookie)
    .viewport(1920, 1200)
    .zoom(0.9)
    .open(pageUrl)
    .waitForSelector('#main')
    .pdf('tmp/' + filename, {
      format: 'A4',
      orientation: 'landscape',
      margin: '10mm'
    })
    .then(function() {
      res.status(200).send({
        filename: filename,
        link: link
      });
    })
    .catch(function(err) {
      console.log('catch', err);
    })
    .finally(function() {
      horseman.close();
    });
```

**Comment by ballPointPenguin** [comment]
I just tried this: 

```
horseman
    .open(https://en.wikipedia.org/wiki/List_of_Roman_emperors)
    .pdf('tmp/' + filename,)
```

and although it did not paginate (why would it), it did not cut any content off.
So maybe it's my own stylesheets that are interfering.

**Comment by ballPointPenguin** [comment]
Yep!

I just confirmed with:

```
horseman
    .viewport(1920, 1200)
    .zoom(0.9)
    .open(https://en.wikipedia.org/wiki/List_of_Roman_emperors)
    .pdf('tmp/' + filename, {
      format: 'A4',
      orientation: 'landscape',
      margin: '10mm'
    })
```

That it will paginate the content (given a format). So the issue is on my end.

Thank you
