### ISSUE TITLE
Socket hangup issue on 'open' call

### ISSUE THREAD

**Issue by didil** [johntitus/node-horseman#123]
Hi

When trying to access a url with node-horseman, we sometimes (randomly) get the error :
'Request() error evaluating open() call: Error: socket hang up'
 do you know what could cause this ? (we use phantomJS 1.9.8)

Thanks

Adil

**Comment by awlayton** [comment]
I believe that means the socket timed out waiting for a response from the server. There's a *whole* bunch on it [here](http://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean).

Anyways, it's most likely not a problem with phantom or horseman.

**Comment by didil** [comment]
thanks for your answer, but it would mean the socket hangup comes from the phantomjs client right ? since I understand it's the only thing that's actually starting a connection

**Comment by awlayton** [comment]
It depends what you mean by "*comes from*". The message is being generated by phantomjs or the kernel or something, but ***you are getting the message because the server is not responding***. The server is the real problem.

**Comment by didil** [comment]
yes I meant which software layer is raising the socket hangup error. Thanks for all the explanations, closing the issue

**Comment by didil** [comment]
fyi I updated to phantomjs 2.1.1 from 1.9.8 and the socket hangup doesn't happen anymore

**Comment by awlayton** [comment]
Strange, perhaps the timeout was increased or something...
