### ISSUE TITLE
Helper methods with assert/should

### ISSUE THREAD

**Issue by keon2567** [johntitus/node-horseman#125]
I am trying to create a helper method that take you from A to B and B to C, and would like to use them as needed.
For example)
```
var self = this;
this.horseman = new Horseman();
horseman
    .do(helper.AtoB.bind(self))
    .do(helper.BtoC)
    .then(function() {
        self.horseman.close()
    }).nodeify(done);
```
....

```
helper = {
    AtoB: function(done) {
        this.horseman
        .open('http://www.google.com/')
        .url()
        .then(function(data) {
            data.should.equal('http://www.reddit.com/')' // should fail here
        }).nodeify(done);
    },
    BtoC: ...
}
```

Having horseman passed to helper methods and going from point A to point B works fine; however, I cannot assert within the helper. It simply ignores the should failures and goes on. I am trying to set some helpers that I can reuse and avoid writing same lines to get from one point to another. Any suggestion would be appreciated. Thank you.

**Comment by awlayton** [comment]
`.do` always resolves for some reason (probably shouldn't). However, it is basically a re-implementation of the bluebird function `.fromNode` (so it can just be deprecated since I made all the bluebird functions available to horseman).

Anyways, to *actually* answer you question, you should have your helper methods return Promises and then just give them to `.then` instead of `.do`. Changes below:

```javascript
//var self = this;
//this.horseman = new Horseman();
// ^ Not needed, this inside horseman chain is already bound to the horseman instance
horseman
    .then(helper.AtoB)
    .then(helper.BtoC)
    .then(function() {
        self.horseman.close()
    }).nodeify(done);
```
....

```javascript
helper = {
    AtoB: function() {
        return this // Return chain result
            .open('http://www.google.com/')
            .url()
            .then(function(data) {
                data.should.equal('http://www.reddit.com/') // should fail here
            });
    },
    BtoC: ...
}
```

**Comment by keon2567** [comment]
I am seeing that horseman.then is not a valid function.

**Comment by awlayton** [comment]
I edited my comment. I should maybe add `.then` as an action.

**Comment by keon2567** [comment]
Is there a way to pass values to helper methods?

**Comment by awlayton** [comment]
Sure,

```javascript
horseman
    .url()
    .then(helper.AtoB)
```

will pass the url as the first parameter to `helper.AtoB`.

**Comment by keon2567** [comment]
How about passing custom variables?

**Comment by awlayton** [comment]
It's all just normal Promises.

```javascript
horseman
    .url()
    .then(function(url) {
        return helper.AtoB(varA, varB); // call it with whatever
    })
```

**Comment by keon2567** [comment]
Thank you @awlayton . Saved my day!

**Comment by keon2567** [comment]
Code above doesn't work if the helper.AtoB needs to return horseman chains. this is now undefined.

horseman
    .url()
    .then(function(url) {
        return helper.AtoB('screenshot', '.jpg');
    })

helper = {
    AtoB: function(varA, varB) {
        var varC = varA+varB;
        return this.screenshot(varC); // this is now undefined
    }
}

**Comment by awlayton** [comment]
```javascript
horseman
    .url()
    .then(function(url) {
        return helper.AtoB.call(this, 'screenshot', '.jpg');
    })
```

Please don't open (or reopen) issues just because you don't understand JavaScript, open issues for things that are wrong about horseman.

**Comment by capcrunchIO** [comment]
This helped me understand something completely unrelated... :+1:

**Comment by awlayton** [comment]
Hah, nice @capcrunchIO.
