### ISSUE TITLE
.text('.selector') returns empty string

### ISSUE THREAD

**Issue by franciskim** [johntitus/node-horseman#127]
I've followed the Twitter example on the website, and the text seems to be an empty string. Tried updating the selector to the most recent one as well (they seem to have changed the CSS class) but no luck.

**Comment by franciskim** [comment]
additionally the `Count links from Google` gives me 0. I've tried on PhantomJS 2.1.1 and 1.9.0 - on Ubuntu 14.04.3 LTS

**Comment by awlayton** [comment]
The website http://www.horsemanjs.org/ is outdated. If you try the google example in the Readme, that one works (I just ran it). As for twitter, it works if you give it the *right* selector:

```javascript
var Horseman = require("node-horseman");

var users = ['PhantomJS',
  'ariyahidayat',
  'detronizator',
  'KDABQt',
  'lfranchi',
  'jonleighton',
  '_jamesmgreene',
  'Vitalliumm'];

users.forEach( function( user ){
  var horseman = new Horseman();
  horseman
    .open('http://mobile.twitter.com/' + user)
    // This selector works now, but will probably stop working later
    .text('table.profile-stats > tbody > tr > td.stat > a[href$="/followers"] > div.statnum')
    .then(function(text){
      console.log( user + ': ' + text );
      horseman.close();
    });
});
```

I think twitter might be trying to deter scraping...

**Comment by franciskim** [comment]
That worked, thanks!
