### ISSUE TITLE
SitePoint JS article on crawling with Horseman

### ISSUE THREAD

**Issue by wreckloose** [johntitus/node-horseman#129]
FYI, some exposure for your excellent package:
[http://www.sitepoint.com/web-crawling-node-phantomjs-horseman/](http://www.sitepoint.com/web-crawling-node-phantomjs-horseman/)

It only includes a fraction of Horseman's capabilities, but there's only so much you can cover in 2,000 words or less.

**Comment by johntitus** [comment]
Very cool, thanks! Nice article.

**Comment by awlayton** [comment]
Nifty
