### ISSUE TITLE
New Window?

### ISSUE THREAD

**Issue by LuckyLillia** [johntitus/node-horseman#132]
I am using horsemanjs to login to a website.
After login, it clicks a link. I am able to write till this step.

Then, a javascript event fires and a new popup window opens.

How to write code to move to the newly opened window? And I have to write code inside the new window.

For example: In this https://github.com/johntitus/node-horseman/issues/41  html code,  instead of the below popup message, if a new child window opens, how should I write code for that new window?

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Confirm check</title>
    <script>
        function confirmation() {
            var answer = confirm('OK or Cancel?');
            if (answer === true) {
                console.log('You pressed OK');
            } else {
                console.log('You pressed Cancel');
            }
        }
    </script>
</head>
<a id="confirm" href="#" onclick="confirmation()" >Confirm?</a>
</body>
</html>
```

Thanks.

**Comment by awlayton** [comment]
That is something horseman v2 does not handle well. It has been fixed in v3 (see #100).

The behavior of v3 is not entirely set yet, but using it would fix your problem...

**Comment by LuckyLillia** [comment]
How do I get v3 ?

**Comment by awlayton** [comment]
It's not released, but you can install the current WIP version with `npm install johntitus/node-horseman#wip-v3`.

**Comment by awlayton** [comment]
You'll probably want to set the `switchToNewTab` option @LuckyLillia.
