### ISSUE TITLE
wait doesnt delay next call

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#136]
I have a test case where I would like to wait 10s before I make a screenshot, but screenshot is made as soon as ready is resolved.

 
```javascript
horseman.open()
  .wait(10000)
  .screenshot('test.png')
  .close();
```

Any suggestions on why is this happening?

**Comment by awlayton** [comment]
It works fine for me.
```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman();

horseman.open('http://www.timer-tab.com/')
    .wait(10000)
    .screenshot('test.png')
    .close()
```

test.png:
![test](https://cloud.githubusercontent.com/assets/4231765/13470163/e14d8858-e078-11e5-8640-b34ccaad49e7.png)

It must be broken from changes you made to the code (I assume this is that one project of yours).

**Comment by mato75** [comment]
Hm, well you may be right. I am generating this steps from JSON data. I am adding actions dynamically.

Example:
`horseman.open(); horseman.wait().then(function() {}); horseman.screenshot('test.png'); horseman.close();`

Is there a better way to do this?

**Comment by awlayton** [comment]
You have to build on the same chain. You are creating branch in the chain (which I doubt horseman likes).

You need to do it like so:
```javascript
var chain = horseman.open();
// Always append to the chain
chain = chain.wait().then(function() {});
chain = chain.screenshot('test.png').then(function() {});
chain.close();
```

**Comment by mato75** [comment]
Thank you, will try tomorrow morning.

**Comment by mato75** [comment]
Hm, I am getting this error:

Cannot set property 'lastVal' of undefined

````
HorsemanPromise.prototype[name] = function () {
		var args = arguments;
		return this.then(function (val) {
			this.lastVal = val;
			return this[name].apply(this, args);
		});
	};
````

**Comment by mato75** [comment]
Answer: 
http://stackoverflow.com/questions/35767854/build-promises-from-json-with-bluebird#35767854

**Comment by awlayton** [comment]
That error has to be from a change you made. I made the Promise chain bound to the Horseman instance, so `this` should *never* be undefined.
