### ISSUE TITLE
Closing Tabs and Access to DOM ?

### ISSUE THREAD

**Issue by LuckyLillia** [johntitus/node-horseman#139]
First of all, thanks for the suggestion in #132 and I used switchToNewTab option with success in wip-v3.

I am stuck on two things:

1) How do I close the newly opened tab? How to call the window.close() ?  (The newly opened window has no close button so I cannot call .click(btnClose) )

2) How do I access the DOM similar to casperjs, like this.evaluate( and here document.queryselector) and so on?

Thanks a lot

**Comment by johntitus** [comment]
1) You can't. Never thought of that, but there is no method for it. @awlayton maybe we could add that to v3?
2) After you switchToNewTab, that becomes you "working" tab. You can then use the `.evaluate` method and the target will be that new tab.

**Comment by LuckyLillia** [comment]
Thanks for the quick reply,

inside  .evaluate can I do  window.close() ? And yes, if you could add the new window/tab close functionality in v3 that would be great!

I hope I can do this in .evaluate, right?
document.querySelector('input[name="login_button"]').click();

**Comment by LuckyLillia** [comment]
As an example, if I visit a blog post and wanted to share it,
I click a button and a new twitter window opens up. I send the tweet. 
Then I close the window close icon.

To do this in code, I think I have to use the window.close() method. 
Or maybe, a new tab close method in horseman!

I do not have much idea about the tab closing behavior which needs to be implemented in code, though I feel renumbering the tabs may be a good idea.

**Comment by LuckyLillia** [comment]
To add to this, I have noticed:

Inside the new popup window, there's a close button, so 
.click('input[id="btn-close"]')
 .wait(5000)
 .switchToTab(0)
 .tabCount()
 .log()

It closes the popup window, switches to the main page, but as you mentioned, tabcount() is still 2, even though the popup window is closed.

**Comment by awlayton** [comment]
Yes, it should be relatively simple to fix that.

I think I am leaning towards having `.openTab` resolve to some sort of tab ID that could be given to `.switchToTab`, but still leaving support for indexing the array of tabs. When a tab is closed, the things would shift in the array, but the tab ID things would be the same for each tab.

Thoughts?

**Comment by awlayton** [comment]
I just made another beta release @LuckyLillia. Tabs now go away when their corresponding page closes, and there is now a `.closeTab()` action. It would be great if you could try it out.

I have not yet added the tab ids I talked about, which is why I did not close this issue yet.

**Comment by awlayton** [comment]
I think I'll close this. If anyone else really wants the tab ids I'll reconsider.
