### ISSUE TITLE
can't run on windows

### ISSUE THREAD

**Issue by n37r06u3** [johntitus/node-horseman#14]
$ phantomjs 1.js
Error: Cannot find module 'http'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  C:/Users/n37r06u3/Desktop/node/node_modules/node-horseman/node_modules/node-ph
antom-simple/node-phantom-simple.js:3
  C:/Users/n37r06u3/Desktop/node/node_modules/node-horseman/node_modules/node-ph
antom-simple/node-phantom-simple.js:474
Error: Cannot find module 'path'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  C:/Users/n37r06u3/Desktop/node/node_modules/node-horseman/lib/index.js:4
  C:/Users/n37r06u3/Desktop/node/node_modules/node-horseman/lib/index.js:290
TypeError: '[object Object]' is not a constructor (evaluating 'new Horseman()')

  1.js:2

**Comment by johntitus** [comment]
Horseman runs in Node.js, so you'd execute your script like this:

`node 1.js`

**Comment by n37r06u3** [comment]
thx
