### ISSUE TITLE
Request is always empty

### ISSUE THREAD

**Issue by lukaszblacha** [johntitus/node-horseman#141]
Hi @johntitus 
First of all thank you for the great piece of code.

I am encountering following issue
```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman();
horseman.on('resourceRequested', function(data, request) {
    console.log(JSON.stringify(request, null, 4));
});
horseman.open('http://www.google.com');
```
Log always gives me `{}`

EDIT: I can see it's broken in node-phantom-simple

**Comment by awlayton** [comment]
This is solely because of node-phantom-simple. Horseman cannot fix it. You should open an issue of node-phantom-simple for this if there is not one already.

**Comment by lukaszblacha** [comment]
I will am closing this issue because of this
https://github.com/baudehlo/node-phantom-simple/issues/98

**Comment by awlayton** [comment]
@lukaszblacha In [v3][] there is an `.at` action (same arguments as `.on`) which runs when the event is happening (`.on` runs after).

You could use it to access the request parameter, but be aware that the callback given to `.at` runs in PhantomJS *not* in Node.js.
[v3]: <https://github.com/johntitus/node-horseman/tree/wip-v3>
