### ISSUE TITLE
Need a way to access raw content of a URI

### ISSUE THREAD

**Issue by zhaorenjie** [johntitus/node-horseman#145]
In phantomJS, a page.content object hold the contents. But there is no equivalent in horseman.
When crawling some page like 'http://c.diaox2.com/share/sku_pack', it will be more convenient to have access to the raw content.

**Comment by awlayton** [comment]
I have never tried to use PhantomJS with something that is not HTML. Using `.open()` and `page.content` actually works for this @zhaorenjie?

I have been contemplating if horseman should have a `.download()` like [CasperJS](http://docs.casperjs.org/en/latest/modules/casper.html#download), which I think is basically what you want.

**Comment by awlayton** [comment]
It does not work as you say @zhaorenjie, page.content in PhantomJS is ***not*** the raw content of the URI.

The content is coerced into a web page, that is for your provided URI the value of `page.content` is the same as the value of `horseman.html()` (except `page.content` has and outer `<html>` and `</html>`).

TO be precise, `page.content` was like this:
```html
<html>
  <head>
  </head>
  <body>
    <pre style="word-wrap: break-word; white-space: pre-wrap;">
      ACTUAL URI CONTENT
    </pre>
  </body>
</html>
```

**Comment by zhaorenjie** [comment]
Oh, thanks. Tough with a little bit more works to do to extract the "REAL" content, it's helpful and solves the problem.

**Comment by awlayton** [comment]
That is not what `page.content` always looks like @zhaorenjie. If the URI points to an image, the image is not in `page.content` at all (there is just an img tag).

The only real answer to this is to have a `.download()` action. Do agree about adding `.download(url)` @johntitus?

**Comment by awlayton** [comment]
I have added an implementation of a [`.download()`](https://github.com/johntitus/node-horseman#downloadurl-path-binary) action.

I am not sure yet if I like it, so I'd appreciate input. Also it not work with binary in phatom 1 (but binary does work with phantom 2), but I think it's reasonable for the new horseman version to work best with the new phantom version.

**Comment by awlayton** [comment]
I am calling this closed for now. If anyone dislikes my `.download()` they can open an issue about it
