### ISSUE TITLE
Issue when using proxies

### ISSUE THREAD

**Issue by snapeuh** [johntitus/node-horseman#147]
Hello,

I use Horseman 3.0.0 Beta 1 and I tried to use it with a proxy.

```javascript
Browser
    .setProxy('ip', '80', 'http', 'username:password')
    .userAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36')
    .viewport(1366, 768)
    .open('http://www.example.com')
    .screenshot('image.png')
    .close();
```

The screenshot is the page when I visit : http://myproxyip:myproxyport. Same if I use the .html method. It returns the HTML code of the proxy page. 

Did you experience this issue?

Thanks,

Romain.

**Comment by awlayton** [comment]
What version of phantom are you using? Those are the wrong arguments to `.setProxy()`, it should be `.setProxy('ip', '80', 'http', 'username, 'password')` as stated in the [Readme](https://github.com/johntitus/node-horseman#setproxyip-port-type-user-pass).

Also phantom's proxy settings are not for proxies with login pages, they are for [HTTP proxies](https://tools.ietf.org/html/rfc2068#section-14.33).

**Comment by snapeuh** [comment]
I use Phantom 2.1.1. In the readme I can read : 

`.setProxy(ip, [port], [type], [user, pass])`

Which let me think that user and pass are combined in a single string. Maybe you should split it to [user], [pass] like the other parameters.

I am trying your solution and will let you know the result!

**Comment by awlayton** [comment]
It means that you have to supply both or neither, but the comma means they are separate arguments.

**Comment by snapeuh** [comment]
I can confirm that I have the same problem with your suggestion.

I try to load a site but instead I have the html from the http://ip:port from the proxy. It's an HTTP proxy without an authentication form. I use the same proxy with request module for NodeJS without any problem.

I also tried to setup the proxy directly in Horseman options by typing: 

`{ proxy: 'http://user:pass@ip:port' }`

But no luck with that too. Still getting the proxy homepage content.

**Comment by awlayton** [comment]
Those are not the correct constructor options.

```javascript
var horseman = new Horseman({
    proxy: 'ip:port',
    proxyType: 'http',
    proxyAuth: 'user:pass'
});
```

**Comment by snapeuh** [comment]
My bad, I rushed the answer and remixed everything.

I meant that I tried to use the string on the IP parameter for setProxy.

And indeed I did use the options as it's mentioned in the doc.

I guess it connect to the proxy otherwise I wouldn't have the proxy HTML as output. If I remove the proxy method or options everything works as intended.

Sorry for the confusion.

Romain.

**Comment by awlayton** [comment]
Interesting... There are tests for the proxy stuff and they pass. What version of node are you using? Have you tried the constructor proxy options?

**Comment by snapeuh** [comment]
I'll try some stuff tuesday and I'll let you know.

I am 100% sure the proxy is working and that the credentials are correct too. As I said I am using it with the RequestJS node package without any issue with the syntax : "http://user:pass@ip:port".

Here is a more precise example :

```
Browser
    .setProxy('ip', '80', 'http', 'username', 'password')
    .userAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36')
    .viewport(1366, 768)
    .open('http://www.example.com')
    .html()
    .then(function(html){
        console.log(html);
    })
    .close();
```

It outputs the HTML of _http://ip:port_ instead of _example.com_ source code. If I remove the `setProxy` the ouput is _example.com_ source code.

Super strange :/

**Comment by snapeuh** [comment]
@awlayton My bad. I was distracted and used the wrong port for my proxy. It isn't on port 80. Everything is working as expected now. Thanks again for your patience and your help.

Romain.
