### ISSUE TITLE
Add other frame switching actions

### ISSUE THREAD

**Issue by awlayton** [johntitus/node-horseman#149]
As pointed out in #148, horseman is missing a `.switchToParentFrame()`.

Perhaps there should be an action for each of Phantom's switchTo*Frame functions?

**Comment by awlayton** [comment]
Just to check, is there any reason not to add all of these actions @johntitus?

I sometimes have a problem with adding too many things and getting feature creep...

**Comment by johntitus** [comment]
Seems like there's a demand for them, so I'd say go ahead and add them.
