### ISSUE TITLE
Issue in instantiating node-horseman

### ISSUE THREAD

**Issue by viveksrinivasanss** [johntitus/node-horseman#15]
Within express app when I tried to create instance of Horseman globally its working correctly without any errors.But when I try the same within the function it throwing the following error

**node: ../src/node_http_parser.cc:387: static v8::Handle<v8::Value> node::Parser::Execute**
**(const v8::Arguments&): Assertion `!current_buffer' failed.**

**Aborted (core dumped)**

When I do the same thing within sails my code hangs at the line where I instantiate the instance of Horseman.

The same thing works fine when I do it normally without using it with sails or express

The following code block creates a simple express app which requires node_horseman_test_2.js where I instantiate node horseman.

## node_horseman_test_1.js

```/*
 |--------------------------------------------------------------------------
 | Global Imports
 |--------------------------------------------------------------------------
 */

var express = require('express');
var Promise = require('bluebird');
var path = require('path');
var bodyParser = require('body-parser');
var nodeHorseman = require('./node_horseman_test_2.js');

/*
 |--------------------------------------------------------------------------
 | Create our Express application
 |--------------------------------------------------------------------------
 */

var app = express();

app.use(bodyParser.urlencoded({
    extended: true
}));

app.all('/*', function(req, res, next) {
    // CORS headers
    res.header("Access-Control-Allow-Origin", "*"); // restrict it to the required domain
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
    // Set custom headers for CORS
    res.header('Access-Control-Allow-Headers', 'Content-type,Accept,X-Access-Token,X-Key');
    if (req.method == 'OPTIONS') {
        res.status(200).end();
    } else {
        next();
    }
});

// Use environment defined port or 8888
var port = process.env.PORT || 8888;

// Create our Express router
var router = express.Router();

// Register all our routes with /api
app.use('/api/v1/', router);

// Initial dummy route for testing
router.get('/', function(req, res) {
    res.json({ message: 'Test message' });
});

//Add productMatching router here
var test = router.route('/test');

//Get request here calls scraper to find matches
test.get(function(req, res) {
    nodeHorseman.instantiate(req.query).then(function(results) {
        res.send(results);
    }).catch(function(err) {
        if(err) res.send(err);
        //LOG ERROR HERE
        else res.send('Match failed. Check connection.');
    });
});

// If no route is matched by now, it must be a 404
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    //LOG ERROR HERE
    next(err);
});

// Start the server
app.listen(port);
console.log('Send match searches to ' + port);
```
## node_horseman_test_2.js

```
var Horseman = require('node-horseman');
var userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36';
var Promise = require("bluebird");


exports.instantiate = function() {
  	return new Promise(function(resolve, reject) {
		var horse = new Horseman();
		horse
	    .userAgent(userAgent)
	    .open("http://www.google.com");
		console.log(horse.url());
		horse.close();
	});
};

```

**Comment by johntitus** [comment]
I know we discussed this via email a bit before and I was stumped, but I decided to start from scratch and try again.  I stood up a new Express 4.0 app

`express --ejs newfolder`

I installed horseman `npm install node-horseman --save`

I npm installed everything.
`npm install`

I modified routes/index.js to look like this:
```js
var express = require('express');
var router = express.Router();
var Horseman = require('node-horseman');

/* GET home page. */
router.get('/', function(req, res) {
	var horseman = new Horseman();
	var url = horseman
		.open('http://www.google.com')
		.url();
	res.json({url:url});
	horseman.close();
});

module.exports = router;
```

Ran the server, and it works fine. The index page shows `{"url":"http://www.google.com/"}`.  

So I'm not sure what's causing the bug, but maybe recreate what I did and then slowly add to it until you either get the bug, or are able to move forward.

**Comment by petecoop** [comment]
@viveksrinivasanss not sure if this is the issue but You aren't resolving your promise anywhere, so it will never go to `.then()`

```js
exports.instantiate = function() {
    return new Promise(function(resolve, reject) {
        var horse = new Horseman();
        horse
        .userAgent(userAgent)
        .open("http://www.google.com");
        console.log(horse.url());
        horse.close();
    });
};
```

**Comment by viveksrinivasanss** [comment]
@petecoop  actual problem happens in third line itself where I instantiate the node-horseman instance...I missed adding that resolve line...Its not working  even after adding that line...

**Comment by viveksrinivasanss** [comment]
@johntitus Thanks for the solution...Its working fine now in express ...I am using older version of express ...Once I updated to 4^ version of express its started working....Might be some dependency which I missed before....

But the hanging issue in sails framework still exist...if you want I can post some examples here

**Comment by johntitus** [comment]
If upgrading express fixed it, then I'm going to just blame sails and close this issue ;)
