### ISSUE TITLE
Unhandled rejection Error: spawn ENOENT

### ISSUE THREAD

**Issue by MrBlueBird** [johntitus/node-horseman#150]
Hello, i have a problem, version node: 
v0.10.42

Every time when you try to run the script

[root@da4502 scrap]# node server.js
call on port 8081
spawn called
{ '0': 'phantomjs',
  '1':
   [ '--ignore-ssl-errors=true',
     '--load-images=true',
     '--ssl-protocol=any',
     '--web-security=true',
     '/home/node/dom/domain.io/public_html/scraping/node_modules/node-phantom-simple/bridge.js' ] }
Unhandled rejection Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by awlayton** [comment]
The `ENOENT` error typically means the phantom executable was not found. Are you sure you have PhantomJS installed properly?

**Comment by MrBlueBird** [comment]
I installed phantom command npm install phantom

npm install phantom
npm WARN gentlyRm not removing /home/node/domains/no.om.pl/public_html/scrap/node_modules/.bin/phantomjs as it wasn't installed by /home/node/domains/no.om.pl/public_html/scrap/node_modules/phantomjs-prebuilt

> phantomjs-prebuilt@2.1.7 install /home/node/domains/no.om.pl/public_html/scrap/node_modules/phantom/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS is previously installed at /home/node/domains/no.om.pl/public_html/scrap/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
qs@5.2.0 node_modules/phantomjs-prebuilt/node_modules/qs -> node_modules/phantom/node_modules/qs
request@2.67.0 node_modules/phantomjs-prebuilt/node_modules/request -> node_modules/phantom/node_modules/request
phantomjs-prebuilt@2.1.7 node_modules/phantomjs-prebuilt -> node_modules/phantom/node_modules/phantomjs-prebuilt
node-phantom-simple@2.2.4 /home/node/domains/no.om.pl/public_html/scrap
+-- node-horseman@2.8.2  extraneous
`-- phantom@2.0.10  extraneous

**Comment by awlayton** [comment]
You need to have phantom on your path, the npm phantom does not do that. Only the horseman beta work out of the box with npm phantom.

You need to either install horseman v3, or do the following to use npm phantom:
```javascript
var phantomjs = require('phantomjs');

var horseman = new Horseman({phantomPath: phantomjs.path});
```
