### ISSUE TITLE
Ability to extend Horseman actions

### ISSUE THREAD

**Issue by lukaszblacha** [johntitus/node-horseman#152]
This is an enhancement suggestion. I'd really love the ability to extend Horseman API with user defined actions. It comes in handy when dealing with repetitive tests.

The interface could look like this:
```javascript
Horseman.registerAction('injectCssFiles', function(css) {
    return this.evaluate(function(css) {
        // function body
    }, css);
});
```

The implementation would add this action to both Horseman and HorsemanPromise prototypes.
What do you think?

**Comment by awlayton** [comment]
I had considered adding something like that, but I didn't know if anyone would use it. Since I'm not the only one, I will add it to the todo list.
