### ISSUE TITLE
Documentation Enhancement for waitFor

### ISSUE THREAD

**Issue by JamesRBrown** [johntitus/node-horseman#153]
Most of the wait options are pretty straightforward, however, the "waitFor" option is unclear as how it is to be used.  An example would be of great benefit.  I assume this allows for a custom function, but I'm not sure how to implement.  I have a need to implement a branching waitForSelector function, that waits for one selector in one case, and a different selector in another case, and it seems the "waitFor" option would be good for this, but if it is the implementation escapes me. 

Thank you!

Awesome API by the way!

**Comment by JamesRBrown** [comment]
Did some more playing around with this, and figured it out.  It seems you have to return one of the other wait functions.  Ex:

.evaluate(function(){
            var hasPictures = !!$('.fa-camera');
            $('[role="listitem"] [role="button"]:first').click(); //click on item
            return hasPictures;
})
.waitFor(function(hasPictures){
            if(hasPictures){
                return waitForSelector('.image-viewer-thumbnails'); //item has pictures, wait for them
            }else{
                return waitForSelector('[ng-include*="image-viewer.html"]'); //item does not have pictures
            }
})

**Comment by awlayton** [comment]
Sorry but you did *not* figure it out correctly @JamesRBrown.

I am not sure how the description of `.waitFor()` is unclear, it seems like you are overthinking it.

The function given to `.waitFor()` is evaluated on the browser page, so it does not have the horseman actions like `waitForSelector`. Also, you are not passing yours and arguments so `hasPictures` will be undefined.

Use it like so
```javascript
// This will call foo repeatedly in the browser until true (or whatever else you specified) is returned
.waitFor(function foo(a, b) {
  // a == 1
  // b == 2
  return $('#someid').length > 0
}, 1, 2, true) // last argument (true) is what return value to wait for
```

**Comment by JamesRBrown** [comment]
@awlayton thank you for clearing that up for me, my original attempts were quite similar to your code, but the function would never return and would just hang (I didn't really understand the relationship of the return value).  I thought I figured it out because I finally got the function to return (guess it basically just fell through), and it seemed to wait an appropriate amount of time for each of the cases I was dealing, but it was probably just coincidences.   I appreciate you explaining the usage, and it would be fantastic if that explanation could be added to the documentation so that this would be clear moving forward.  (I tried googling this quite a bit before I posted, and didn't find anything any where that actually demonstrated the usage.)

**Comment by awlayton** [comment]
I can add a code example, but how would you word the description @JamesRBrown?

**Comment by JamesRBrown** [comment]
@awlayton I would do it similarly to other examples in the read me:

### **.waitFor(fn, [arg1, arg2,...], value)**
Wait until the fn evaluated on the page returns value. fn is invoked with args;

```
//This function conditionally switches between two selectors to wait for
//Will call the function until selected function returns true
.waitFor(function(hasPictures){
        if(hasPictures){
            return $('.image-viewer-thumbnails').length > 0;//wait for images to load
        }else{
            return $('.submit-button').length > 0;//no images to wait for
        }
    }, hasPictures/*value to pass in*/, true /*the value which the function return must match to proceed*/)//the last argument is always the matching value to wait on
```

I do have one question though, is it not possible to pass in the value to the function as the output from the previous action?  If not you have to save the switching value (gained from the previous action) to a variable in the next higher execution context (outside of the horseman chain), which isn't elegant.

**Comment by awlayton** [comment]
You don't have to make a variable, you just have to use `.then` (horseman is all Promises).

```javascript
horseman
  .evaluate(/* some function */) // Can be whatever action
  .then(function(res) {
    return this.waitFor(function(res) { /* some code */ }, res, true);
  })
```

**Comment by JamesRBrown** [comment]
Brilliant!  Thanks for that!

**Comment by JamesRBrown** [comment]
@awlayton I edited my above post with the updated description, I hope you didn't miss it.  

The original description "Wait until the fn evaluated on the page returns value." was unclear to me because it seems like it's awaiting until it returns an value, and not necessarily the specified value. 

So perhaps: Wait until the fn evaluated on the page returns specified value.

**Comment by JamesRBrown** [comment]
@awlayton thank you for updating the read me, it look great!

One thing though, after further testing I discovered that the promise method doesn't actually work.  If I do...

```
.then(function(res) {
    return this.waitFor(function(res) { /* some code */ }, res, true);
  })
```
...it doesn't actually wait like...
```
.waitFor(function(res) {
     /* some code */ 
}, res, true);

```
...does.

**Comment by awlayton** [comment]
It should. Can you post example code where it does not work?

**Comment by JamesRBrown** [comment]
@awlayton I'm sorry, the code I'm working on is scraping a protected resource and I can't make the access info publicly known, however I'll give you the code minus the resource information (perhaps I could supply you with the rest out of band).  Essentially it's an Angular site for vehicle management, some vehicles have pictures, some do not (depending on if there was damage reported).  In the former case it takes less time to load a vehicle than the latter case, and thus I need to conditionally wait for img tags or not.  

```javascript
//Broken:
var Horseman = require('/home/automationScripts/node_modules/node-horseman');

var valueStore = {};

valueStore.loginURL = "";
valueStore.username = "";
valueStore.password = "";
valueStore.VIN = "";

new Horseman()
    .userAgent("Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36")
    .viewport(1080, 1920)
    .then(function(){
        console.log("Opening Login Page");
    })
    .open(valueStore.loginURL)
    .type('input#IDToken1', valueStore.username)
    .type('input#IDToken2', valueStore.password)
    .click('[name="Login.Submit"]')
    .then(function(){
        console.log("Logged in!");
        console.log("Logging Search Page");
    })
    .waitForSelector('[ng-model="vm.searchCriteria.vins"]')
    .waitForSelector('button[ng-click*="vm.search()"]')
    .screenshot('horseSearchPage.png')
    .type('[ng-model="vm.searchCriteria.vins"]', valueStore.VIN)
    .click('button[ng-click*="vm.search()"]')
    .then(function(){
        console.log("Searched for vin!");
        console.log("Returning results");
    })
    .waitForSelector('role="listitem"')
    .evaluate(function(){
        var hasPictures = !!$('.fa-camera');
        $('[role="listitem"] [role="button"]:first').click(); //click on item
        return hasPictures;
    })
    .then(function(hasPictures){
        console.log("Has pictures: "+hasPictures);
        return this.waitFor(function(hasPictures){
            if(hasPictures){
                return $('.image-viewer-thumbnails').length > 0;            //wait for images to load
            }else{
                return $('[ng-include*="image-viewer.html"]').length > 0;   //only wait for image container (this should be present even if there aren't images)
            }
        }, hasPictures, true);
    })
    .screenshot('vehicle.png') //no pictures are loaded
    .then(function(){
        console.log("Closing horseman!");
    })
    .close();
```

```javascript
//Working:

var Horseman = require('/home/automationScripts/node_modules/node-horseman');

var valueStore = {};

valueStore.loginURL = "";
valueStore.username = "";
valueStore.password = "";
valueStore.VIN = ""; 

new Horseman()
    .userAgent("Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36")
    .viewport(1080, 1920)
    .then(function(){
        console.log("Opening Login Page");
    })
    .open(valueStore.loginURL)
    .type('input#IDToken1', valueStore.username)
    .type('input#IDToken2', valueStore.password)
    .click('[name="Login.Submit"]')
    .then(function(){
        console.log("Logged in!");
        console.log("Logging Search Page");
    })
    .waitForSelector('[ng-model="vm.searchCriteria.vins"]')
    .waitForSelector('button[ng-click*="vm.search()"]')
    .screenshot('horseSearchPage.png')
    .type('[ng-model="vm.searchCriteria.vins"]', valueStore.VIN)
    .click('button[ng-click*="vm.search()"]')
    .then(function(){
        console.log("Searched for vin!");
        console.log("Returning results");
    })
    .waitForSelector('role="listitem"')
    .evaluate(function(){
        var hasPictures = !!$('.fa-camera');
        $('[role="listitem"] [role="button"]:first').click(); //click on item
        return hasPictures;
    })
    .then(function(hasPictures){
        console.log("Has pictures: "+hasPictures);
        valueStore.hasPictures = hasPictures;
    })
    .waitFor(function(hasPictures){
            if(hasPictures){
                return $('.image-viewer-thumbnails').length > 0;            //wait for images to load
            }else{
                return $('[ng-include*="image-viewer.html"]').length > 0;   //only wait for image container (this should be present even if there aren't images)
            }
        }, valueStore.hasPictures, true)
    .screenshot('vehicle.png') //no pictures are loaded
    .then(function(){
        console.log("Closing horseman!");
    })
    .close();

```
