### ISSUE TITLE
Pass in functions as arguments to various methods

### ISSUE THREAD

**Issue by winghouchan** [johntitus/node-horseman#155]
Is it possible to pass in functions as arguments to various methods? If it is, how would this be done; and if not, would it be possible to implement it?

Here is a (silly) example of what I'm trying to do:

```javascript
const Horseman = require('node-horseman');
const horseman = new Horseman();

function foo(cb) {
  console.log('Foo worked.');
  cb();
}

function bar() {
  console.log('Bar worked.');
}

horseman
  .userAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.1')
  .open('https://www.google.co.uk/')
  .evaluate(foo, bar)
  .close();
```

At this point I was looking to have this functionality in the following methods:

- `.do`
- `.evaluate`
- `.waitFor`

**Comment by awlayton** [comment]
As for `.evaluate and .waitFor`, since the communication of arguments between Node.JS and PhantomJS is done through JSON, you cannot pass functions. You can emulate it by passing the functions as strings (not pretty, but it's all you can do).

```javascript
const Horseman = require('node-horseman');
const horseman = new Horseman();

function foo(cbstr) {
  var cb;
  eval('cb = ' + cbstr);
  console.log('Foo worked.');
  cb();
}

function bar() {
  console.log('Bar worked.');
}

horseman
  .userAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.1')
  .open('https://www.google.co.uk/')
  .evaluate(foo, bar)
  .close();
```

For `.do`, the function you give it runs in Node.JS along with your horseman code. It doesn't take any arguments, but it can just access the outer scope's variables directly

```javascript
const Horseman = require('node-horseman');
const horseman = new Horseman();

function foo() {
  console.log('Foo worked.');
  bar();
}

function bar() {
  console.log('Bar worked.');
}

horseman
  .userAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.1')
  .open('https://www.google.co.uk/')
  .do(foo)
  .close();
```

**Comment by winghouchan** [comment]
Ahhh right, thanks for speedy reply @awlayton! It's not pretty indeed, but it seems like that's the way I'll have to go. (Or inject a JS file and call methods from that) Thank you!
