### ISSUE TITLE
Question: What's the best way to iterate with horseman?

### ISSUE THREAD

**Issue by JamesRBrown** [johntitus/node-horseman#157]
I've read the read me quite a bit, and I'm still not sure what the best approach for iteration with horseman is.

Let's say you have a data collection, like a number of VINs, and for each of those VINs you need to collect data from a website concerning them.  Does horseman provide a mechanism to iterate over a dataset, perhaps like jQuery's .each()?  The best idea I've had so far is to login to the page, get the cookies and URL, then close the horseman session.  Then have a function that opens a new horseman session with the cookies and URL where you can keep calling that function with a new VIN until you have made it through the whole collection.  This is burdensome though, as you have to deal with the asynchronous nature of opening and closing multiple horseman sessions, it would be easier if the entire process could be contained within a single horseman instance where by the end you have dealt with the complete dataset.

**Comment by JamesRBrown** [comment]
Finally noticed there are a few examples attached to the project, found what I was looking for:
https://github.com/johntitus/node-horseman/blob/master/examples/links.js

**Comment by awlayton** [comment]
That is one way to do that @JamesRBrown. Depending on the situation, you can also use loops.

```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman();

var buttons  = [/* array of selectors */];
var chain = horseman.open(/* URL */);
for (var i = 0; i < buttons.length; i++) {
  // Just be sure to APPEND to the chain of actions
  chain = chain.waitForSelector(buttons[i]).click();
}
```

Of course if the stop condition depends on the resolution value of a Promise you have to do something like what you linked to.
