### ISSUE TITLE
Bluebird promise library not found

### ISSUE THREAD

**Issue by winghouchan** [johntitus/node-horseman#158]
I'm attempting to use the built-in promise library, however it can't seem to be found when running a function being evaluated in the browser. Here's a simplified case:

```javascript
const debug = require('debug')('test');
const config = { 'injectBluebird': true, 'bluebirdDebug': true, };
const Horseman = require('node-horseman');
const horseman = new Horseman(config);

horseman
  .on('consoleMessage', function (msg) {
    debug(msg);
  })
  .userAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10')
  .open('https://google.com')
  .evaluate(function () {
    console.log(typeof Promise);
    console.log(typeof P);
    console.log(typeof Bluebird);
  })
  .close();
```

The output is:

```
  horseman using PhantomJS from $PATH +0ms
  horseman .setup() creating phantom instance on 12406 +6ms
  horseman phantom created +524ms
  horseman phantom version 2.0.0 +19ms
  horseman page created +10ms
  horseman phantomjs onLoadFinished triggered +10ms success NaN
  horseman injected jQuery +31ms
  horseman injected bluebird +8ms
  horseman:verbose onError +5ms ReferenceError: Can't find variable: Promise
	phantomjs://webpage.evaluate(): 4 in configBluebird
	phantomjs://webpage.evaluate(): 9 in <anonymous> 12406
  horseman .on() consoleMessage set. +7ms
  horseman .userAgent() set +22ms Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10
  horseman .open() +1ms https://google.com
  horseman phantomjs onLoadFinished triggered +767ms success 1
  horseman injected jQuery +16ms
  horseman injected bluebird +11ms
  horseman:verbose onError +4ms ReferenceError: Can't find variable: Promise
	phantomjs://webpage.evaluate(): 4 in configBluebird
	phantomjs://webpage.evaluate(): 9 in <anonymous> 12406
  horseman .evaluate() +4ms <anonymous>
  test undefined +10ms
  test undefined +0ms
  horseman:verbose .evaluate() finished synchronously +1ms <anonymous> s 12406
  horseman .close(). +5ms
```
From [Horseman documentation](https://github.com/johntitus/node-horseman#evaluatefn-arg1-arg2
), it seems I should access Bluebird via `Bluebird`.

> Lastly, if `fn` returns a Promise or thenable, it will be waited on and the action in Node will resolve/reject accordingly.

```javascript
horseman
  .open('http://en.wikipedia.org/wiki/Headless_Horseman')
  .evaluate(function() {
    // Silly example for illustrative purposes.
    return Bluebird.delay(100).return('Hello World');
  })
  .then(function(mesg){
    // Will log 'Hello World' after a roughly 100 ms delay.
    console.log(mesg);
  })
  .close();
```

From [Bluebird documentation](http://bluebirdjs.com/docs/getting-started.html), it seems I should access Bluebird via `Promise` or `P`.

> When using script tags the global variables `Promise` and `P` (alias for `Promise`) become available.

**Comment by awlayton** [comment]
You should access bluebird via `Promise` *unless* you use `injectBluebird: 'bluebird'`, *then* you access it via `Bluebird`.

> - injectBluebird: whether bluebird is automatically loaded into each page. Default is false. If true and Promise is already present on the page, it is not injected. If 'bluebird' it is always injected as Bluebird, whether Promise is present or not.

As for your code, it works when I run it with PhantomJS 2.1.1 (bluebird is available as both `Promise` and `P`). It must be something about PhantomJS 2.0.0.

**Comment by winghouchan** [comment]
@awlayton thanks for the clarification on how to use Bluebird with Horseman!

I've just rerun the test case with PhantomJS 2.1.1 however the problem is still occuring :persevere: 

```
  horseman using PhantomJS from $PATH +0ms
  horseman .setup() creating phantom instance on 12406 +5ms
  horseman phantom created +516ms
  horseman phantom version 2.1.1 +25ms
  horseman page created +11ms
  horseman phantomjs onLoadFinished triggered +15ms success NaN
  horseman injected jQuery +38ms
  horseman injected bluebird +10ms
  horseman:verbose onError +6ms ReferenceError: Can't find variable: Promise
	undefined: 4 in configBluebird
	: 9 in <anonymous> 12406
  horseman .on() consoleMessage set. +10ms
  horseman .userAgent() set +13ms Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10
  horseman .open() +3ms https://google.com
  horseman phantomjs onLoadFinished triggered +638ms success 1
  horseman injected jQuery +17ms
  horseman injected bluebird +12ms
  horseman:verbose onError +5ms ReferenceError: Can't find variable: Promise
	undefined: 4 in configBluebird
	: 9 in <anonymous> 12406
  horseman .evaluate() +6ms <anonymous>
  test undefined +11ms
  test undefined +0ms
  test undefined +0ms
  horseman:verbose .evaluate() finished synchronously +0ms <anonymous> s 12406
  horseman .close(). +8ms
```

**Comment by awlayton** [comment]
Interesting... Could you please post the output of `npm ls` along with your Node.JS version, your horseman version, and your OS? Thanks.

**Comment by winghouchan** [comment]
Sure.

Here's the output of `npm ls`:

```
├─┬ debug@2.2.0
│ └── ms@0.7.1
├── UNMET PEER DEPENDENCY eslint@^2.4.0
├── eslint-config-airbnb@6.2.0
├── eslint-plugin-react@4.2.3
├── moment@2.12.0
├─┬ node-horseman@3.0.0
│ ├── bluebird@3.3.4
│ ├── clone@1.0.2
│ ├── cookies.txt@0.1.2
│ ├── data-uri-to-buffer@0.0.4
│ ├── defaults@1.0.3
│ └── node-phantom-simple@2.2.4
└── validator@5.2.0
```

My Node.js version is `5.4.0`.

And my OS is OS X El Capitan 10.11.4.

**Comment by awlayton** [comment]
Interesting. It must have something to do with OS X, since that is the only real difference between your setup and mine. Unfortunately I do not have access to a Mac.

What if you try to log `typeof window.Promise` instead?

**Comment by winghouchan** [comment]
I've tried that as well. Still returns `undefined`. :persevere:

:thought_balloon: hmmm, I'll give this a try on a machine with a different OS later.

**Comment by awlayton** [comment]
I tried it in [Travis on OS X](https://travis-ci.org/awlayton/node-horseman/jobs/122590381#L2070) and it works there... This is a tough one.

**Comment by winghouchan** [comment]
Tough indeed.

I did a bit of digging and the `ReferenceError` is being caused here: https://github.com/johntitus/node-horseman/blob/abdfb026cb73e879ef3f187a0b8d2e0b9e5e24b2/lib/index.js#L342

**Comment by awlayton** [comment]
Yes. It appears for you the injecting of bluebird does not work, so when it tries to turn on debug for bluebird there is an error.

**Comment by awlayton** [comment]
I found something that might be the problem. Could you `npm install awlayton/node-horseman` and see if it is fixed for you @winghouchan?

**Comment by winghouchan** [comment]
It's fixed :+1: :smile:

Thank you so much @awlayton.

**Comment by awlayton** [comment]
Awesome. I'll publish a new version with the fix when I get a chance today.
