### ISSUE TITLE
Using with slimmer path

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#159]
I am getting this issue:

Error Domain: {\"name\":\"HeadlessError\",\"message\":\"Phantom immediately exited with: 255\"}

conf:

{ parameters:
   { 'ignore-ssl-errors': true,
     'load-images': true,
     'ssl-protocol': 'any',
     'web-security': false },
  path: '/vagrant_runners/slimerjs-0.9.6/slimerjs' }

**Comment by awlayton** [comment]
SlimerJS does not support the `web-security` option. See [here](https://docs.slimerjs.org/current/configuration.html#command-line-options) for which options are supported.

**Comment by mato75** [comment]
So it is by default on false, or how do we turn it off? I am testing iframes, so we need this on off.

**Comment by awlayton** [comment]
Before version 3 horseman always passed it. If you want to use horseman with SlimerJS you need to use version 3 (which only passes it if you give it to the constructor), or back-port the fix from #102.

**Comment by mato75** [comment]
How do you set up that horseman works with slimerJS, because I am having quit a bit of trouble.

Now I am getting this error:
Unexpected output from PhantomJS: SLIMERJSLAUNCHER environment variable is missing. Set it with the path to Firefox or XulRunner

**Comment by awlayton** [comment]
It looks like you can't get it to work with only node-phantom-simple (baudehlo/node-phantom-simple#127). I do not think this is a horseman issue.

**Comment by mato75** [comment]
I agree, sorry.
