### ISSUE TITLE
Port is not used by node-phantomjs-simple

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#161]
As I see in node-phantomjs-simple, it gets port on its own.

Or why do we have a port attribute in node-horseman?

**Comment by awlayton** [comment]
node-phantom-simple used to need to be told a port to use. If that is no longer the case, I guess we should remove it from horseman.

**Comment by awlayton** [comment]
At least I thought that was the reason. Was there another reason for port @johntitus?

**Comment by johntitus** [comment]
Hard to remember. It may have been a hold over from the Nightmare project which used a different Phantomjs bridge.  Feel free to kill it if you think that's best.
