### ISSUE TITLE
How to crawl multiple pages in a loop?

### ISSUE THREAD

**Issue by mort3za** [johntitus/node-horseman#162]
I want to crawl a list of pages in an array and log a selector of every page content to console.
I tried to make a loop but it looks complicated for me and using yields is hard for me (should i use yields?).
Can you please show me an example?

**Comment by awlayton** [comment]
You were not clear what your exact problem is. Perhaps this? You choices are either yields or Promise stuff.

```javascript
var Promise = require('bluebird');
var Horseman = require('node-horseman');

var SELECTOR = /* something */;
var PAGES = [/* array of URLs */];

var contents = Promise.map(function(page) {
  var hoseman = new Horseman();
  return horseman.open(page)
    .html(SELECTOR)
    .close();
});

// contents is now a Promise of an array of strings of the selector contents
```

**Comment by mort3za** [comment]
Yes this. Thanks
