### ISSUE TITLE
Screenshot with display flex is not working

### ISSUE THREAD

**Issue by sbsomya** [johntitus/node-horseman#164]
Hi 
Prepared a webpage with display flex it does not shows the given html element

**Comment by johntitus** [comment]
Can you provide an example?

**Comment by sbsomya** [comment]
I tried taking screenshot of the website
http://rocketium.com/capsules/winterswolf/the-best-walking-cities-in-the-world
But blank screen comes up 
![image_28](https://cloud.githubusercontent.com/assets/15935666/14581746/337234aa-0412-11e6-9df8-d6f5b0777de4.png)

**Comment by awlayton** [comment]
I was able to take a screenshot of the page that was not blank. Please post the code you are using, your horseman version, your PhantomJS version, and your Node.JS version @sbsomya.

**Comment by sbsomya** [comment]
var Horseman = require('node-horseman');
var horseman = new Horseman({phantomPath : require("phantomjs2").path});

horseman
    .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
    .viewport(560,800)
    .open('http://rocketium.com/capsules/winterswolf/the-best-walking-cities-in-the-world#1')
    .wait(10000)
    .screenshot("./public/capsules/image_1.png")
    .close();


With phantomjs2
horseman latest
node js 5.9


![image_1](https://cloud.githubusercontent.com/assets/15935666/14644828/0af0a46a-0671-11e6-81e5-a7a9dc4ba091.png)

**Comment by awlayton** [comment]
My screenshot worked because I had no `.delay()`. When the page tries to animate it decides PhantomJS does not support CSS animations and shows nothing. If you look at the HTML of the page after the delay, you will see this:

```html
<p>Your browser does not support CSS animations.</p>
```

**Comment by awlayton** [comment]
The problem @sbsomya is that the page is trying to use functions which are missing in PhantomJS's JavaScript environment (in particular `String.prototype.startsWith`).

I was able to make the page animations work with polyfilling.
```javascript
var Horseman = require('node-horseman');
var POLYURL = 'https://cdn.polyfill.io/v2/polyfill.min.js';

var horseman = new Horseman();

horseman
    .userAgent()
    .then(function(useragent) { // Polyfill based on the real UserAgent
        var self = this;
        return self.on('initialized', function() {
            return self.includeJs(POLYURL + '?ua=' + useragent)
        });
    })
    .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
    .viewport(560,800)
    .open('http://rocketium.com/capsules/winterswolf/the-best-walking-cities-in-the-world#1')
    .wait(10000)
    .screenshot("./public/capsules/image_1.png")
    .close();
```
The above code produces a non-blank screenshot.

**Comment by sbsomya** [comment]
Thanks a lot the pollyfill thing worked :+1:

**Comment by awlayton** [comment]
Do you think it would be good to consider building polyfill support into horseman @johntitus?

**Comment by johntitus** [comment]
Seems like a good idea, depending on how hard it is. The `loadFinishedSetup`
you made looks like a good place to inject it.

**Comment by sbsomya** [comment]
HI 

Prepared a html file 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <img id="dummyImage" src="http://media02.hongkiat.com/ww-flower-wallpapers/roundflower.jpg">
</body>
<script>
    if("somya".startsWith("som")){
        document.getElementById("dummyImage").src = "http://www.whitegadget.com/attachments/pc-wallpapers/15524d1221480898-dangerous-3d-horror-wallpapers-3d-horror-wallpape44.jpg";
    }
</script>
</html>

And phantomjs code as
var Horseman = require('node-horseman');
var POLYURL = 'https://cdn.polyfill.io/v2/polyfill.min.js';

var horseman = new Horseman();

horseman
    .userAgent()
    .then(function(useragent) { // Polyfill based on the real UserAgent
        var self = this;
        return self.on('initialized', function() {
            return self.includeJs(POLYURL + '?ua=' + useragent)
        });
    })
    .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
    .viewport(560,800)
    .open('./public/demo.html')
    .wait(10000)
    .screenshot("./public/capsules/image_1.png")
    .close();

I am getting the flower image instead of the skeleton image
Means the code inside the startsWith if loop is not working somehow
Can you help me with this thing

**Comment by sbsomya** [comment]
html file as 
image with src as image1
```
if("somya".startsWith("som")){
        document.getElementById("dummyImage").src = "image2";
    }
```
And phantomjs code as
```
var Horseman = require('node-horseman');
var POLYURL = 'https://cdn.polyfill.io/v2/polyfill.min.js';

var horseman = new Horseman();

horseman
     .userAgent()
     .then(function(useragent) { // Polyfill based on the real UserAgent 
              var self = this;
              return self.on('initialized', function() {
                  return self.includeJs(POLYURL + '?ua=' + useragent)
              });
       })
       .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
       .viewport(560,800)
       .open('./public/demo.html')
       .wait(10000)
       .screenshot("./public/capsules/image_1.png")
       .close();
```

The image 1 only comes in the screenshot instead image 2 should come
Means the code inside the startsWith if loop is not working somehow
Can you help me with this thing

**Comment by awlayton** [comment]
The polyfilling the way I did it does not necessarily finish before the page's JavaScript starts running. I was aware of that, which is why I was thinking horseman should have it built in. Making it happen before the page's code would be more complicated and probably require changes to horseman.

**Comment by awlayton** [comment]
I think I found a way to inject the polyfill *before* any of the page's JavaScript runs @sbsomya and @johntitus.

As far as I can tell it works, but it is.... *not* pretty. When I run it `String.prototype.startsWith` is polyfilled when the HTML loads (i.e., my `console.log` prints). I ended up downloading the code of the polyfill, then running it synchronously in PhantomJS (*not* Node.JS) when the initialized event fires.

If you find something wrong with this, or think of a *nicer* way to achieve this, *please* let me know.

```javascript
var Horseman = require('node-horseman');
var POLYURL = 'https://cdn.polyfill.io/v2/polyfill.min.js';

var horseman = new Horseman();

horseman
    .userAgent()
    .then(function(useragent) { // Get Polyfill based on real UserAgent
        return this.download(POLYURL + '?ua=' + useragent);
    })
    .then(function(polyfill) {
        // Make polyfill into function
        var polyfun = new Function(polyfill);
        // Wrap function in evaluateJavaScript
        var onInit = new Function(
            'console.log("onInitialized");' +
            'page.evaluateJavaScript(' + polyfun.toString() + ')'
        );
        // Call before page loads
        return this.at('initialized', onInit);
    })
    .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
    .viewport(560,800)
    .open('i164.html')
    .wait(100)
    .reload()
    .wait(100)
    .close();

```

# i164.html#
```html
<script>
    if ('somya'.startsWith('som')) {
        console.log('HERE');
    }
</script>
```

**Comment by awlayton** [comment]
Closing, since this is more of a PhantomJS issue. Also, I opened #230 which would hopefully help this sort of thing.
