### ISSUE TITLE
Unhandled rejection click evaluatePage  global code error

### ISSUE THREAD

**Issue by Rafi993** [johntitus/node-horseman#165]
I installed node-horseman and i downloaded phantomjs and set it to environment variable (windows 7 64bit) when I tried to execute 

```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman();
horseman
  .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
  .open('http://www.google.com')
  .type('input[name="q"]', 'github')
  .click('button:contains("Google Search")')
  .keyboardEvent('keypress', 16777221)
  .waitForSelector('div.g')
  .count('div.g')
  .log() // prints out the number of results
  .close();
```

I got the following error
```

Unhandled rejection click
evaluatePage

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61
    at C:\Users\test\Desktop\horse\node_modules\node-horseman\lib\actions
.js:989:36
    at tryCatcher (C:\Users\test\Desktop\horse\node_modules\bluebird\js\r
elease\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (C:\Users\test\Desk
top\horse\node_modules\bluebird\js\release\promise.js:176:30)
    at Horseman.<anonymous> (C:\Users\test\Desktop\horse\node_modules\nod
e-horseman\lib\actions.js:987:29)
    at Horseman.tryCatcher (C:\Users\test\Desktop\horse\node_modules\blue
bird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\test\Desktop\horse\nod
e_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Users\test\Desktop\horse\node_modules\b
luebird\js\release\promise.js:559:18)
    at Promise._settlePromiseCtx (C:\Users\test\Desktop\horse\node_module
s\bluebird\js\release\promise.js:596:10)
    at Async._drainQueue (C:\Users\test\Desktop\horse\node_modules\bluebi
rd\js\release\async.js:143:12)
    at Async._drainQueues (C:\Users\test\Desktop\horse\node_modules\blueb
ird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\test\Deskt
op\horse\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

```
I even tried using
```
var phantomjs = require('phantomjs');
var horseman = new Horseman({phantomPath: phantomjs.path});
```

**Comment by awlayton** [comment]
The `.click()` is failing because the selector you tried to click does not exist.

**Comment by Rafi993** [comment]
this code is from the example of node-horseman

**Comment by awlayton** [comment]
Yes, google has apparently changed their page since the example was made. It is hard to make a scrape that works for long periods.

**Comment by Rafi993** [comment]
is there any workaround it ?

**Comment by Rafi993** [comment]
and the selector exist
`
<div class="g">
`
the code seems to work fine when using keyboardEvent without click().

**Comment by awlayton** [comment]
The selector that is the problem is `'button:contains("Google Search")'`. That element matches the selector `'div.g'` which is *not* what you are trying to click. There is no "workaround" because there is no bug.

A selector which *does* match match the current search button is `'input[value="Google Search"]'`.

**Comment by Rafi993** [comment]
Thanks awlayton for the help.

**Comment by choxi** [comment]
Would it be possible to catch the error and throw a more friendly "Click selector not found" message?

**Comment by awlayton** [comment]
Since different versions of PhantomJS throw slightly different errors, it would probably being easier (though kinda wasteful) to have horseman check is the selector is missing and throw an appropriate error @choxi. I would prefer catching the specific error of the selector not existsing, but I do not have the time lately to figure out how. I would be happy to accept a PR doing so though.
