### ISSUE TITLE
Does the screenshot takes some time of its own 

### ISSUE THREAD

**Issue by sbsomya** [johntitus/node-horseman#166]
Hi actually need to capture screenshots of a website in 40ms of time difference 
So does our screenshot capturing take some time 
or can i execute it in parallel

**Comment by awlayton** [comment]
I'm sure the screenshot take some amount of time. I do not no if it's on the order of 1ms or 10ms. I am not sure what you mean by "execute it in parallel".

**Comment by sbsomya** [comment]
Execute in parallel means let the window keep on running at a particular pace and capture the screenshots seperately

**Comment by awlayton** [comment]
I'm still not sure what you mean. If you are asking if the JavaScript on the page keeps executing while you are taking screenshot, I think so but I am not certain. You would probably need to ask on the PhantomJS mailing list about that to know for sure. However, I doubt the screenshot takes long enough for it to usually matter if the page pauses briefly.

**Comment by sbsomya** [comment]
Yes you got it right but yes its not mattering much

**Comment by sbsomya** [comment]
Saw the millisecond difference before the screenshot and in the then function comes out to be 120 ms 

horseman
    .on('consoleMessage', function( msg ){
        console.log(msg);
    })
    .viewport(560,800)
    .open('http://google.com')
    .then(function () {
       var presentTime = new Date().getTime();
        horseman
           .screenshot("img1.png")
           .then(function () {
                var endTime = new Date().getTime();
                console.log(endTime - presentTime);
            })
    });

**Comment by awlayton** [comment]
So does that keep you from doing what you wanted?

**Comment by sbsomya** [comment]
Yes actually aim is to capture images for a video 
In which require 25 frames/sec
which is every 40 milli second need a screenshot

So this results into a output which in realtime is more than 40 milli second

**Comment by awlayton** [comment]
There is nothing horseman can do about how long phantom takes to do a screenshot. Also, taking a bunch of screenshots is *not* a particularly practical way to create a video.

I admit the time you reported is rather long, but that is not necessarily how long the screenshot took (it is an upper limit). There is a fair bit of polling involved which can throw off the time.

You could try taking the screenshots without waiting for the previous screenshot to finish.

**Comment by awlayton** [comment]
I am not claiming it is the *best* way to do it, but the below *works* for me @sbsomya.

```javascript
var Promise = require('bluebird');
var Horseman = require('node-horseman');

const URL = 'http://giphy.com/gifs/goat-ouch-6MBrUyxJuIoLu';
const RATE = 40;
const FRAMES = 100;

var horseman = new Horseman();

var p = horseman.open(URL);

var ps = []
for (var i = 0; i < FRAMES; i++) {
    ps[i] = p.delay(RATE * i).screenshot('frame' + i + '.png');
}

Promise.all(ps).then(function(ps) {
    console.log('Done');   
    return horseman.close();
});
```

**Comment by sbsomya** [comment]
This also is a faster as in images u can see the goat jumping in 5 images but should have done it in 25
No worries we figured out a way a slowed our animations so in the images it looks like happening in real

**Comment by awlayton** [comment]
I am closing this since all `.screenshot()` does is call PhantomJS's `.render()`, so I don't see how horseman can do anything about it being slow.
