### ISSUE TITLE
Phantomjs processes not exiting on close?

### ISSUE THREAD

**Issue by MichaelJCole** [johntitus/node-horseman#168]
Hi, Horseman is great.  I'm using it on a site that sometimes crashes.  After a crash, I run the following code.  It happens alot.

```javascript
  reboot() {
    if (this.page) {
      this.oldPage = this.page // dont garbage collect to quickly?
      this.oldPage.close() // This happens, but doesn't close the process.
    }
    this.page = new Horseman({ignoreSSLErrors: true})
    return this.page.userAgent(this.config.userAgent)
    .open(config.crashyUrl)
    .then(() => { return this.doSomeSetup() })
  }
```

When I call this.oldPage.close(), the phantomjs process sticks around.  I wouldn't care, except they start to exhaust memory.

Is this a bug in close() or am I doing it wrong?

```
  horseman .screenshot() +5ms screenshots/error-1461516618812.png
  horseman .setup() creating phantom instance on 12411 +0ms
scrape error
  horseman phantom created +90ms
  horseman phantom version 2.1.1 +2ms
  horseman page created +4ms
  horseman phantomjs onLoadFinished triggered +4ms success NaN
  horseman injected jQuery +12ms
  horseman .url() +994ms
  horseman .close(). +2ms
  horseman .setup() creating phantom instance on 12412 +0ms
  horseman phantom created +88ms
  horseman phantom version 2.1.1 +2ms
  horseman page created +6ms
  horseman phantomjs onLoadFinished triggered +5ms success NaN
  horseman injected jQuery +14ms
  horseman .userAgent() set +6ms Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
  horseman .open() +0ms http://www2.vauto.com/Va/Appraisal/Default.aspx?new=true
  horseman phantomjs onLoadFinished triggered +2s success 1
  horseman jQuery not injected - already exists on page +2ms

```

Thanks!

**Comment by awlayton** [comment]
It is hard to tell from what you have posted. It is possible there is a bug in horseman's close, or there could be a bug in the underlying node-phantom-simple library.

As few specifics might help. Could you run in with `DEBUG=*` set and show what is printed? Also, how exactly are you determining that PhantomJS process is still around? I only ask because Node.JS can be pretty lazy about garbage collecting, it could be everything is working and it just hasn't gotten around to freeing any of the memory.

**Comment by MichaelJCole** [comment]
Hey @awlayton this was a bug in my code :-/  Sorry to interrupt!  Switched to horseman after trouble with another lib.  Absolutely love it.  Thanks!

**Comment by awlayton** [comment]
Glad you got it to work.
