### ISSUE TITLE
Phantomjs taking upto 90% of CPU 

### ISSUE THREAD

**Issue by sbsomya** [johntitus/node-horseman#169]
Hi 

Using node-horseman 
actually phantomjs is eating upto 90% of the CPU is there a way i can reduce it

**Comment by johntitus** [comment]
Not that I'm aware of. If you're sure it's PhanomJS, you may want to ask them.  https://github.com/ariya/phantomjs/issues

**Comment by awlayton** [comment]
Closing since there is now ariya/phantomjs#14227.

**Comment by gouchaoer** [comment]
check this issue:#14334
this bug also take 90% of cpu
