### ISSUE TITLE
video.play() does not work with node-horseman

### ISSUE THREAD

**Issue by sbsomya** [johntitus/node-horseman#170]
In html having a video play option in javascript 
Its not working 
getting a blank screen

**Comment by awlayton** [comment]
I am not sure PhantomJS supports HTML5 video, at least not 1.x. Maybe 2 does. What version of PhantomJS are you using?

**Comment by sbsomya** [comment]
Using 2.1.1

**Comment by awlayton** [comment]
It seems that it is not supported. ariya/phantomjs#10839
