### ISSUE TITLE
Screenshot taking 120 ms of time

### ISSUE THREAD

**Issue by sbsomya** [johntitus/node-horseman#171]
Saw the millisecond difference before the screenshot and in the then function comes out to be 120 ms

horseman
.on('consoleMessage', function( msg ){
console.log(msg);
})
.viewport(560,800)
.open('http://google.com')
.then(function () {
var presentTime = new Date().getTime();
horseman
.screenshot("img1.png")
.then(function () {
var endTime = new Date().getTime();
console.log(endTime - presentTime);
})
});

**Comment by awlayton** [comment]
Why did you open as issue for this?
