### ISSUE TITLE
clientScripts option is not working

### ISSUE THREAD

**Issue by codynguyen** [johntitus/node-horseman#172]
Hello,

I'm trying to use `clientScripts` to inject test-specific scripts onto the page in our test environment but it is not working. Looking at the source code, apparently the `clientScripts` option is not processed anywhere [nor is it passed to phantomjs](https://github.com/johntitus/node-horseman/blob/master/lib/index.js#L95-L133).

**Comment by awlayton** [comment]
It does seem that the `clientScripts` option does not do anything. Is it another vestigial option or something @johntitus?

**Comment by codynguyen** [comment]
Hi @awlayton @johntitus, is there any update on the status of `clientScripts`? Thanks.

**Comment by awlayton** [comment]
The current status is that the option is not used by the code. I would accept a pull request to implement it, but I do not have any time to write the code myself lately.

We could also just remove the option, since there are already [`.injectJs()`](https://github.com/johntitus/node-horseman#injectjsfile) and [`.includeJs()`](https://github.com/johntitus/node-horseman#includejsurl) actions.

**Comment by awlayton** [comment]
How do you feel about `clientScripts` @wong2?

**Comment by wong2** [comment]
@awlayton I found `clientScripts` does existed in the [first commit](https://github.com/johntitus/node-horseman/blob/e93bbd7f64a95686758e5233352651d9a7f450da/lib/index.js#L106) of this project (when it's still called `Creeper`), but later removed in [this commit](https://github.com/johntitus/node-horseman/commit/d2e200902288a15916d664e13714f9fde59e09e3), so I think maybe @johntitus forgot to remove it from the README.

I'm +1 for just remove the option, anyway it's just a wrapper for multiple `.injectJs()`

**Comment by awlayton** [comment]
Thanks for figuring that out @wong2.

**Comment by awlayton** [comment]
Thanks for noticing this @codynguyen. You can use `.injectJs()` instead.
