### ISSUE TITLE
Add phantomjs-prebuilt to package.json requirements

### ISSUE THREAD

**Issue by grgisme** [johntitus/node-horseman#173]
There may be a reason you haven't done this, but adding phantomjs-prebuilt to the list of requirements in package.json would go a long way to making this more "plug and play".

**Comment by awlayton** [comment]
We have already considered this and decided not to. For one thing horseman can use SlimerJS instead. Also phantom is usually installed without npm.

**Comment by awlayton** [comment]
I would be open to considering adding it to `optionalDepencies`.

**Comment by grgisme** [comment]
Thanks for the response -- I'll have to checkout SlimerJS too.
