### ISSUE TITLE
Is SlimerJS officially supported?

### ISSUE THREAD

**Issue by winghouchan** [johntitus/node-horseman#179]
Looking through the documentation there is no mention of support for [SlimerJS](https://slimerjs.org/). However #99 shows that SlimerJS does work with Horseman and #102 shows a fix applied to Horseman to resolve an issue between Horseman and SlimerJS. All of this suggests that SlimerJS is _officially_ supported however documentation doesn't suggest that so in the end it's a bit confusing.

**tl;dr** Is SlimerJS officially supported by Horseman? If it is, would it be possible that documentation mentions it and/or any advantages/caveats? 😃

**Comment by awlayton** [comment]
I don't think I would say SlimerJS is *officially* supported. However, SlimerJS *does* work with horseman.

SlimerJS is still a work in progress and many PhantomJS features are net yet implemented in SlimerJS, so some horseman things that work with PhantomJS won't work with SlimerJS.

The main reason it is not documented is that I myself have not used it, and I do not know exactly what does and does not work yet.

**Comment by winghouchan** [comment]
Ahh okai, thanks for clarifying this @awlayton 👍
