### ISSUE TITLE
Unhandled rejection HeadlessError: Phantom immediately exited with: 127

### ISSUE THREAD

**Issue by wmjones228** [johntitus/node-horseman#182]
Hi,

I recently rebuilt the machine however afterward my program returns this error
I properly installed phantomjs-prebuilt, phantomjs and node_horseman 

I did some search and 127 is related to the command can not be found, then I explicitly states but  still no luck.
```javascript
var phantomjs = require('phantomjs');
var horseman = new Horseman({phantomPath: phantomjs.path});
```

Anyone has any idea?
Thanks in advance

```
  horseman phantom created +9ms
Unhandled rejection HeadlessError: Phantom immediately exited with: 127
    at ChildProcess.immediateExit (/root/node_modules/node-phantom-simple/node-phantom-simple.js:153:23)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by awlayton** [comment]
The command not being found is not the *only* cause for code 127 @wmjones228. Have you tried the solution to ariya/phantomjs#13597?

**Comment by awlayton** [comment]
Closing since this is likely not a horseman problem, and there has been no response.
