### ISSUE TITLE
iframes?

### ISSUE THREAD

**Issue by ellisgl** [johntitus/node-horseman#183]
How do you access iframes? I've tried about 20 different ways, but am unable to access their contents.

**Comment by awlayton** [comment]
You just use the [frame actions](https://github.com/johntitus/node-horseman#frames) to switch from the main from to another one. Then you use the other actions normally (e.g. `.html()`), but instead of using the main frame they will use the one you switched to.

**Comment by ellisgl** [comment]
Thanks. Last night it wasn't working for me, now it is.
