### ISSUE TITLE
Selector not working

### ISSUE THREAD

**Issue by ellisgl** [johntitus/node-horseman#185]
I can do this:
```javascript
.click('body > table > tbody > tr > td > a:nth-child(31)')
```

But I can't do
```javascript
.click('a[href^="categorynav.aspx?aid=3752&kb=4&L1cid=1217"]')
```

Tested int he browser - and this works fine.

**Comment by awlayton** [comment]
Please post detail. Phantom version, horseman version, website info, what browser you tested in, complete horseman code, etc.

**Comment by ellisgl** [comment]
Horseman 3.0.1
PhantomJS 2.1.1
Chrome  50.0.2661.102 m
Site info - It's a KB that has frames and iframes which uses SSO login.
Ever thing works up to the point where I'm want to click some links in an iframe (Only work if I do body > table....a:nth-child). 

code (Just trying to get to work before making it modular and pretty)

	var Horseman = require('node-horseman');
	var horseman = new Horseman({timeout: 30000});

	horseman
		.open('https://somesite')
		//.html()
		//.log()
		.type('input[name="login"]', 'someuser')
		.type('input[name="passwd"]', 'somepassword')
		.click('span[id="cred_sign_in_button"]')
		.waitForNextPage()
		.type('input[name="Password"]', 'Somepasswordagain')
		.click('span[id="submitButton"]')
		.waitForNextPage()
		.wait(1000)
		.waitForNextPage()
		.wait(1000)
		.waitForNextPage()
		.switchToFrame("navframe")
		.wait(1000)
		.click('td[id="Col4"]')
		.waitForNextPage()
		.wait(1000)
		.switchToMainFrame()
		.switchToFrame("mainframe")
		.switchToFrame("subnavframe")
		.click('body > div > table:nth-child(1) > tbody > tr:nth-child(1) > td')
		.waitForNextPage()
		.wait(1000)
		.switchToParentFrame()
		.switchToFrame('mainframe')
		.switchToFrame('submainframe')
		.click('body > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr > td:nth-child(1) > a')
		.waitForNextPage()
		.wait(1000)
		.select('select[name="wflidnv"]', '5')
		.wait(1000)
		.select('select[name="wfstatus"]', '1366')
		.type('input[name="articletitle"]', 'Testing')
		.click('input[id="btnSubmit"]')
		.waitForNextPage()
		.wait(1000)
		.evaluate(function()
		{
			return {
				html : $('#ct63').html('<strong>Testing</strong> some stuff out.')
			}
		})
		.wait(1000)
		.click('input[id="Save"]')
		.waitForNextPage()
		.wait(1000)
		.click('#versions > table > tbody > tr > td > a:nth-child(2)')
		.wait(1000)
		.click('#box_artGroups > table > tbody > tr > td.defaultText > a')
		.wait(1000)
		.evaluate(function()
		{
			return {
				attribute: $('input[name="group"][value="12"]').attr('checked', 'true')
			};
		})
		.wait(3000)
		.click('input[name="submitButton"]')
		.waitForNextPage()
		.wait(3000)
		.click('#box_artCategories > table > tbody > tr > td.smalltext > a')
		.waitForNextPage()
		.wait(3000)
		.switchToFrame('kbCatIframe')
		.switchToFrame('catnavframe')
		//.click('body > table > tbody > tr > td > a:nth-child(31)')
		.click('a[href^="categorynav.aspx?aid=3752&kb=4&L1cid=1217"]')
		.wait(1000)
		.html()
		.log()
		.screenshot('shots/inner.png')
		.close();

**Comment by ellisgl** [comment]
Oh here's link I'm trying to "click" on.

<a href="categorynav.aspx?aid=3762&amp;kb=4&amp;L1cid=1217&amp;level=2&amp;mod=&amp;r=0.5908441" class="smalltext"><img src="/images/nav/folderclosed_plus.gif" border="0" align="absmiddle"></a>

**Comment by awlayton** [comment]
I see, so iframes are involved...

The first thing I notice @ellisgl is that the `<a>` tag has `&amp;` in it, but your selector just has `&` in it. Are you sure it is not as simple as that?

**Comment by ellisgl** [comment]
I first tried with &amp; because that's how it copied from chrome, &amp; didn't work in my test in Chrome, but worked with &. So both ways trigger a crash.

**Comment by awlayton** [comment]
Is it *crashing*, or is the `.click()` Promise just rejecting?

Would it be possible for you to post the output of running your script with `DEBUG='horseman*' BLUEBIRD_DEBUG=1` set?

**Comment by ellisgl** [comment]
(node:8352) Warning: a promise was rejected with a non-error: [object Object]
(node:8352) Warning: a promise was rejected with a non-error: [object Object]
(node:8352) Warning: a promise was rejected with a non-error: [object Object]
Unhandled rejection click
evaluatePage

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61
    at C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\actions.js:989:36
    at Horseman.<anonymous> (C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\actions.js:987:29)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Horseman.evaluatePage (C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\actions.js:984:20)
    at Horseman.exports.__evaluate (C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\actions.js:973:22)
    at Horseman.(anonymous function) [as __evaluate] (C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\index.js:398:17)
    at Horseman.exports.click (C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\actions.js:343:14)
    at Horseman.(anonymous function) [as click] (C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\index.js:398:17)
    at Horseman.<anonymous> (C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\index.js:406:22)
    at C:\xampp\htdocs\kbimport\node_modules\node-phantom-simple\node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (C:\xampp\htdocs\kbimport\node_modules\node-phantom-simple\node-phantom-simple.js:645:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Promise.HorsemanPromise.(anonymous function) [as click] (C:\xampp\htdocs\kbimport\node_modules\node-horseman\lib\index.js:404:15)
    at Object.<anonymous> (C:\xampp\htdocs\kbimport\index.js:77:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3

**Comment by ellisgl** [comment]
It's the same things with &amp;amp;

**Comment by awlayton** [comment]
There should be ***much*** more output @ellisgl.

**Comment by ellisgl** [comment]
Went I set the environment variables the only thing that is added is:

(node:8352) Warning: a promise was rejected with a non-error: [object Object]
(node:8352) Warning: a promise was rejected with a non-error: [object Object]
(node:8352) Warning: a promise was rejected with a non-error: [object Object]

Also I'm running this under Windows. Let me fire up my Linux box and if it's any different.

**Comment by ellisgl** [comment]
horseman using PhantomJS from $PATH +0ms
	  horseman .setup() creating phantom instance on 12406 +14ms
	  horseman phantom created +149ms
	  horseman phantom version 2.1.1 +17ms
	  horseman page created +9ms
	  horseman phantomjs onLoadFinished triggered +10ms success NaN
	  horseman injected jQuery +21ms
	  horseman .open() +4ms https://kbadmin-******.kb.net
	  horseman phantomjs onLoadFinished triggered +3s success 1
	  horseman jQuery not injected - already exists on page +7ms
	  horseman .type() +7ms input[name="login"] ********** undefined
	  horseman .keyboardEvent() +18ms keypress * null
	  horseman .keyboardEvent() +6ms keypress  * null
	  horseman .keyboardEvent() +11ms keypress * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +12ms keypress * null
	  horseman .keyboardEvent() +6ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +9ms keypress  * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +6ms keypress  * null
	  horseman .keyboardEvent() +9ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +9ms keypress  * null
	  horseman .keyboardEvent() +9ms keypress  * null
	  horseman .keyboardEvent() +10ms keypress * null
	  horseman .keyboardEvent() +8ms keypress  * null
	  horseman .keyboardEvent() +10ms keypress * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .type() +1ms input[name="passwd"] ******** undefined
	  horseman .keyboardEvent() +36ms keypress * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +4ms keypress  * null
	  horseman .keyboardEvent() +3ms keypress  * null
	  horseman .keyboardEvent() +4ms keypress  * null
	  horseman .keyboardEvent() +8ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +3ms keypress  * null
	  horseman .keyboardEvent() +9ms keypress  * null
	  horseman .click() +0ms span[id="cred_sign_in_button"]
	  horseman .click() done +8ms
	  horseman .waitForNextPage() +0ms
	  horseman phantomjs onLoadFinished triggered +4s success 2
	  horseman injected jQuery +15ms
	  horseman .waitForNextPage() completed successfully +2ms
	  horseman .type() +1ms input[name="Password"] ********** undefined
	  horseman .keyboardEvent() +21ms keypress * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +5ms keypress  * null
	  horseman .keyboardEvent() +15ms keypress * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +7ms keypress  * null
	  horseman .keyboardEvent() +16ms keypress * null
	  horseman .keyboardEvent() +4ms keypress  * null
	  horseman .keyboardEvent() +4ms keypress  * null
	  horseman .click() +1ms span[id="submitButton"]
	  horseman .click() done +9ms
	  horseman .waitForNextPage() +0ms
	  horseman phantomjs onLoadFinished triggered +384ms success 3
	  horseman injected jQuery +10ms
	  horseman .waitForNextPage() completed successfully +11ms
	  horseman .wait() +0ms 1000
	  horseman phantomjs onLoadFinished triggered +486ms success 4
	  horseman injected jQuery +29ms
	  horseman phantomjs onLoadFinished triggered +482ms success 5
	  horseman .waitForNextPage() +3ms
	  horseman injected jQuery +6ms
	  horseman .waitForNextPage() completed successfully +53ms
	  horseman .wait() +1ms 1000
	  horseman phantomjs onLoadFinished triggered +442ms success 6
	  horseman injected jQuery +8ms
	  horseman .waitForNextPage() +550ms
	  horseman .waitForNextPage() completed successfully +51ms
	  horseman .switchToFrame() +1ms navframe
	  horseman .wait() +2ms 1000
	  horseman .click() +1s td[id="Col4"]
	  horseman phantomjs onLoadFinished triggered +20ms success 7
	  horseman .click() done +0ms
	  horseman .waitForNextPage() +1ms
	  horseman injected jQuery +13ms
	  horseman .waitForNextPage() completed successfully +54ms
	  horseman .wait() +0ms 1000
	  horseman .switchToMainFrame() +1s
	  horseman .switchToFrame() +9ms mainframe
	  horseman .switchToFrame() +11ms subnavframe
	  horseman .click() +6ms body > div > table:nth-child(1) > tbody > tr:nth-child(1) > td
	  horseman .click() done +10ms
	  horseman .waitForNextPage() +0ms
	  horseman phantomjs onLoadFinished triggered +2s success 8
	  horseman .waitForNextPage() completed successfully +25ms
	  horseman .wait() +1ms 1000
	  horseman injected jQuery +4ms
	  horseman .switchToParentFrame() +1s
	  horseman .switchToFrame() +8ms mainframe
	  horseman .switchToFrame() +10ms submainframe
	  horseman .click() +8ms body > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr > td:nth-child(1) > a
	  horseman .click() done +29ms
	  horseman .waitForNextPage() +0ms
	  horseman phantomjs onLoadFinished triggered +423ms success 9
	  horseman injected jQuery +9ms
	  horseman .waitForNextPage() completed successfully +34ms
	  horseman .wait() +0ms 1000
	  horseman .select() +1s select[name="wflidnv"] 5
	  horseman .value() +0ms select[name="wflidnv"] 5
	  horseman .wait() +11ms 1000
	  horseman phantomjs onLoadFinished triggered +460ms success 10
	  horseman injected jQuery +23ms
	  horseman .select() +519ms select[name="wfstatus"] 1366
	  horseman .value() +0ms select[name="wfstatus"] 1366
	  horseman .type() +25ms input[name="articletitle"] Testing undefined
	  horseman .keyboardEvent() +18ms keypress T null
	  horseman .keyboardEvent() +8ms keypress e null
	  horseman .keyboardEvent() +4ms keypress s null
	  horseman .keyboardEvent() +4ms keypress t null
	  horseman .keyboardEvent() +9ms keypress i null
	  horseman .keyboardEvent() +3ms keypress n null
	  horseman .keyboardEvent() +4ms keypress g null
	  horseman .click() +0ms input[id="btnSubmit"]
	  horseman .click() done +6ms
	  horseman .waitForNextPage() +0ms
	  horseman phantomjs onLoadFinished triggered +1s success 11
	  horseman jQuery not injected - already exists on page +15ms
	  horseman .waitForNextPage() completed successfully +10ms
	  horseman .wait() +0ms 1000
	  horseman .evaluate() +1s <anonymous>
	  horseman:verbose .evaluate() finished synchronously +37ms <anonymous> s 12406
	  horseman .wait() +3s 1000
	  horseman .click() +1s input[id="Save"]
	  horseman .click() done +43ms
	  horseman .waitForNextPage() +0ms
	  horseman phantomjs onLoadFinished triggered +2s success 12
	  horseman .waitForNextPage() completed successfully +2ms
	  horseman .wait() +0ms 1000
	  horseman injected jQuery +11ms
	  horseman .click() +1s #versions > table > tbody > tr > td > a:nth-child(2)
	  horseman .click() done +42ms
	  horseman .wait() +0ms 1000
	  horseman .click() +1s #box_artGroups > table > tbody > tr > td.defaultText > a
	  horseman .click() done +5ms
	  horseman .wait() +0ms 1000
	  horseman phantomjs onLoadFinished triggered +460ms success 13
	  horseman injected jQuery +7ms
	  horseman .evaluate() +533ms <anonymous>
	  horseman:verbose .evaluate() finished synchronously +6ms <anonymous> s 12406
	  horseman .wait() +2s 3000
	  horseman .click() +3s input[name="submitButton"]
	  horseman .click() done +21ms
	  horseman .waitForNextPage() +0ms
	  horseman phantomjs onLoadFinished triggered +1s success 14
	  horseman injected jQuery +8ms
	  horseman .waitForNextPage() completed successfully +42ms
	  horseman .wait() +0ms 3000
	  horseman .click() +3s #box_artCategories > table > tbody > tr > td.smalltext > a
	  horseman .click() done +9ms
	  horseman .waitForNextPage() +0ms
	  horseman phantomjs onLoadFinished triggered +1s success 15
	  horseman .waitForNextPage() completed successfully +8ms
	  horseman .wait() +0ms 3000
	  horseman injected jQuery +23ms
	  horseman .switchToFrame() +3s kbCatIframe
	  horseman .switchToFrame() +9ms catnavframe
	  horseman .click() +8ms a[href^="categorynav.aspx?aid=3752&amp;kb=4&amp;L1cid=1217"]
	(node:3217) Warning: a promise was rejected with a non-error: [object Object]
	  horseman .close(). +13ms
	(node:3217) Warning: a promise was rejected with a non-error: [object Object]
	(node:3217) Warning: a promise was rejected with a non-error: [object Object]
	Unhandled rejection click
	evaluatePage

	global code
	evaluateJavaScript@[native code]
	evaluate@phantomjs://platform/webpage.js:390:39
	phantomjs://code/bridge.js:121:61
		at /home/******/kbimport/node_modules/node-horseman/lib/actions.js:989:36
		at Horseman.<anonymous> (/home/******/kbimport/node_modules/node-horseman/lib/actions.js:987:29)
		at tryOnImmediate (timers.js:543:15)
		at processImmediate [as _immediateCallback] (timers.js:523:5)
	From previous event:
		at Horseman.evaluatePage (/home/******/kbimport/node_modules/node-horseman/lib/actions.js:984:20)
		at Horseman.exports.__evaluate (/home/******/kbimport/node_modules/node-horseman/lib/actions.js:973:22)
		at Horseman.(anonymous function) [as __evaluate] (/home/******/kbimport/node_modules/node-horseman/lib/index.js:398:17)
		at Horseman.exports.click (/home/******/kbimport/node_modules/node-horseman/lib/actions.js:343:14)
		at Horseman.(anonymous function) [as click] (/home/******/kbimport/node_modules/node-horseman/lib/index.js:398:17)
		at Horseman.<anonymous> (/home/******/kbimport/node_modules/node-horseman/lib/index.js:406:22)
		at /home/******/kbimport/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
		at IncomingMessage.<anonymous> (/home/******/kbimport/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
		at emitNone (events.js:91:20)
		at IncomingMessage.emit (events.js:185:7)
		at endReadableNT (_stream_readable.js:926:12)
		at _combinedTickCallback (internal/process/next_tick.js:74:11)
		at process._tickCallback (internal/process/next_tick.js:98:9)
	From previous event:
		at Promise.HorsemanPromise.(anonymous function) [as click] (/home/******/kbimport/node_modules/node-horseman/lib/index.js:404:15)
		at Object.<anonymous> (/home/******/kbimport/index.js:77:6)
		at Module._compile (module.js:541:32)
		at Object.Module._extensions..js (module.js:550:10)
		at Module.load (module.js:456:32)
		at tryModuleLoad (module.js:415:12)
		at Function.Module._load (module.js:407:3)
		at Function.Module.runMain (module.js:575:10)
		at startup (node.js:159:18)
		at node.js:444:3

**Comment by awlayton** [comment]
Maybe  PhantomJS doesn't support the `[^=]` CSS selector? I am not sure how good PhantomJS's CSS3 selector support is, and horseman will only inject jQuery into the *main* frame.

Maybe you could try `[|=]` instead @ellisgl?

**Comment by ellisgl** [comment]
That didn't work:

  horseman .click() +3ms a[href|="categorynav.aspx?aid=3752&kb=4&L1cid=1217"]
(node:2994) Warning: a promise was rejected with a non-error: [object Object]
  horseman .close(). +8ms
(node:2994) Warning: a promise was rejected with a non-error: [object Object]
(node:2994) Warning: a promise was rejected with a non-error: [object Object]
Unhandled rejection click
evaluatePage

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61
    at /home/kmccall/kbimport/node_modules/node-horseman/lib/actions.js:989:36
    at Horseman.<anonymous> (/home/kmccall/kbimport/node_modules/node-horseman/lib/actions.js:987:29)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Horseman.evaluatePage (/home/kmccall/kbimport/node_modules/node-horseman/lib/actions.js:984:20)
    at Horseman.exports.__evaluate (/home/kmccall/kbimport/node_modules/node-horseman/lib/actions.js:973:22)
    at Horseman.(anonymous function) [as __evaluate] (/home/kmccall/kbimport/node_modules/node-horseman/lib/index.js:398:17)
    at Horseman.exports.click (/home/kmccall/kbimport/node_modules/node-horseman/lib/actions.js:343:14)
    at Horseman.(anonymous function) [as click] (/home/kmccall/kbimport/node_modules/node-horseman/lib/index.js:398:17)
    at Horseman.<anonymous> (/home/kmccall/kbimport/node_modules/node-horseman/lib/index.js:406:22)
    at /home/kmccall/kbimport/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/home/kmccall/kbimport/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Promise.HorsemanPromise.(anonymous function) [as click] (/home/kmccall/kbimport/node_modules/node-horseman/lib/index.js:404:15)
    at Object.<anonymous> (/home/kmccall/kbimport/index.js:77:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3

**Comment by awlayton** [comment]
There are already injection functions (`.injectJs()` and `.includeJs()`). I have never tested it, but I would think they would work with switching frames.

**Comment by awlayton** [comment]
Could it just be because all the selectors you've posted have `aid=3752`, but the href has `aid=3762` @ellisgl?

It seems to work for me when I change the 5 to a 6 (using `&`, not `&amp;`).

**Comment by ellisgl** [comment]
I'm trying .includeJs('http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js') - and working down the code at the moment.

**Comment by ellisgl** [comment]
Yeah, so the AID changes each time I run the script! D'OH! But you do need to include jQuery to get the cool css selectors.

**Comment by awlayton** [comment]
So PhatnomJS does not support `[^=]` then?

**Comment by ellisgl** [comment]
Not sure yet about that. I know it doesn't like the ":contains()" if jQuery isn't loaded up.

**Comment by ellisgl** [comment]
So a[href*="whatever"] works with out needing to inject. Now to figure out how to get the confirm() to work...

**Comment by awlayton** [comment]
Well `:contains()` is a jQuery thing, not a real CSS selector. I was curious about `^=` since it's CSS 3, but if `*=` works it probably does too.
