### ISSUE TITLE
[Help] How to click on a selector inside a table?

### ISSUE THREAD

**Issue by talysl** [johntitus/node-horseman#186]
Hello,

I want to open a new window in horseman clicking on an element like the one below:
`<tr id="g_1_SIpk7Xwo" class="tr-first stage-live" style="cursor: pointer;">`
But I cannot use the "id" as a selector because it changes according to a specific item. So, is there any other way to click on an item to open the page inside the element?
I am sorry if this question is too general, but I am struggling with this last piece of my code and it seems to be something simple to solve!
Thanks in advance.

**Comment by awlayton** [comment]
You just need the right selector. If you always want the first row, perhaps something like `'tr.tr-first'` will be involved?

The exact answer depends on what is on the page. You should just google around for doing thing with selectors (either plain CSS or jQuery ones).
