### ISSUE TITLE
async evaluation doesn't work on windows 10.

### ISSUE THREAD

**Issue by alexey-sh** [johntitus/node-horseman#189]
Hi, I tried to execute this code
```javascript
horseman
  .open('http://en.wikipedia.org/wiki/Headless_Horseman')
  .evaluate(function(ms, done){
    var start = Date.now();
    setTimeout(function() {
      done(null, Date.now() - start);
      // ^ Can pass an Error as first argument,
      // making evaluate action reject its Promise in Node.
      // Second argument is what the Promise will resolve to.
    }, ms);
  }, 100)
  .then(function(actualMs){
    console.log(actualMs);
  })
  .close();
```

in console I see `null`. same for example with bluebirdjs.

phantomjs version is 2.1.7, 
node-horseman version is 2.8.2, 
node version is 5.10.1. 
**OS is windows 10 pro x86 32-bit.** (virtual machine)
I've tried this example on OS X and it **works**.

How I can use async evaluate on windows 10? 

Thanks!

**Comment by awlayton** [comment]
Support for async in `.evaluate()` was added in horseman ***3***. You must *not* have been using horseman 2.8.2 when you tried it in OSX.
