### ISSUE TITLE
执行实例代码报错

### ISSUE THREAD

**Issue by qinmudi** [johntitus/node-horseman#19]
1、执行示例代码报错，请问大概是什么原因?
Error: spawn ENOENT

npm install node-horseman
2、安装模块报错
npm WARN package.json horseman@1.0.0 No description
npm WARN package.json horseman@1.0.0 No repository field.
npm WARN package.json horseman@1.0.0 No README data
\
> deasync@0.0.10 install /Users/qinmudi/ericqin/test/horseman/node_modules/node-horseman/node_modules/deasync
> node ./build.js

`darwin-x64-node-0.10` exists; testing
Binary is fine; exiting
node-horseman@1.4.1 node_modules/node-horseman
├── defaults@1.0.0
├── clone@0.1.19
├── node-phantom-simple@1.2.0
├── debug@2.1.2 (ms@0.7.0)
└── deasync@0.0.10 (bindings@1.1.1, nan@1.7.0)

**Comment by johntitus** [comment]
@qinmudi, It looks like an error installing `deasync`. 
https://github.com/abbr/deasync#installation

Please check out those installation instructions.
