### ISSUE TITLE
Can't close horseman instance from extension handlers

### ISSUE THREAD

**Issue by alecarg** [johntitus/node-horseman#196]
I might be implementing this the wrong way, but here goes one or two cases that fail for me that I would expect them to work:

```javascript
Horseman.registerAction('evaluateAndCatch', function(fn) {
  var self = this;
  return this
  	.evaluate(fn)
	.catch(function(err){
		return self.close(); // this does not close the instance
	});
});
```

--------

```javascript
Horseman.registerAction('start', function() {
  var self = this;
  return this
	.on('timeout', function(msg){
		return self.close(); // this does not close the instance
	})
}
```

It feels like I'd need to reject the promise as well as attempting to close(); in both scenarios. Could that be the problem?
Btw, not sure if the following would work (outside extension handlers).

```javascript
horseman
  .on('timeout', function( msg ){
    horseman.close();
  })
```

Any help would be greatly appreciated.

**Comment by awlayton** [comment]
In the first case it will *only* close if the Promise rejects and in the second one it will *only* close if a timeout occurs. I would bet neither of those things are happening, which is why it is not closing.

For you last part, you never *have* to use `.registerAction`, it just lets you name a series of actions and use that name to call them later.

**Comment by alecarg** [comment]
@awlayton , thanks.

I can confirm both statements were indeed running (both the .close() ones), but the instances were not getting closed and the rest of the chain was executing instead up until the last .close()

Also, thanks for your tip about .registerAction. I am actually packing a lot of actions together when using it, hence why I need to close the instance from inside it. That's the reason why I mentioned the third example, which might or might not work while being the same as the second one, but isn't something I'd be willing to do as that would create a lot of code duplication on my tests.

Thanks again.

**Comment by awlayton** [comment]
1 How did you determine the instances were not closing?
2. The chain does not stop at a close
```javascript
  horseman.open(URL)
    .close() // Does NOT stop chain
    .status() // Will STILL run
```

**Comment by alecarg** [comment]
@awlayton , thanks.

I was console logging from inside the onTimeout and catch handlers, but it would seem like (2) might answer (1) then: I was expecting close() to stop the chain.

What would be the correct way to stop the chain then?

**Comment by awlayton** [comment]
The chain of actions is in fact a Promise chain. So you can do whatever Promise stuff you can think of.

For example, you `evaluateAndCatch` action is probably a bad idea. You should do something like
```javascript
horseman.evaluatae(fn)
  /* Chain stuff here */
  .catch(function() {
    return this.close();
  })
```
When anything in the chain rejects, the actions will be skipped (horseman actions are *resolution* handlers, not *rejection* handlers) until the next catch is reached.

For chaining questions, you should look into dealing with Promises in general, not horseman specifically.

**Comment by awlayton** [comment]
Also, `.close()` is actually a special action (it runs on resolution or rejection), so you should almost always just stick it at the end of the chain.
```javascript
horseman.open(url)
  .click('sadadasdadasd') // Click that won't work
  .close() // Instance will STILL be closed
```

**Comment by alecarg** [comment]
Hey @awlayton , thanks for all the feedback!

Just wondered why you thought evaluateAndCatch was a bad idea. It would seem like the example you gave me was exactly the same as the one I posted, except yours wasn't inside a .registerAction

I do have ```.close()``` at the end of every chain. As you pointed out, chains are promises, so I do remember trying something like the following at some point before creating this issue. I've retried this and it still gave me an error:

```javascript
Horseman.registerAction('start', function() {
  var self = this;
  return this
        .on('error', function(msg, trace){
		return self.reject("error reject2").then(null, function(rejectionReason) {
		  console.log(rejectionReason);
		});
	})
```
I was also chaining ```.close()``` in there before reject but stripped it out so as to not complicate things.

I'm sorry if this is something basic related to Promises I'm missing, while I have read a bit on the topic, I'm mainly learning them as I go.

**Comment by awlayton** [comment]
I was saying `evaluateAndCatch` might be a bad idea because you usually want things *between* the evaluate and the catch (so that those thing will me skipped if the evaluate rejects).

What error are you getting from the above example? Also FYI, the `.on()` and `.at()` actions register event handlers, they are not like a `.then` so you cannot return a Promise in the handler of them and have it do what you want (it won't be a part of the outer Promise chain).
