### ISSUE TITLE
.evaluate async/promise/callback?

### ISSUE THREAD

**Issue by tylercb** [johntitus/node-horseman#197]
It's been a long day and it's late and I need a little help... I know I'm missing the promise/callback/async part of the .evaluate() call on this example. At the end of the day, I want to remove all the HTML that is :hidden and only keep the visible elements. But I keep getting inconsistent results because I haven't implemented the promises or callbacks correctly. Any advice or comments are greatly appreciated.

```javascript
horseman
        .viewport(1920,1080)
        .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
        .open('http://v4-alpha.getbootstrap.com/layout/responsive-utilities/')
        .evaluate(function(done){
          $('body :hidden').remove(); // derrrrr
          done(null, $('html')[0].outerHTML); // uhhhhhh
        })
        .then(function(html) {
          console.log(html);
        })
        .close();
```

The expected output is all script and non visible HTML elements are removed.

**Comment by awlayton** [comment]
What versions of horseman PhantomJS etc.?

**Comment by tylercb** [comment]
"node-horseman": "^3.0.1",

$ phantomjs -v
2.1.1

**Comment by tylercb** [comment]
I ended up using phantom instead.

var phantom = require('phantom');
phantom.create().then(function (ph) {
          ph.createPage().then(function (page) {
              page.setting('userAgent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0');
              page.property('viewportSize', {width: 1920, height: 1080});
              page.open('http://v4-alpha.getbootstrap.com/layout/responsive-utilities/').then(function () {
                  page.includeJs("https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js").then(function() {
                      page.evaluate(function() {
                          $('body :hidden').remove();
                          return document.documentElement.outerHTML;
                      }).then(function(html){
                          console.log(html);
                          page.close();
                          ph.exit();
                      });
                  });
              });
          });
      });
