### ISSUE TITLE
npm untar error for v. 3.1.0

### ISSUE THREAD

**Issue by zatziky** [johntitus/node-horseman#198]
Hello,

on Windows when trying to install this lib using the command `npm i node-horseman@3.1.0 --save`
I receive this error:

>  
> npm ERR! tar.unpack untar error AppData\Roaming\npm-cache\node-horseman\3.1.0\package.tgz
> tripito-tools@1.0.0 tools
> `-- phantom@2.1.5  invalid
> 
> npm WARN tripito-tools@1.0.0 No description
> npm WARN tripito-tools@1.0.0 No repository field.
> npm WARN tripito-tools@1.0.0 No license field.
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "nodejs\\node.exe" "nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-horseman@3.1.0" "--save"
> npm ERR! node v6.2.1
> npm ERR! npm  v3.9.3
> npm ERR! path tools\node_modules\.staging\node-horseman-6af918ed
> npm ERR! code EEXIST
> npm ERR! errno -4075
> npm ERR! syscall mkdir
> 
> npm ERR! EEXIST: file already exists, mkdir 'tools\node_modules\.staging\node-horseman-6af918ed'
> npm ERR! File exists: tools\node_modules\.staging\node-horseman-6af918ed
> npm ERR! Move it away, and try again.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     tools\npm-debug.log
> 

The contents of **npm-debug.log** have nothing more in it. There is no **.staging** folder.

All other versions of 3.x.x  are working fine.

**Comment by awlayton** [comment]
Looks like I accidentally published some files that are not part of horseman and they confuse Windows. Version 3.1.1 should work.
