### ISSUE TITLE
I  want to remove some html tag  when I opening url

### ISSUE THREAD

**Issue by aby913** [johntitus/node-horseman#200]
i don't know how to  do it .
I open some url ,but  some  javascript file received  timeout .
have a solution for remove these script tags  when I open one url?

**Comment by awlayton** [comment]
Could you maybe try to state your problem again more clearly and precisely? To remove a tag you'll probably just have to manipulate the DOM with javascript in the `.evaluate()` action.

**Comment by aby913** [comment]
my code is like this:
 .waitFor(function waitForSelectorCount(selector, count) {
	    return $(selector).length >= count
	}, "some html tag", 1, true)

and then  , get a error:
Unhandled rejection TimeoutError: timeout during .waitFor() after 15029 ms
    at Timeout.waitForCheck (/web/digger/api/node_modules/node-horseman/lib/actions.js:1643:13)
    at Timeout.wrapper (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

**Comment by aby913** [comment]
It's my fault!
i reviewed the url html, i found  the  tag is changed, so my waitFor selector is wrong.
i fixed it   it's run ok!
thank u~

**Comment by awlayton** [comment]
Glad it works for you @aby913.
