### ISSUE TITLE
Horseman does not start on heroku

### ISSUE THREAD

**Issue by lightsprint09** [johntitus/node-horseman#21]
I am trying to start a horseman instance on heroku. 
Example:
```var phantomjs = require("phantomjs");
var Horseman = require("node-horseman");
var config = {phantomPath:phantomjs.path};
new Horseman(config)```

Debug Output: ```Sat, 28 Mar 2015 18:06:49 GMT horseman .setup() creating phantom instance on```

nom Error :``` npm ERR! code ELIFECYCLE```

**Comment by johntitus** [comment]
Can you give an example of how you installed phantomjs on heroku?

**Comment by lightsprint09** [comment]
I use the npm version ```phantomjs```

**Comment by lightsprint09** [comment]
I do no setup on phantomjs od heroku

**Comment by puzrin** [comment]
I guess, your instance on heroku does not have netstat, used by node-phantom-simple. See https://github.com/baudehlo/node-phantom-simple/pull/46.

Version 2.0.0 of driver try `ss` first. That may help. Can you check if `ss` is available? Or can you install net-tools / iproute2 package on your instanse?

**Comment by johntitus** [comment]
May want to try this now, as I just upgraded to node-phantom-simple 2.0.2.

**Comment by johntitus** [comment]
Closing. Please reopen if this is an issue in v2.
