### ISSUE TITLE
Not load static files

### ISSUE THREAD

**Issue by colutti** [johntitus/node-horseman#210]
Is it possible to configure horseman to not load static files, such as images and css? I would like to speed up the test execution by not loading any static file that is not necessary for the test to run.

**Comment by awlayton** [comment]
Read the Readme. It says how to not load images. I do not know of a way to
stop phantom loading CSS.

**Comment by awlayton** [comment]
See [here](https://github.com/ariya/phantomjs/blob/master/examples/loadurlwithoutcss.js) for example of using `onResourceRequested` to stop CSS loading.
