### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by chovy** [johntitus/node-horseman#213]
Can node horseman run ok if I fire off a bunch of async requests simultaneously that will each open an instance to crawl a url?

Also. Does node horseman crawl single page apps without issue? i.e.: angular react or vuejs?

**Comment by chovy** [comment]
I'm wondering in a server with 16gb ram and quad core processor if I'll be able to spin up dozens of instances or hundreds. Any ideas? I'm just looking for a ballpark estimate of to how much parallel processing I can do.

**Comment by johntitus** [comment]
Sorry, no clue. If you find out, please let us know!

**Comment by awlayton** [comment]
Closing for now. Feel free to update this if you find out.
