### ISSUE TITLE
Promises not working

### ISSUE THREAD

**Issue by agustinkassis** [johntitus/node-horseman#214]
It looks like chaining doesn't create new promises

```javascript
horseman
  .open('someUrl')
  .waitForNextPage()
  .then(resolveFn, rejectFn); // Rejects on timeout

function resolveFn() {
  console.log('congrats');
}

function rejectFn() {
  horseman
    .reload()
    .waitForNextPage() // Should wait for the reload
    .then(function () {
      console.log('This time the reload works!');
    }, function () {
      // It takes the first promise, so its already rejected
      console.log('Rejects the promise immediately');
    })
}
```

**Comment by awlayton** [comment]
Could you please *state* what is *supposedly* wrong? I do not understand what you want me to see from this code snippet.

**Comment by dominictracey** [comment]
It makes no sense.

**Comment by awlayton** [comment]
*What* makes no sense?

**Comment by dominictracey** [comment]
The provided code snippet isn't proper use of promises. Thanks for your work on node-horseman, btw.

**Comment by sebringj** [comment]
The code on version 2.8.2 was previously working when chaining the "evaluate" method in my code. I upgraded to 3.1.1 on another project and the same code did not work. I was able to verify this by downgrading on the new project and could see it work. Here's the snippet in question that only returns the last promise chained in a Promise.all:

    'use strict';

    function parse(horseman) {
  
      return Promise.all([
        horseman.evaluate(require('./metas')),
        horseman.evaluate(require('./texts')),
        horseman.evaluate(require('./images')),
        horseman.evaluate(require('./embeds'))
      ]);
    }

    module.exports = parse;

Thanks @awlayton

**Comment by awlayton** [comment]
What you're doing is probably a bad idea because of how horseman works @sebringj. You should do the `.evaluate()`s sequentially.

Horseman wants to have one chain of actions. I can agree it would be nice if it worked like you want, but I think you just got lucky with version 2.3.2 and I advise against doing that for stability reasons.

```javascript
'use strict';

function parse(horseman) {

  return horseman
    .evaluate(require('./metas'))
    .evaluate(require('./texts'))
    .evaluate(require('./images'))
    .evaluate(require('./embeds'));
}

module.exports = parse;
```

**Comment by awlayton** [comment]
Closing because original issue is not clear and there have been no updates for some time.
