### ISSUE TITLE
Click on Twitter Follow button not working

### ISSUE THREAD

**Issue by nvarcha** [johntitus/node-horseman#215]
Hi,

I've managed to work with horseman and click on everything except Twitter's main follow button.

The selector is found correctly and only one is counted on the page and its visible. I've tried many, but this finds it perfectly: '.user-actions-follow-button'. I made screenshot() and crop() to check and everything looks ok.

```javascript
var clickSelector = '.user-actions-follow-button';
phantomInstance
	.open('https://twitter.com/github')
	.count(clickSelector).log() // prints 1
	.visible(clickSelector).log() //  prints true
	.click(clickSelector)
	.close()
```

I've also tried this, to no avail:

```javascript
        phantomInstance
            .open('https://twitter.com/github')
            .count(clickSelector).log()
            .visible(clickSelector).log()
            .evaluate(function (clickSelector) {
                return $(clickSelector).offset();
            }, clickSelector)
            .then (function (offset) {
                console.log('offset', offset);
                phantomInstance
                    .mouseEvent('click', offset.left + 40, offset.top + 40);
            })
            .close();
```

And this:

```javascript
        phantomInstance
            .open('https://twitter.com/' + username)
            .count(clickSelector).log()
            .visible(clickSelector).log()
            .evaluate(function (clickSelector) {
                $(clickSelector).trigger('click');
                return $(clickSelector).offset();
            }, clickSelector)
            .close();
```

I've tried everything and I can't find it to work.

Not sure if this is an issue or I'm doing something wrong.

Thanks!

**Comment by awlayton** [comment]
Two things:

1. Why are you adding 40 to the offset when using `.mouseEvent()`?
1. Try spoofing your userAgent. Sites can send completely different HTML based on the userAgent. So looking at the HTML in your browser to figure out what to do with PhantomJS is not always a good idea.

**Comment by nvarcha** [comment]
Thanks for the reply.

1. I tried that to ensure the click was happening inside the button and not on the rim, but I tried both
2. I just tried a few user agents and didn't work (used http://www.whoishostingthis.com/tools/user-agent/ to get it) and tried with Firefox and Chrome. I.e. (I'm setting userAgent right after creating the phantomInstance and before any open() commands):
```
phantomInstance.userAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0');
```

Any other ideas of what might be happening?

Thanks!

**Comment by awlayton** [comment]
Did you try writing out the HTML that phantom has and making sure the button is the same as you think?

**Comment by nvarcha** [comment]
I did. The button is there. The selector is the same. I can find it with Firebug for instance on the generated HTML.

But still no click. Very odd.

**Comment by nvarcha** [comment]
Also, I can click on any other element such as the Mute button, block, report, etc. 

It's just the follow button not working.

**Comment by awlayton** [comment]
Could you run it with `DEBUG='horseman*'` set and post the output @nvarcha? Feel free to X out any usernames, passwords, etc.

**Comment by nvarcha** [comment]
Sure. Here it is.

  horseman using PhantomJS from phantomjs module +0ms
  horseman .setup() creating phantom instance 1 +3ms
  horseman phantom created +2s
  horseman phantom version 1.9.8 +13ms
  horseman page created +8ms
  horseman phantomjs onLoadFinished triggered +11ms success NaN
  horseman injected jQuery +24ms
  horseman .open() +7ms https://twitter.com/login
  horseman phantomjs onLoadFinished triggered +4s success 1
  horseman .userAgent() set +1ms Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0
  horseman jQuery not injected - already exists on page +8ms
  horseman .screenshot() +4ms t_1.png
  horseman .count() +540ms #page-container > div.dashboard.dashboard-left > div.DashboardProfileCard.module > div > div.DashboardProfileCard-userFields > span
  horseman .open() +346ms https://twitter.com/github
  horseman phantomjs onLoadFinished triggered +1s success 2
  horseman jQuery not injected - already exists on page +11ms
  horseman .screenshot() +6ms t_3.png
  horseman .count() +1s .user-actions-follow-button
  horseman .visible() +6ms .user-actions-follow-button
  horseman .click() +5ms .user-actions-follow-button
  horseman .click() done +8ms

**Comment by nvarcha** [comment]
Another strange thing. Running this code in the console in Firefox with Firebug clicks the button correctly:
$('.follow-button').click()

But doing this on Horseman doesn't work either:

```
        phantomInstance
            .open('https://twitter.com/github')
            .evaluate (function () {
                $('.follow-button').click();
            })
```

**Comment by johntitus** [comment]
When I run the code below, it seems to click the button fine. The first screenshot is the generic twitter page for the github user. The second screenshot is a dialog asking for me to login.

```js
horseman
    .open('https://twitter.com/github')
    .screenshot('twitter1.png')
    .click('.follow-button')
    .wait(1000)
    .screenshot('twitter2.png')
    .close();
```

**Comment by nvarcha** [comment]
@johntitus Yes, but if you are already logged in, then it does not actually do the Follow.

I've tried also changing the .viewport() but no luck.

On a forum for CasperJS it was mentioned the issue was the element was not visible hence not interactable, but as I check with .visible() that should not be the case here.

This is what I use to log in:
```
            horseman
                .open('https://twitter.com/login')
                .type(inputName, 'email')
                .type(inputPass, 'pass')
                .click(submitBut)
                .waitForNextPage()
```

And after that, if I run your code immediately after (or a few other methods), it doesn't work. 

I'm going to try a few things to see if I can narrow it down better.

**Comment by johntitus** [comment]
How do you know it's not working? Taking a screenshot before/after?

**Comment by nvarcha** [comment]
Yes, I took screenshot and also I can check because when I'm logged in, after doing that, I'm not Following that user.

**Comment by nvarcha** [comment]
It seems Twitter, when the Following button is clicked, it performs a POST like so:

https://twitter.com/i/user/follow?authenticity_token=XXXXXXX&challenges_passed=false&handles_challenges=1&impression_id=&user_id=XXXXXXXXX

Would Horseman/Phantom have an issue with the navigated page doing that?

**Comment by awlayton** [comment]
No horseman should be fine with xhr requests and stuff. When I open the page in horseman with `DEBUG='horseman*'`, I get the following error.

```
 horseman:verbose onError +0ms TypeError: 'undefined' is not an object (evaluating 'perf.timing.navigationStart')
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 630 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 663 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 663 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 1183 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 1183 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 513 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 513 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 517 in <anonymous>
	phantomjs://webpage.evaluate(): 4 in <anonymous>
	: 1 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 113 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 104 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 517 in j
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 1189 in <anonymous>
	https://abs.twimg.com/c/swift/en/bundle/boot.e6b077f5de86684fadd7deecc5f5822584c96171.js: 811 in <anonymous>
	https://abs.twimg.com/c/swift/en/bundle/profile.fe8d5a4c426f6730760869928f91befb67cb0fa9.js: 146 in <anonymous>
	https://abs.twimg.com/c/swift/en/bundle/profile.fe8d5a4c426f6730760869928f91befb67cb0fa9.js: 191 in <anonymous>
	https://abs.twimg.com/c/swift/en/init.13fa90c646bf288e4242420ae5b6f0847cdf0a0a.js: 508 in <anonymous> 1
```

I believe what is happen is the `.click()` is working just fine, but the JavaScript triggered by the button is breaking in PhantomJS due to missing features.

**Comment by nvarcha** [comment]
Oh, I see. I guess I'll jump to Phantom's issues then, as it's not a Horseman issue.

Thanks a lot for checking, though!
