### ISSUE TITLE
jquery selectors with react

### ISSUE THREAD

**Issue by phatcatmatt** [johntitus/node-horseman#216]
I'm trying to navigate a page using jquery selectors. The page is built in react. Node-horeseman is telling me the elements don't exist (with .exists()). I've been successful with other non-react pages. What am I doing wrong?

**Comment by awlayton** [comment]
Perhaps React is not done rendering the DOM. Try putting a `.wait()` after your `.open()`.

**Comment by phatcatmatt** [comment]
I did try that but it didn't work. I can take a screenshot of the loaded page that shows everything is rendered, but I still can't select elements. 



On September 6, 2016 at 6:36:36 AM MDT, Alex Layton <notifications@github.com> wrote:Perhaps React is not done rendering the DOM. Try putting a .wait()  after your .open() .  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/johntitus/node-horseman","title":"johntitus/node-horseman","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/johntitus/node-horseman"}},"updates":{"snippets":[{"icon":"PERSON","message":"@awlayton in #216: Perhaps React is not done rendering the DOM. Try putting a `.wait()` after your `.open()`."}],"action":{"name":"View Issue","url":"https://github.com/johntitus/node-horseman/issues/216#issuecomment-244936646"}}}

**Comment by johntitus** [comment]
Can you spit out the .html() of the page, to verify the selectors are
present?  Also, that it's not within an iframe...

**Comment by phatcatmatt** [comment]
As far as I can tell the selectors are present and it's not an iframe. For reference I am crawling a local classified website (http://www.ksl.com/homes/index/rentler). I've been successful with craigslist, but I can't get this site to work. Not sure if I'm just an idiot or if it's something to do with react. Thanks for the help.

**Comment by jkarttunen** [comment]
I'm having similar issues with non-react page.

**Comment by johntitus** [comment]
It would be helpful if someone could provide a working test case.

**Comment by jkarttunen** [comment]
Turns out my case was selector returning multiple results.

**Comment by wong2** [comment]
have you tried `waitForSelector`?

**Comment by tobiaslins** [comment]
I got the same issue on [Sofort.com](https://www.sofort.com/)
`Mon, 20 Mar 2017 08:49:15 GMT horseman phantomjs onLoadFinished triggered success 4
Mon, 20 Mar 2017 08:49:15 GMT horseman .waitForNextPage() completed successfully
Mon, 20 Mar 2017 08:49:15 GMT horseman .type() input[id="#MultipaysSessionSenderBankCode"] 00000 undefined
Mon, 20 Mar 2017 08:49:15 GMT horseman jQuery not injected - already exists on page`

**Comment by awlayton** [comment]
Are you saying the script crashes when you use `.html()` @tobiaslins? It seems like you are having a *different* but perhaps similar issue.

Please post your code and *all* of the log output (none of the useful bits are in what you posted).
