### ISSUE TITLE
.evaluate returning undefined

### ISSUE THREAD

**Issue by luislaborda** [johntitus/node-horseman#217]
It have been for a couple days now, and long long long hours trying to get results back when calling .evaluate. No matter what I try, I get stock here. Using version 3.1.1 I use the following:

```javascript
horseman.evaluate(function(selector){
  return ($(selector).text());
},'tr[role="row"]')
.then(function(results){
  console.log(results);
});
```
In the above example, I never get to see the console log. What am I missing? 
Is it because the script still running in the background? If so, how do I wait until ready?

**Comment by johntitus** [comment]
The below code works, which makes me think your issue may be specific to the page you're working with. Can you provide a full test case?

```js
horseman
    .open('http://www.google.com')
    .evaluate(function(selector){
        return ($(selector).text());
    },'a')
    .then(function(results){
      console.log(results);
    })
    .close();
```

**Comment by luislaborda** [comment]
I believe I found why it wasn't working. It all depends on the method **prior** evaluate. If you have a method that returns html, then the method works, but if you have a method that does not return html, then evaluate fails. 

Your example above works because .open() somehow returns html, but if **between** .open() and .evaluate() you place a .wait() or something that does not return any html, then console.log will never get invoke. Dose it makes sense? Have you test this use case? 

Please note that I don't know the ins-out of horsemanjs. All I know that in my case, as soon I placed the method .html() before evaluate, then my promise worked and I was able to get the results.

**Comment by johntitus** [comment]
Adding a `wait(100)` to my example after the `.open` still works.
Perhaps adding the .html() to your example causes enough of a delay that the page finishes rendering?

**Comment by awlayton** [comment]
Since there has been no response, I am assuming @johntitus was right about the real issue.
