### ISSUE TITLE
Beginner recursion question - why does this behave this way?

### ISSUE THREAD

**Issue by zerotocoder** [johntitus/node-horseman#218]
//When written like this, the function allows you to calculate a power function.

function power(base, exponent) {
  if (exponent == 0)
    return 1;
  else
    return base * power(base, exponent-1);
}

console.log(power(3, 3));
//27

//When written like this, the maximum call stack is exceeded

function power(base, exponent) {
  if (exponent == 0)
    return 1;
  else
    return base * power(base, exponent);
}

console.log(power(3, 3));
//RangeError: Maximum call stack size exceeded 

Can someone break down the line by line of what's going on here?

**Comment by johntitus** [comment]
This doesn't seem to have anything to do with node-horseman.
