### ISSUE TITLE
get data successively from .text()

### ISSUE THREAD

**Issue by garysou** [johntitus/node-horseman#219]
Hello everybody, i'm a new node-horseman user and i have a little issue since 2 or 3 days. 
Im trying to get all the text from the same .class on a page with the following code: 

```javascript
horseman
    .open('path_url')
    .text('.cl_name1 .cl_name2')
    .then(function (text){
        console.log(text)
    })
   .close();
```
where the html of path_url is like: 
```html
<div class='cl_name1>
    <p class='cl_name2'> data_text1 </p>
    <p class='cl_name2'> data_text2 </p>
```
but the problem is that the console give me all the text in a row: 
```bash
data_text1data_text2
```
Can you enlighten me about a fashion to get this data separately ?

**Comment by awlayton** [comment]
You need to call `.text()` separately for each thing you want  the text of.

**Comment by garysou** [comment]
If I have 1K of data it will be very difficult. At the beginning I thought that the data requested by text() (or evaluate() ) triggered the event 'ressourceReceived' and I got this data successively, but in fact not. There is no event triggered when the horseman get data ?

**Comment by johntitus** [comment]
is the text being returned an array? Try changing it to
console.log(text.join(','));

**Comment by awlayton** [comment]
Horseman doesn't get data. Those events are about Phantom receiving resources (where a resource is something like a picture or a CSS file). Horseman is mostly about Promises, though there are a couple horseman events still hanging around.

**Comment by garysou** [comment]
@johntitus 
No this is the problem, this return error `undefined is not a function`: 
```javascript 
text.forEach( function (txt){ 
    console.log(txt)
```
@awlayton 
So if i follow you, horseman goal is to write PhantomJs for node in an asynchronous fashion and getting data in a proper way is not ?

**Comment by awlayton** [comment]
Your error is because `.forEach` is not defined. Are you trying to run that in an evaluate, because Phantom is missing most of the fancy things like `.forEach`?

Horseman is just a wrapper around PhantomJS, we didn't write or rewrite any of the Phantom code. Horseman aims to abstract away the Phantom stuff for common use cases, but sometimes you still need to understand how Phantom works.

**Comment by garysou** [comment]
@awlayton 
I want to precise that im also new to have javascript programming. I understand that node is js at server side, PhantomJs emulate the browser and node-horseman clone Phantom in node. If  my problem come from a lack of Phantom or Js, do you have any specific reference under your end around this problem ?

**Comment by garysou** [comment]
@awlayton 
I just see your last answer. I understand better horseman. Thanks for your time to answer; i ll make a round on Phantom  ..
