### ISSUE TITLE
Travis-CI Compatibility

### ISSUE THREAD

**Issue by ben-z** [johntitus/node-horseman#22]
Hello, 

First of all, thank you for the great work!

I was trying to run `node-horseman` with mocha on [**travis**](travis-ci.com) but it failed with:

```
> node test/horseman.js

undefined
npm ERR! Test failed.  See above for more details.
```

The script is almost exactly the same as the example:

```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman();

var numLinks = horseman
  .open('http://www.google.com')
  .type('input[name="q"]', 'github')
  .click("button:contains('Search')")
  .waitForNextPage()
  .title();

console.log("Title: " + numLinks);

horseman.close();
```

Please let me know if this is a known issue or if I have missed anything.

Thanks,

Ben

**Comment by johntitus** [comment]
To run the test, you do `npm test`.  The script you wrote seems to work fine for me. Are you still having an issue?

https://github.com/johntitus/node-horseman#tests

**Comment by johntitus** [comment]
Closing due to lack of info.
