### ISSUE TITLE
Passing horseman object across functions

### ISSUE THREAD

**Issue by mamigot** [johntitus/node-horseman#224]
I have a relatively complex initialization process for horseman through which, before scraping the website or making calls to its API, I have to set a specific user agent, login credentials, etc. I'm taking care of this in one function, which should return horseman objects that are ready to go after performing these steps.

However, when I try to use the horseman instance in another function, I get this error:
`Unhandled rejection HeadlessError: Phantom Process died` ... as if I had called the `.close()` function on horseman before returning from `launchHorseman(...)`.

```javascript
function launchHorseman(rootUrl, email, password) {
  return new Horseman()
    .asLaptop() // custom action
    .login(rootUrl, email, password) // custom action
}

function getBlocks(apiUrl, rootUrl, email, password) {
   launchHorseman() // none of the following works, as if .close() had just been called!
    .headers({'Accept':'application/json'})
    .open(apiUrl)
    .plainText()
    .then(function(blocks){
      console.log(blocks);
    })
    .close()
}
```

Of course, if I make the API call in the same function as the one in which I launch the horseman instance, everything works.

Is there a way to prevent this "`.close()`" behavior from happening, thereby being able to use the same horseman object across functions?

Thank you!

**Comment by awlayton** [comment]
What you are trying to do should work @mamigot. There is not implicit `.close()` that should be happening. Perhaps there is a bug in one of your custom actions you call in your initialization function?

**Comment by mamigot** [comment]
Thank you, @awlayton . This is the custom action I had defined:

```javascript
Horseman.registerAction('login', function(rootUrl, email, password) {
  return this
    .open(rootUrl + '/login')
    .type('#login-email', email)
    .type('#login-password', password)
    .click('#login > button')
    .waitForNextPage()
});
```

This was giving an error because of `.waitForNextPage()` apparently. I modified the action to not end with it (even `.wait(4000)` worked) and now it's fine:

```javascript
Horseman.registerAction('login', function(rootUrl, email, password) {
  return this
    .open(rootUrl + '/login')
    .type('#login-email', email)
    .type('#login-password', password)
    .click('#login > button')
    .waitForNextPage()
    .waitForSelector('body')
});
```

Thanks, sir!

**Comment by awlayton** [comment]
Interesting. I am not sure why the first version has a problem...
