### ISSUE TITLE
Cannot open any more than 4 simultaneous instances.

### ISSUE THREAD

**Issue by dynamite-ready** [johntitus/node-horseman#228]
I'm on OSX, using Node JS ver 4.6.1, and Horseman ver 3.2.0 and am running code like this:

```
function screenShot(url)
    var horseman = new Horseman();
    
    horseman.
        open(url).
        screenshotBase64('PNG').
        then((content) => {
            var buf = new Buffer(content, 'base64');
        }).
        close().
        catch(error => {
            console.log(error);
        });
}    

for(let i =0; i < 9; i++) screenshot(`http://myurl/${i}`);
```

In doing this, I expect to have created 9 Phantom instances, but for some reason, only 4 are ever created, as evidenced here in this debug log:

```
  horseman using PhantomJS from phantomjs-prebuilt module +0ms
Server running at: http://127.0.0.1:5678
  horseman .setup() creating phantom instance 1 +8s
  horseman .setup() creating phantom instance 2 +10ms
  horseman .setup() creating phantom instance 3 +4ms
  horseman .setup() creating phantom instance 4 +3ms
  horseman phantom created +1s
  horseman phantom created +4ms
  horseman phantom created +2ms
  horseman phantom version 2.1.1 +9ms
  horseman phantom version 2.1.1 +7ms
  horseman phantom version 2.1.1 +1ms
  horseman phantom created +2ms
  horseman page created +7ms
  horseman phantom version 2.1.1 +10ms
```

What am I missing? Is this a bug in Horseman, Node-Phantom-Simple, or Phantom itself?

**Comment by wong2** [comment]
I tried your code, it works correctly for me, creating 9 phantom instances.

**Comment by wong2** [comment]
if you run it several times, are you always get `4` instances? (I mean instead of 3, 5, ...)

**Comment by dynamite-ready** [comment]
To be honest, after debugging the application, the issue appears to be tied to a problem with Redis.
Basically, when Redis can't store an item, we don't run the Phantom. 

You can ignore this.

Thank you for your help.

**Comment by wong2** [comment]
haha alright
