### ISSUE TITLE
kreypress not working properly

### ISSUE THREAD

**Issue by Raidus** [johntitus/node-horseman#229]
Hey there!

I'm trying to collect some keywords from the amazon autocompletion. Unfortunately the keypress event is not working properly. 

In this example, the script should log the third auto suggestion by amazon. Instead it's logging 'a'. 

Any ideas to fix this?

```javascript
'use strict';

var Horseman = require('node-horseman');
var horseman = new Horseman();

horseman
  .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
  .open('https://www.amazon.de/')
  .type('#twotabsearchtextbox', 'a')
  .keyboardEvent('keypress', 16777237)
  .keyboardEvent('keypress', 16777237)
  .keyboardEvent('keypress', 16777237)
  .evaluate(function () {
    return document.querySelector('#twotabsearchtextbox').value
  })
  .log() // prints out the third suggestion
  .close();
```

**Comment by awlayton** [comment]
It seems that the actual problem is Amazon's auto-completion does not work in PhantomJS. This image is what I get when I add a `.screenshot()` to the end of your example.

![2](https://cloud.githubusercontent.com/assets/4231765/19710495/b8440506-9afc-11e6-90d9-2b51b5edefda.png)

**Comment by robertpallas** [comment]
horseman
		.userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
		.open('https://www.amazon.de/')
		.waitForSelector('.nav-signin-tooltip-footer')
		.click('#twotabsearchtextbox')
		.wait(1500)
		.type('#twotabsearchtextbox', 'a')
		.wait(1500)
		.keyboardEvent('keypress', 16777237)
		.keyboardEvent('keypress', 16777237)
		.keyboardEvent('keypress', 16777237)
		.value('#twotabsearchtextbox')
		.log() // prints out the third suggestion
		.close()

@Raidus - if the timing is important you want to tune the wait to wait for the elements to change their state so that the autocomplete works. [.waitFor(fn)](https://github.com/johntitus/node-horseman#waitforfn-arg1-arg2-value) is good in this case.

**Comment by Raidus** [comment]
Wow, thanks for the quick respond and the working solution!

**Comment by nageshdudam** [comment]
Hello robertpallas & awlayton
I am facing problem with keyboard events.
My requirement is same like "Raidus" - there is one textbox on the website - and on key down - it sends Ajax request to their server and then brings the options
then I need to select the 2nd option and proceed.

My main problem is - I am not getting the options or may be key press - down key is not working.

Please let me know your views.

Awaiting for your assistance.

Thank you.
