### ISSUE TITLE
Clicking between frames.

### ISSUE THREAD

**Issue by C0n3** [johntitus/node-horseman#233]
Hi!

I'm having some problems with the click function.

What I'm doing?

1 -> I go to some page.
2 -> In that page, I go to the first frame.
3 -> Click in one button on that frame.
4 -> I go back to the main frame.
6 -> Now I go to the second frame.
5 -> And then I try to click in some button, but nothing happens.

I do not receive any error from Horseman and in debug mode everything looks good.

Code:

``` javascript
var Horseman = require('node-horseman');
var horseman = new Horseman({loadImages:true, timeout: 60000});

horseman
    .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
    .viewport(1024, 768)
    .open('http://example.com')
    .switchToFrame(0)
    .waitForSelector('.checkbox')
    .click('.checkbox')
    .switchToMainFrame()
    .switchToFrame(1)
    .waitForSelector('#button')
    .click('#button')
    .screenshot('screenshot.png')
    .then(() => process.exit());
```

The button works fine when I test him on Chrome.

**Comment by awlayton** [comment]
Could you post a usable example? There are no frames in the page `example.com`.

**Comment by C0n3** [comment]
Sorry guys, this is not a issue.
