### ISSUE TITLE
Proper way of handling horseman.open getting stuck in redirect loop?

### ISSUE THREAD

**Issue by timotgl** [johntitus/node-horseman#236]
I'm using horseman in an integration test where I log into a service, modify a cookie, and as a result expect to get logged out with the next request. The service throws me in a redirect loop in this case, which is a side effect of using an external authentication server.

My problem is that calling `.open()` after modifying the cookie results in `Unhandled rejection Error: Failed to load url`. I'd like to proceed with the promise chain however and just assert that an error happend. Any ideas?

```javascript
tap.test('Modifying a cookie should get me logged out', (test) => {
  horseman = horseman
    .cookies(modifiedCookie)
    .open('...url here...')
    .catch((result) => {
      test.pass()
      test.end()
    })
    .close()
})
```

**Comment by awlayton** [comment]
I am not sure what you are asking. Can't you just do whatever you want in that `.catch` you have?

**Comment by timotgl** [comment]
@awlayton I can, was just wondering if there's a way to supress the exception.

**Comment by awlayton** [comment]
No horseman does not allow disabling rejections. You can, however, [catch only certain rejections](http://bluebirdjs.com/docs/api/catch.html#filtered-catch).

**Comment by timotgl** [comment]
I resorted to using my test framework to just match the exception, which is good enough I guess:
```
    .open('url')
    .catch((exception) => {
      const throwException = () => {
        throw exception
      }
      test.throws(throwException, new Error('Failed to url'), 'expect exception to be thrown')
    })
```

Anyway, thanks for your help!

**Comment by awlayton** [comment]
What framework are you using? Most of the ones I've seen have a way to get at least some Promise support.

**Comment by timotgl** [comment]
@awlayton I was using http://www.node-tap.org/ (which also has some more promise support with https://www.npmjs.com/package/tapromise apparently) but was happy with the solution i posted above.
