### ISSUE TITLE
url not loading in node-horseman

### ISSUE THREAD

**Issue by antonymca** [johntitus/node-horseman#237]
i am trying to access the url via node horseman , sometimes it loads and some times it doesn't, but i am able to access the url from my terminal via curl request.

Node Version :v6.2.0
node horseman :3.2.0

**Comment by awlayton** [comment]
Please supply more information (e.g., PhantomJS verstion, the URL).

**Comment by antonymca** [comment]
The issue was with the site. Now i able to access it. Hence i am closing this issue.
