### ISSUE TITLE
Not an issue, but i dont know where to ask else, sorry

### ISSUE THREAD

**Issue by iceman20k** [johntitus/node-horseman#239]
I am trying to scrape a website with dynamic content with phantomjs and the nice node-horseman. My Problem is that i have absolutely no clue how to return the received html. All your examples are with console.log. What i need is a function that i could call just like http-request:

request(url, function (error, response, html) { ...
I need something similar, lets call it horsemanRequest() ....

What i have so far, but what is not wokring is something like this:

```javascript
function horsemanGet() {
horseman
	.open('http://mysite.org')
	.status()
	    .then(function(status) {
	    	if (Number(status) !== 200) {
	    		return("error");
	    	}
    	})
	.wait(10000)
	.html()
    .then(function(body) {
    	//console.log(body);
    	return body;
    })
    .close();
}
```

Can anyone help me on this or direct me to a howto? Any help is really appreciated!
I am pretty sorry if this is the absolut wrong place to post that.

**Comment by awlayton** [comment]
You can't exactly "*return*" with horseman. It's asynchronous, it uses Promises. You should look into working with Promises.

This function would return a Promise which *resolves* to the HTML of the page.
```javascript
function horsemanGet() {
    return horseman
        .open('http://mysite.org')
        .status()
        .then(function(status) {
            if (Number(status) !== 200) {
                throw new Error('status: ' + status);
            }
    	})
        .wait(10000)
        .html()
        .close();
}
```

**Comment by iceman20k** [comment]
ok, thanks a lot for your response and help!
