### ISSUE TITLE
Using node-horseman in docker/docker-compose

### ISSUE THREAD

**Issue by sp90** [johntitus/node-horseman#241]
Okay so im working on using horseman as a prerender for my angular app.

And i have this docker-compose file:

where i start the prerender script to listen on `localhost:5000`, and then in my docker-compose i have my normal app on `localhost:8000`. 

So im trying to hit my frontend(fe) container by hitting:

`localhost:5000?url=http://fe:8000` because of the dns, that have been setup in docker 

So i want this to hit my frontend container to resolve the page and return it only to bots

```javascript
const path = require('path');
const phantomjs = require('phantomjs-prebuilt');
const Horseman = require('node-horseman');
const horseman = new Horseman({
	ignoreSSLErrors: true,
        sslProtocol: 'any',
        webSecurity: false,
	phantomPath: path.join(__dirname, 'node_modules/phantomjs-prebuilt/bin/phantomjs')
});
const express = require('express');
const app = express();

// Prep config for app
let UA = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0';

app.get('/', function(req, res) {
	let url = req.query.url;

	if (url === 'undefined' || url === undefined) {
		return res.send('Please send a url :)');
	}

	url = encodeURI(url);

	console.log("url: ", url);

	horseman
		.on('loadStarted', onLoadStart)
		.on('loadFinished', onLoadFinish)
		.on('timeout', onTimeout)
		.on('consoleMessage', onMessage)
		.on('error', onError)
		.userAgent(UA)
		.open(url)
		.html()
		.then(function(html) {
			console.log("Html ready");
			res.send(html);
		})
		.close();
});

app.listen(5000, function() {
	console.log('Example app listening on port 5000!');
});

function onMessage(msg) {
	console.log('onMessage: ', msg);
};

function onError(msg, trace) {
	console.log('onError: ', msg);
	console.log('onError - trace: ', trace);
};

function onTimeout(msg) {
	console.log("onTimeout: ", msg);
}

function onLoadStart() {
	console.log("onLoadStart");
}

function onLoadFinish(msg) {
	console.log("onLoadFinish: ", msg);
}
```

**Comment by awlayton** [comment]
I don't really know much about docker, but you are using `phantomjs-prebuilt` in a weird (wrong?) way.

```javascript
const phantomjs = require('phantomjs-prebuilt');
const Horseman = require('node-horseman');
const horseman = new Horseman({
	ignoreSSLErrors: true,
        sslProtocol: 'any',
        webSecurity: false,
	phantomPath: phantomjs.path // Like this
});
```

Also, could you post specifically was is wrong and a log of the output when running with `DEBUG='horseman*'` and `BLUEBIRD_DEBUG=1` set?

**Comment by robertpallas** [comment]
I use Horseman and Phantom in Docker, not with prebuilt. My Dockerfile:

    # PhantomJS
    RUN apt-get install -y libfreetype6 libfontconfig wget
    RUN wget -q --user-agent="Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6" https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    RUN tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
    RUN install -t /usr/local/bin phantomjs-2.1.1-linux-x86_64/bin/phantomjs
    RUN rm -rf phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2

For your end goal though I think its much better to use Angular Universal. If you are not on Angular 2 and app is not super complex then upgrade it. The effort is worth the return.

**Comment by sp90** [comment]
@robertpallas we have a huge project, and its a project in transition between legacy web, prerender stuff for all users, towards a dynamic ng1 app that only prerenders stuff for the bots.

I will try your setup

**Comment by sp90** [comment]
@awlayton & @robertpallas i made it work by installing the phantomjs from the bin, something that didn't work with the prebuilt version

**Comment by awlayton** [comment]
What do you mean @sp90? Like you install PhantomJS in the docker instead of using npm to get it?

**Comment by sp90** [comment]
i installed as @robertpallas said

**Comment by awlayton** [comment]
So then is the answer that `phantomjs-prebuilt` does not work with Docker for some reason?

**Comment by sp90** [comment]
@awlayton yes that is correct 👍

**Comment by awlayton** [comment]
Closing since there is no issue in horseman. Perhaps someone should open an issue for `phantomjs-prebuilt`, if there isn't one already.
