### ISSUE TITLE
captureContent to save the response body

### ISSUE THREAD

**Issue by antonymca** [johntitus/node-horseman#245]
Hi,

In phantomjs 2.0.1 version, there is a capability to save the response body.

To get the response body we need to set page.captureContent = ['.*']; which is working in phantomjs code.

But when i tried to integrate it with node horse man it is not working, need your help to set that value in node horseman.

Thanks

**Comment by awlayton** [comment]
Could you be more specific about what you tried when you "tried to integrate it"?

**Comment by antonymca** [comment]
fixed the issue.

**Comment by mohammadjavadraadi** [comment]
Hi, would you explain how you fixed the issue? I'm facing the same problem. I'm interested in capturing JSON responses. Would you also provide me with a sample code?
Thanks
