### ISSUE TITLE
horseman.evaluate error handling

### ISSUE THREAD

**Issue by Turboman99** [johntitus/node-horseman#246]
Hello, excellent module I plan on using it extensively. 

I do have one issue though: it seems like when using horseman.evaluate(), the function(s) to be run on the webpage sometimes fail or are rejected. I'm looking into why but more importantly, is it possible to handle these errors in node/horseman? I'm using eval in a script that visits various webpages one at a time and uses $.each() to report on the DOM elements which are found there.

Currently, when a call to evaluate() fails, it will break the Promise chain. Here's some output that may make this more clear:

p = 2
p's new value: 3
  horseman .close(). +9ms
Following Link
Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0
  horseman .setup() creating phantom instance 12 +1ms
  horseman phantom created +702ms
  horseman phantom version 2.1.1 +4ms
  horseman page created +6ms
  horseman phantomjs onLoadFinished triggered +7ms success NaN
  horseman injected jQuery +21ms
  horseman .userAgent() set +10ms Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0
{ title: 'TEST – An Official Journal of the Spanish Society of Statistics and ...',
  url: 'http://www.springer.com/statistics/journal/11749' }
  horseman .open() +0ms http://www.springer.com/statistics/journal/11749
  horseman phantomjs onLoadFinished triggered +8s success 1
  horseman jQuery not injected - already exists on page +5ms
  horseman .waitForSelector() +4ms div
  horseman .waitFor() +0ms elementPresent div
  horseman .waitFor() completed successfully +60ms
  horseman .waitForSelector() complete +0ms
  horseman .evaluate() +0ms <anonymous>
{ a: 174, div: 269, 'div.main': 0 }
closing this instance of Follow 3
stepping...
p = 3
p's new value: 4
  horseman .close(). +9ms
Following Link
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
  horseman .setup() creating phantom instance 13 +1ms
  horseman phantom created +720ms
  horseman phantom version 2.1.1 +3ms
  horseman page created +7ms
  horseman phantomjs onLoadFinished triggered +8ms success NaN
  horseman injected jQuery +19ms
  horseman .userAgent() set +12ms Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
{ title: 'Free Personality Test | 16Personalities',
  url: 'https://www.16personalities.com/free-personality-test' }
  horseman .open() +1ms https://www.16personalities.com/free-personality-test
  horseman phantomjs onLoadFinished triggered +5s success 1
  horseman jQuery not injected - already exists on page +4ms
  horseman .waitForSelector() +3ms div
  horseman .waitFor() +0ms elementPresent div
  horseman .waitFor() completed successfully +60ms
  horseman .waitForSelector() complete +0ms
  horseman .evaluate() +0ms <anonymous>
Unhandled rejection fn
evaluate

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61    at Horseman.<anonymous> (/Users/Jonathan/node_modules/node-horseman/lib/actions.js:839:38)
    at Horseman.tryCatcher (/Users/Jonathan/node_modules/node-horseman/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Jonathan/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/Jonathan/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/Users/Jonathan/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/Users/Jonathan/node_modules/node-horseman/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/Jonathan/node_modules/node-horseman/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Jonathan/node_modules/node-horseman/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

I've seen a couple of sites pop up here that seem to be killing the process and I'd like to implement some error handling for sites that cause a failure. I'm just not sure where to do it. I will be grateful for any help or suggestions.

Thanks! And thank you for your work.

**Comment by GeekEdem** [comment]
Same issue when I use .evaluate method and there try use jQuery with horseman 3.2.0

**Comment by Turboman99** [comment]
Thanks, GeekEdem. I updated horseman to 3.2.0 and tried my script again. Same result though, and on the same page. 

I tried adding event handlers for errors and alerts on the webpage (https://www.16personalities.com/free-personality-test) but those were not called so it looks like the error is happening elsewhere. 

I'll post the code I'm using for this operation as soon as I have a chance.

**Comment by Turboman99** [comment]
I was able to resolve this issue by rewriting my eval function as try/catch

**Comment by Vinayk93** [comment]
Same error looking for solution and reason.
