### ISSUE TITLE
run arbitrary code in a chain

### ISSUE THREAD

**Issue by joelanman** [johntitus/node-horseman#25]
Hi - great lib :)

Is it possible to run arbitrary code in a chain?

In the node context, not the browser context (which is `.evaluate`).

for example:

```
horseman
  .open("www.gogle.com")
  .wait(1000)
  .then(function(){
    //do stuff here
  });
```

**Comment by johntitus** [comment]
There's no `then` function - you don't need it. You can just do this:

```js
horseman
  .open("www.gogle.com")
  .wait(1000)

//do stuff here. Won't occur until after the previous chain finishes.

horseman
  .open("www.yahoo.com")
```

**Comment by joelanman** [comment]
sorry yes that works! I'm having some issues but that's clearly not it. Is there a way to make phantom/horseman more verbose? I'm already running `DEBUG=horseman`

**Comment by joelanman** [comment]
my code:

```
	console.log("waiting 5 seconds ...");

	horseman.wait(5000);

	console.log("... done waiting");
```

before this I use `.manipulate` to click a link.

The output is

```
horseman .evaluate() fn on the page +52ms
waiting 5 seconds ...
  horseman load finished, injecting jquery and client scripts +1s
```

then it hangs - "... done waiting" is never logged

**Comment by johntitus** [comment]
Not sure what's going on there. When you click a link, are you waiting for a new page to load? If so you may want to use `.waitForNextPage()`. If you're waiting for an element to become visible, you may want to try `.waitForSelector(selector)`.

Also, make sure you're `.close()`ing horseman when it's done.

**Comment by joelanman** [comment]
sorry, this was a bizarre redirect issue on the site I'm trying to navigate - many thanks for your time!

there's a page on the site which redirects by using javascript to submit a form on load

I fixed by using two `waitForNextPage`.
