### ISSUE TITLE
jQuery is not being included

### ISSUE THREAD

**Issue by swgamerx** [johntitus/node-horseman#256]
getting the error **Unhandled rejection ReferenceError: $ is not defined** with a default horseman and a horseman with settings to inject jquery. 
`var horseman = new Horseman({
        injectJquery: true
    });`

**Comment by mountaindrifter** [comment]
This injects jQuery into the webpage, not horseman. Are you trying to access the jQuery from a .evaluate(fn) type, or from something in node/horseman like a .then(fn)

you may want to post the code that is throwing the error

**Comment by awlayton** [comment]
I am going to close this assuming @mountaindrifter was correct about the situation. Thanks for answering @mountaindrifter!
