### ISSUE TITLE
.crop affects all subsequent .screenshot calls

### ISSUE THREAD

**Issue by joelanman** [johntitus/node-horseman#26]
In a script, I was cropping some areas, then wanting to take full screenshots later on.

However, the `clipRect` set by `.crop` affects all subsequent `.screenshot` calls - is this by design?

Also, not sure why  a viewport of 1200 x 800 is set after a crop? For me, altering this code so that the clipRect is removed after a crop works:

https://github.com/johntitus/node-horseman/blob/master/lib/actions.js#L267

```
  this.page.set('clipRect', rect, function(){
    self.pause.unpause('clipRect');
    self.screenshot( path );
    // self.page.set("viewportSize",{
    //   width: 1200,
    //   height: 800
    // });
    self.page.set('clipRect', {});
    return this;
  });
```

**Comment by johntitus** [comment]
Fixed in version 1.5.2.
