### ISSUE TITLE
phantom.getCookies is undefined

### ISSUE THREAD

**Issue by kritollm** [johntitus/node-horseman#27]
line 233 in lib/action.js:

this.phantom.getCookies(function( result ){

I can't find this method in the phantom API. Maybe the phantom object is extended, but I get this error:
undefined is not a function at Horseman.exports.cookies(/Users/kristian/WebstormProjects/HorseManScraper/node_modules/node-horseman/lib/actions.js:233:18)

**Comment by johntitus** [comment]
Linking this to an issue in node-phantom-simple.

https://github.com/baudehlo/node-phantom-simple/issues/42

**Comment by johntitus** [comment]
Fixed in 1.5.3.
