### ISSUE TITLE
Delayed prepended content is not captured in screenshot

### ISSUE THREAD

**Issue by sundjimson** [johntitus/node-horseman#270]
I'm trying to use horseman-node to do some automatic testing to see rendered content for various screen sizes. It is very promising besides the fact that it misses dynamically prepended content.

To isolate the problem, I've got this simple code that produces a green div after 2000 ms and the green div contains a timestamp showing the delay from window.onload and it works great in a standard browser (tested with Chrome and Firefox).

```html
<!DOCTYPE html>
<html>
<head>
<style>
  .box {
    width: 300px;
    height: 100px;
    background-color: #00ff00;
    text-align: center;
    line-height: 100px;
    display: inline-block;
    margin: 1em;
  }
</style>
<script type="text/javascript">
  window.onload=function() {
   var startTime = Date.now();
    setTimeout(showDiv1, 2000);
  };

function showDiv1() {
  div1 = document.createElement("div");
  div1.id = "div1";
  div1.className = 'box';
  div1.innerHTML = (Date.now() - startTime)/1000;
  document.getElementById("body").prepend(div1);
};
</script>
</head>
<body id="body">   
  <span id="timer"></span> s
  <script type="text/javascript">
    var startTime = Date.now();
    var interval = setInterval(function() {
    var elapsedTime = Date.now() - startTime;
        document.getElementById("timer").innerHTML = (elapsedTime / 1000).toFixed(3);
    }, 100);
</script>
</body>
</html>
```

Check this [Fiddle][1]

When using horseman, the "box" is missing in the screenshot. The code that I've tried is the following:

```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman({'timeout':10000});

horseman
  .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
  .viewport(640, 350)
  .open('http://localhost/~test/horseman/inject/index.html')
  .wait(6000)
  .screenshot('screenshots/injected.png')
  .close();
```

The generated image only shows the timer value after wait without the green div which is shown correctly in the browser.

[Result from running horseman on node via script above][2]

In the ideal test case for me I would like to use .waitForSelector('#div1') and take the screenshot when it has been prepended. But if horseman cannot cope with dynamically prepended content the waitForSelector-solution won't work.

Am I missing something, or are there limitations with horseman?

Question copied from: 
[http://stackoverflow.com/questions/42798054/horseman-misses-dynamically-prepended-content](**url**)

  [1]: https://jsfiddle.net/mL9muj0d/1/
  [2]: https://i.stack.imgur.com/laAef.png

**Comment by awlayton** [comment]
If you run the script with debugging on (`DEBUG='horseman*' node script.js`) you can see that the *real* problem is that you are calling [`ParentNode.prepend()`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend) which is ***experimental*** and not supported by PhantomJS, so the div is never actually being added.

Hoseman has no problem with JavaScript manipulating the DOM. Also, you are right that it is better to wait for the div that to have set wait time.

See below for corrected files and the resulting output.

```html
<!DOCTYPE html>
<html>
<head>
<style>
  .box {
    width: 300px;
    height: 100px;
    background-color: #00ff00;
    text-align: center;
    line-height: 100px;
    display: inline-block;
    margin: 1em;
  }
</style>
<script type="text/javascript">
  window.onload=function() {
   var startTime = Date.now();
    setTimeout(showDiv1, 2000);
  };

function showDiv1() {
  div1 = document.createElement("div");
  div1.id = "div1";
  div1.className = 'box';
  div1.innerHTML = (Date.now() - startTime)/1000;
  document.getElementById("body").appendChild(div1); // Use a supported, standard function
};
</script>
</head>
<body id="body">   
  <span id="timer"></span> s
  <script type="text/javascript">
    var startTime = Date.now();
    var interval = setInterval(function() {
    var elapsedTime = Date.now() - startTime;
        document.getElementById("timer").innerHTML = (elapsedTime / 1000).toFixed(3);
    }, 100);
</script>
</body>
</html>
```

```javascript
var Horseman = require('./');
var horseman = new Horseman({'timeout':10000});

horseman
  .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
  .viewport(640, 350)
  .open('./i270.html')
  .waitForSelector('#div1') // Either .waitForSelector or .wait works just fine
  .screenshot('screenshots/injected.png')
  .close();
```

`screentshots/injected.png`:
![injected](https://cloud.githubusercontent.com/assets/4231765/24108739/e37d869a-0d64-11e7-826e-206f199bc9fe.png)
