### ISSUE TITLE
Failed to load url when page redirected for PDF file

### ISSUE THREAD

**Issue by lenyapugachev** [johntitus/node-horseman#272]
After horseman clicks an element on web-site I'm scraping, page redirecting to generated PDF file, which I need to save locally.

But when it does horseman throws an exception `Unhandled rejection Error: Failed to load url`

I tried to call `.headers({"Content-Type": "application/pdf"})` before `open()`, but I'm using `waitForNextPage` and a first one throws same exception.

Then I tried to call `.headers({"Content-Type": "application/pdf"})` just before horseman clicks on element which triggers redirection, but following `resourceReceived` event log this action suppressed redirection totally.

**Comment by awlayton** [comment]
PhantomJS can only load ***webpages***. It cannot open URLs unless they are ***webpages***.
