### ISSUE TITLE
Adding user input whilst horseman is still running?

### ISSUE THREAD

**Issue by FrankydeForty** [johntitus/node-horseman#275]
Is it possible to add user input half way through a horseman instance.

an example would be, the user submits 'info 1' this starts up horseman and then the user needs to input 'info2' the user does not know info 2 before hand but it remains the same.

Can I with horseman, keep the instance of horseman running untill the user has entered  info2 with an alert poping up asking for info 2 

or do i have to run one instance for info 1 close it and then start another instance with info 1 as variable for  the user to see instance submit info2?

**Comment by awlayton** [comment]
Yes, you can read user input inside a `.then()` in the chain or whatever. It's all just Promises.
