### ISSUE TITLE
Inspecting raw web request

### ISSUE THREAD

**Issue by emarthinsen** [johntitus/node-horseman#282]
Is it possible to inspect the raw web request that is generated on an `open` or `click` call? I created an event handler for `resourceRequested`, but it doesn't show the cookies that will be sent and it only shows a partial list of the headers that will be sent.

**Comment by awlayton** [comment]
I do not know of a way to see any more than what you get with onResourceRequested. If that is not what you need, you will have to look into PhantomJS specific things.

Closing since this is not a horseman specific thing.
