### ISSUE TITLE
How to iterate on html result

### ISSUE THREAD

**Issue by adobeSlash** [johntitus/node-horseman#288]
Hello, i'm really new to Horseman and scrapping.
I'm trying to retrieve data from a div selector.
Actually I managed to get the data from one "article" but I can't find a way to iterate over every "article"

```
horseman
        .open(url + '' + page)
        .html('article')
        .then((htmlRes) => {
          if(htmlRes){
            console.log(`${htmlRes}`);
            console.log("loading data in cheerio");
            var $ = cheerio.load(htmlRes);
            $('h4[class=company-name]').each(function(i, elem) {
              console.log($(this).text());
            });
            /*var li = $('li[class=stack-item]').html();
            console.log(title);
            console.log(li);*/
          }else{
            console.log("Impossible to retrieve data");
          }

        })
        .close();
  });
```

**Comment by lkasoff** [comment]
Assuming there are multiple "article" selectors on the same page, I would use something like the following:
 
```
horseman
        .open(url + '' + page)
        .wait(3000)
        .evaluate(function() {
            var articleData = [];
            $('article').each(function(index, element){
               var companyNames = [];
                $('h4[class=company-name]').each(function(i, elem) {
                companyNames.push($(this).text());
                });
               articleData.push({title: $(title).text(),
               companyNames: companyNames,
               li: $('li[class=stack-item]').html()});
          });
         return articleData;
        })
        .log()
        .close();
```

The function passed to evaluate() is executed in the headless browser with jQuery injected rather than node so you'll need to save the data to an object or variable and the use log() rather than using console.log.

**Comment by adobeSlash** [comment]
Hi, thanks for your help !

My problem is that the h4 contains every h4 of the page so the result is not what I want.
Because now I have a table and each element is the result of every h4 !

I don't know how to get only the h4 of this precise article I'm iterating on ..

`horseman
        .on('error', console.error)
        .open(url + '' + page)
        .wait(3000)
        .evaluate(function() {
          try{
            var articlesData = [];
            $('article').each(function(index, element){
               var companyNames = [];
               $('h4[class=company-name]').each(function(i, elem) {
                 //Delete the span jobs
                 //Delete the number of jobs
                 var t = $(this).text().replace(/\s+/g, '').replace(/\d+/g, '');
                 //Delete the word jobs
                 var tRes = t.substr(0, t.length-4);
                 companyNames.push(tRes);
               });
               articlesData.push(companyNames);
             });
             return articlesData;
          }catch (err) {
              return [err];
          }
         return articleData;
        })
        .log()
        .close();`

**Comment by adobeSlash** [comment]
Finally found a way to do it ! 
Thanks again for your help

```
horseman
        .on('error', console.error)
        .open(url + '' + page)
        .wait(3000)
        .evaluate(function() {
          try{
            var articlesData = [];
            $('article').each(function(index, element){
               var article = {}; // all the data of this article

               var t = $(this).find('h4[class=company-name]').text().replace(/\s+/g, '').replace(/\d+/g, '');
               var tRes = t.substr(0, t.length-4);
               article.title = tRes;

               var stackF = [];
               $(this).find('div[class=company-stack-category]').each(function(i, elem) {
                 var obj = {}; //one stack categorie
                 var stacks = []; //list of item in the aimed stack
                 obj.stackName = $(this).children('.category-title').text(); //name of the stakc
                 $(this).children('.company-stack-list').children('.stack-item').each(function(c, elem) {
                   stacks[c] = $(this).text().replace(/\s+/g, ''); //one stack element
                 });
                 //var stacksRes = stacks.join(', '); //join all the stack element in a unique string
                 //stacksRes = stacksRes.replace(/\s+/g, '');
                 obj.stackValue = stacks;
                 stackF.push(obj);
               });
               article.stacks = stackF;
               articlesData.push(article);
             });
             return articlesData;
          }catch (err) {
              return [err];
          }
         return articleData;
        })
        .log()
        .close()
```
