### ISSUE TITLE
Node horsemanjs weird scope object ga

### ISSUE THREAD

**Issue by chimerarocks** [johntitus/node-horseman#289]
there is this var 'x' defined in a global scope

`var x = 'bye'`

after that i call the horsman, as you can see:

```
horseman
.open('http://www.google.com')
```
do you see here? I'm changing the global var value

```
.then(function() {
    x = 'hi'
})
```

Now i'm passing the value to evaluate function, and now the problem begins. As you will see in the log the value of 'x' is unchanged only in the 'evaluate' scope.

```
.evaluate(function(val, done) {
    done(null, val)
}, x)
```

Did you see?

```
.then(function(e) {
    console.log('newX: ', e)
    console.log('oldX: ', x)
})
.catch(function(err) {
    console.log('err: ', err)
})
.close()
```

why the response is...

```
newX: bye
oldX: hi

```
instead of..

```
newX: hi
oldX: hi
`````````

**Comment by awlayton** [comment]
It's because Promises are asynchronous. This is neither a bug in horseman nor an incorrect result.

I am admittedly poor at explaining this sort of thing, but I suggest you read up on both Promises and JavaScript callbacks in general.
