### ISSUE TITLE
Request() error evaluating open() call: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by thanhthang20** [johntitus/node-horseman#32]
```
var pattern = '0 */'+ 5 +' * * * *';
function job(){
	console.log('Start to run every ' + 5 + ' mins');
        var price = horseman
		.open('http://viettelstore.vn/dien-thoai/apple-iphone-6-plus-64gb-ban-quoc-te--pid975.html')
		.evaluate(function () {
	       	return  $('#_price_new436').text()
		})
		console.log(price);
		horseman.close();
}
new CronJob(pattern, job, null, true, 'America/Los_Angeles');
```

I use [node-cron] (https://github.com/ncb000gt/node-cron) to to schedule crawling job as above. Horseman works very good without node-cron, when putting horseman in node-cron, the first call is ok, all call after that is fail with below error

**Request() error evaluating open() call: Error: connect ECONNREFUSED**
**Request() error evaluating evaluate() call: Error: connect ECONNREFUSED**

**Comment by johntitus** [comment]
You do a `horseman.close()` at the end of the job, so the next time the job runs, there is no connection to phantom. You need to instantiate horseman at the start of the job.

This code seems to work (note I changed it to every minute).

```js
var CronJob = require('cron').CronJob;
var Horseman = require('node-horseman');
var pattern = '0 * * * * *';

function job(){
	var horseman = new Horseman();
	var price = horseman
    	.open('http://viettelstore.vn/dien-thoai/apple-iphone-6-plus-64gb-ban-quoc-te--pid975.html')
    	.evaluate(function () {
        	return  $('#_price_new436').text()
    	});
    console.log(price);
    horseman.close();
}

new CronJob(pattern, job, null, true, 'America/Los_Angeles');
```

**Comment by thanhthang20** [comment]
thanks you so much.
