### ISSUE TITLE
Search Example, Not showing the Results?

### ISSUE THREAD

**Issue by LuckyLillia** [johntitus/node-horseman#33]
Thanks for this awesome pack. I have been searching for a way to use phantomjs from node, and horseman is exactly what I needed!

I have been going through the api and examples.

Here is one problem I am facing: When I run the quickstart example, google search,
1) It opens the google page.
2) Enters my keyword, eg, github
3) It doesn't show the results. Output - [Number of links: null]

I have attached the screenshot....

Search on Google:
------------------------

var Horseman = require('node-horseman');
var horseman = new Horseman();

var numLinks = horseman
  .open('http://www.google.com')
  .type('input[name="q"]', 'github')
  .click("button:contains('Google Search')")
  .waitForNextPage()
  .count("li.g");

// I have added this code to take screenshot.
horseman.screenshot('g3.jpeg');

console.log("Number of links: " + numLinks);

horseman.close();

// Output - Number of links: null

![g3](https://cloud.githubusercontent.com/assets/9840765/8633699/51f36548-27f4-11e5-8fa3-013cdc1b4f11.jpeg)

**Comment by johntitus** [comment]
So it looks like Google isn't using a button on that page - they using an "input".  However, if you pass in a header to tell Google that you're using Firefox, it really is a button and your code works. Here's working code:

```js
var Horseman = require('node-horseman');
var horseman = new Horseman();

var numLinks = horseman
.userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
.open('http://www.google.com')
.type('input[name="q"]', 'github')
.click("button:contains('Google Search')")
.waitForNextPage()
.count("li.g");

// I have added this code to take screenshot.

horseman.screenshot('g3.jpeg');
console.log("Number of links: " + numLinks);
horseman.close();
```

I'll update the readme with the userAgent setting.
