### ISSUE TITLE
Upgrade to node-phantom-simple v2.0 ?

### ISSUE THREAD

**Issue by wreckloose** [johntitus/node-horseman#37]
First off, thanks for the awesome package! I have gotten a lot of use out of it, and it has proven very helpful.

I am curious if you plan to upgrade Horseman to use version ^2.0 of node-phantom-simple anytime soon? I ask because I am using FreeBSD, which is not supported in versions < 2.0 of node-phantom-simple. As a result of that, I added support for FreeBSD to node-phantom-simple and submitted a pull request which was accepted some time ago, but which has only just recently made it into a release. In the interim, I have been having to manually replace Horseman's node-phantom-simple package with the custom package, which I am still having to do since Horseman's dependency is for node-phantom-simple version ^1.2.0. It would be nice if I no longer had to do this, but obviously it requires that Horseman support version ^2.0.

**Comment by johntitus** [comment]
Def need to do this. Just have to find the time...

**Comment by wreckloose** [comment]
FWIW, I replaced v1.2.0 with v2.0 in my project, and everything seemed to work fine. That said, I did get two deprecation messages printed to screen, though they didn't seem to have any negative effect functionality-wise:

Deprecated '.create(callback, options)' syntax - use '.create(options, callback)' instead
Deprecated 'phantomPath' option - use 'path' instead

**Comment by johntitus** [comment]
Give it a shot, let me know how it goes.

**Comment by wreckloose** [comment]
It looks good to me. I'm not getting any of the deprecation messages that I mentioned before, and all of the functionality that *I* use seems to be working as expected. This includes open, close, status, userAgent, headers, wait, evaluate, screenshotBase64, and various event listeners.

Thanks a lot for the quick turnaround! This really helps me out!
