### ISSUE TITLE
Change API to use Promises

### ISSUE THREAD

**Issue by johntitus** [johntitus/node-horseman#40]
Opening for comments. I've been playing with promises and would like to move the entire API to be promise based.  Using Horseman would now look something like:

```js
horseman
	.headers( headers )
	.then(function(){
		return horseman.open( 'http://httpbin.org/headers' )
	})
	.then( function(){
		return horseman.evaluate(function(){
			return document.body.children[0].innerHTML;
		});
	})
	.then( function( data ){
		var response = JSON.parse( data );					
		response.should.have.property( 'headers' );
		response.headers.should.have.property( 'X-Horseman-Header' );
		response.headers[ 'X-Horseman-Header' ].should.equal( 'test header' );
	})
        .catch( function( e ){
           console.log(e)
        });

```
This would remove the dependency on `deasync`, and make it easy to run multiple horsemen at the same time, without blocking the entire process.

Downwide - API gets more convoluted/not as easy to read.

**Comment by johntitus** [comment]
Tentative [v2](https://github.com/johntitus/node-horseman/tree/v2) branch is available to check out.  Only some actions are working, see the tests to see what is working.

**Comment by greim** [comment]
Nice. :+1:  from me. As long as the promise implementation conforms to the spec, the above would translate into this using async/await:

```js
try {
  await horseman.headers( headers );
  await horseman.open( 'http://httpbin.org/headers' );
  let data = await horseman.evaluate(function() {
    return document.body.children[0].innerHTML;
  });
  let response = JSON.parse( data );
  response.should.have.property( 'headers' );
  response.headers.should.have.property( 'X-Horseman-Header' );
  response.headers[ 'X-Horseman-Header' ].should.equal( 'test header' );
} catch (ex) {
  console.error(ex.stack);
}
```

(Something nearly identical could also be done with generators, since async/await isn't fully standardized yet.) I think this can massively simplify testing code the way the original API did, but without ever blocking the thread.

**Comment by pitaj** [comment]
This would be absolutely awesome

**Comment by johntitus** [comment]
Just release version 2.0.0. Expect a few bumps as it was a big re-write.

**Comment by greim** [comment]
:+1:
