### ISSUE TITLE
'On confirm' event is not responding to callback return value

### ISSUE THREAD

**Issue by Unlearn** [johntitus/node-horseman#41]
After writing some Mocha tests utilising Horseman I've come across an issue with Javascript confirmation dialogues. 

Following the PhantomJs documentation of dealing with [confirmation events](https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#onconfirm). I'm returning `true` from the on confirm callback. This page was referenced by the [Horseman docs](https://github.com/johntitus/node-horseman#onevent-callback).

As explained on the PhantomJs page:
> `true` === pressing the "OK" button, `false` === pressing the "Cancel" button
};

No matter what I return in my Horseman code it says it says cancel was pressed.

I've created some test files to illustrate this issue. 

My test HTML: 
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Confirm check</title>
    <script>
        function confirmation() {
            var answer = confirm('OK or Cancel?');
            if (answer === true) {
                console.log('You pressed OK');
            } else {
                console.log('You pressed Cancel');
            }
        }
    </script>
</head>
<a id="confirm" href="#" onclick="confirmation()" >Confirm?</a>
</body>
</html>
```

My test Horseman script:
```javascript
var Horseman = require('node-horseman');

var browser = new Horseman();
var url = 'file:///Users/user/Desktop/confirm.html';

browser
    .viewport(1920, 1080)
    .on('loadFinished', function(status) {
        console.log('%s Status %s', url, status);
    })
    .on('consoleMessage', function( msg, lineNumber, sourceId ) {
        console.log('Console: %s, %s, %s', msg, lineNumber, sourceId);
    })
    .on('confirm', function( msg ) {
        console.log('Confirm message: %s', msg);
        return false;
    })
    .open(url)
    .click('a#confirm');

browser.close();
```

The terminal output with `DEBUG=horseman` enabled: 
```shell
  horseman .setup() creating phantom instance on +0ms
  horseman .setup() phantom instance created ok. +448ms
  horseman .setup() creating phantom page. +1ms
  horseman .setup() phantom page created ok. +21ms
  horseman .setup() setting viewport. +0ms
  horseman .setup() viewport set ok. +4ms
  horseman .viewport() set +60ms
  horseman .on loadFinished set. +0ms
  horseman .on consoleMessage set. +0ms
  horseman .on confirm set. +0ms
  horseman .opening: file:///Users/user/Desktop/confirm.html +0ms
file:///Users/user/Desktop/confirm.html Status success
  horseman .open: file:///Users/user/Desktop/confirm.html - status: success +22ms
Confirm message: OK or Cancel?
Console: You pressed Cancel, undefined, undefined
  horseman .click() a#confirm +81ms
  horseman .close(). +0ms
```

I may be doing things wrong but I've not seen any indication that I should be doing things differently to respond to confirmation events. 

Any help with this would be appreciated.

Cheers.

**Comment by Unlearn** [comment]
Hi @johntitus thanks for following this up with the PhantomJs guys. 

Do you have any recommend work-arounds which could be used in Horseman? We chose Horseman as it's powerful but simple enough for our less skilled testing developers to use it would be great if we could keep using it and writing tests before the PhantomJs team come up with a fix.

Thanks again.

**Comment by johntitus** [comment]
Grab 1.5.7. I added a wrapper around the issue, along with tests for clicking both Ok & Cancel to make sure both work.

**Comment by marianocarpentier** [comment]
Hi @johntitus, I am experiencing this issue with PhantomJs 2.0.0 and Horseman 2.8.1.
I took @Unlearn minimal test and I modified to work with promises:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Confirm check</title>
    <script>
        function confirmation() {
            var answer = confirm('OK or Cancel?');
            var div = document.createElement('div');
            div.id = "result-div";
            if (answer === true) {
                div.innerHTML = "YES";
                console.log("Clicked OK");
            } else {
                div.innerHTML = "NO";
                console.log("Clicked Cancel");
            }
            document.body.appendChild(div);
        }
    </script>
</head>
<body>
<a id="confirm" href="#" onclick="confirmation()">Confirm?</a>
</body>
</html>
```
And the JS:
```javascript
'use strict';

var Horseman = require('node-horseman');

var browser = new Horseman();
var url = '/Users/marianocarpentier/development/horsemanMinimal/index.html';

var finished = false;
var promise = browser
    .viewport(1920, 1080)
    .on('loadFinished', function (status) {
        console.log('%s Status %s', url, status);
    })
    .on('consoleMessage', function (msg, lineNumber, sourceId) {
        console.log('Console: %s, %s, %s', msg, lineNumber, sourceId);
    })
    .on('confirm', function (msg) {
        console.log('Confirm message: %s', msg);
        return true;
    })
    .open(url)
    .click('a#confirm')
    .waitForSelector('#result-div')
    .evaluate(function (selector) {
        return ($(selector).text() === "YES");
    }, '#result-div')
    .then(function (res) {
        if (res) {
            console.log("Success");
        } else {
            console.log("Error");
        }
        browser.close();
        finished = true;
    });


var intl = setInterval(function () {
    if (finished)
        clearInterval(intl);
}, 100);
```
Following this thread, I managed to make it work by adding this workaround code into the **actions.js** file, line 999 for me:
```javascript
...
else {
	var pageEvent = "on" + eventType.charAt(0).toUpperCase() + eventType.slice(1);
	self.page[pageEvent] = callback;
	if(pageEvent === "onConfirm") {
		self.page.setFn(pageEvent, callback);
	}
}
...
```
The **if(pageEvent === "onConfirm") {...}** is my workaround. If you have a better option, please let me know!

Cheers,

**Comment by awlayton** [comment]
It sounds like we need to consider fixing the other event handlers where PhantomJS expects a return value, e.g., `onPrompt`.

**Comment by awlayton** [comment]
@marianocarpentier, it looks a *very* similar line of code used to be there and has been removed. Perhaps @johntitus has a reason for removing it?

**Comment by marianocarpentier** [comment]
Actually, I don't consider this is a fix, I just added that as a temporary solution. I think that was removed for a reason, and since I don't know what that reason is, I didn't add code for ```onPrompt``` or made a pull request.

**Comment by kenleytomlin** [comment]
I can confirm I'm experiencing the same issue with the 'confirm' event.  I'm using node-horseman 2.8.2 and phantomjs 1.9.18.  @marianocarpentier's workaround fixed this for me.

**Comment by awlayton** [comment]
I think the code that was there before *is* the way (or at least a way( to go about fixing it @marianocarpentier. Do you want to chime is as to why said code was removed @johntitus?

**Comment by awlayton** [comment]
I am calling this issue solved in v3. I added an `.at` action. The return value of the callback is properly given to phantom for `confirm`, `prompt`, etc.

The way node-phantom-simple works, the `.on` callback's return value cannot have an effect.
