### ISSUE TITLE
Horseman Won't Install on iojs (> v2.5.0) or node (v4.0.0)

### ISSUE THREAD

**Issue by db-ryan** [johntitus/node-horseman#43]
It seems that I can't install node-horseman on iojs greater than version 2.5.0 or node 4.0.0.

Is node-horseman still being supported?  It looks like the trouble may be with 'deasync'?  I just figured I would start a thread for others trying to upgrade.

- - -
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/home/doppleruser/.nvm/versions/io.js/v3.0.0/bin/iojs" "/home/doppleruser/.nvm/versions/io.js/v3.0.0/bin/npm" "install"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.0.10 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.0.10 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/package-trials/npm-debug.log
- - -

**Comment by db-ryan** [comment]
I'm stupid....just use v2.0.0 of node-horseman and everything works fine.  Please don't embarrass me on reddit.

**Comment by johntitus** [comment]
Reddit?

**Comment by db-ryan** [comment]
A bad joke....sorry.
