### ISSUE TITLE
`waitForNextPage` doesn't work

### ISSUE THREAD

**Issue by edge** [johntitus/node-horseman#44]
I've been trying to use `waitForNextPage`, but it doesn't work as expected.

In your links example, if you change [this line](https://github.com/johntitus/node-horseman/blob/master/examples/links.js#L69) to
```js
return horseman.waitForNextPage();
```
the screenshot will give you an unfinished page. The same occurs with the pizza example.

So far I've been able to hack it out with `waitForSelector`, but that's highly prone to error.

Horseman ends my long search for an up-to-date Phantom driver, but this bug renders it almost unusable.

I'm on Phantom 2.0.0.

**Comment by edge** [comment]
I've solved it temporarily with this:
```js
await horse.waitFor(function() {
	return (location.pathname === '/login.php') && (document.readyState === 'complete');
}, true);
```

**Comment by johntitus** [comment]
The google example uses the waitForSelector because Google is doing a single-page app.  The pizza example doesn't change pages.

That said, I have seem some weirdness with this feature. I think it's a timing/race condition - the promise is resolving AFTER the page has already changed.  I'll play around with it a bit to see if I can pin it down.

**Comment by edge** [comment]
Yeah, it was definitely giving me problems for even traditional sites.

Checking `document.readyState === 'complete'` would probably fix things. But the problem is that this would most likely get checked before the page even changes, in which case it is in fact `'complete'`.

**Comment by johntitus** [comment]
In version 1.x, it checked for `document.readyState !== 'complete'` and then waited for  `document.readyState === 'complete'`.  Couldn't get that to work with the new Promise-based api. My guess is that if a user clicked on an anchor, by the time that promise resolved the ready state had already unloaded.

I'm going through and adding a bunch of debug statements now to help me run it down.  If you have a good, public failing site I can test with, it would help.

**Comment by johntitus** [comment]
If you get a chance, can you try your test with the latest master?  I hooked into the PhantomJS onLoadFinished event so it should be a lot more accurate now.  I'll hold off on publishing it to NPM until you've had a chance to try it out, or a few days, whichever comes first.

**Comment by edge** [comment]
Got it, I'll have access to the tests in a few hours.

**Comment by edge** [comment]
@johntitus Just ran the tests, it works flawlessly (even a little faster too).

LGTM
