### ISSUE TITLE
Confirm and Alert not working

### ISSUE THREAD

**Issue by mufasahaha** [johntitus/node-horseman#47]
Here's the code I used: 

yield horseman.on('alert', co.wrap(function*(msg) {
            console.log(':\nALERT: ' + msg);
            return true;
        }));

I also set an event for urlChanged and that works perfectly fine with the same format above. (using the co.wrap)

Any idea what might be the cause?

The rest of the code works fine if a confirm/alert is not on the site. Also, not sure if this is important but I used an android device user agent... so this was for mobile.

Thanks

**Comment by johntitus** [comment]
It may have to do with where the function is occurring.  `onUrlChanged` gets wrapped inside of the actions.js file, while `onAlert` is passed directly to Phantom.  You may want to try not co.wrap'ing the function.  Also, you probably don't need to yield to any `.on` functions as it just sets the handler.

Finally, you may want to try your code with version 2.1.0 of node-horseman. The api is now fully chainable, so you can probably rewrite your yield statements to take advantage of it.

**Comment by mufasahaha** [comment]
Hi John, thanks for the quick reply :bow:
