### ISSUE TITLE
Crop should allow something else then path

### ISSUE THREAD

**Issue by Swatto** [johntitus/node-horseman#5]
Provide a path is nice for local storage of image but we should be allowed to give things like a buffer for other manipulations.

I would be happy to be allowed to upload it, serve it with HTTP, etc... It's endless.

**Comment by johntitus** [comment]
Unfortunately, PhantomJS will only render to a file. 

See http://phantomjs.org/api/webpage/method/render.html

**Comment by Swatto** [comment]
That's not true, I use `renderBase64` to do that in a service that I write.

See http://phantomjs.org/api/webpage/method/render-base64.html

**Comment by johntitus** [comment]
Ah, nice. Sorry about that, wasn't aware of that method.

**Comment by johntitus** [comment]
Added `screenshotBase64(type)`.  Decided to not overload `screenshot(path)` since `screenshot` is chainable, and `screenshotBase64` is not (needs to return the base64 encoded string).
Closed via commit 90ee53eadb6410336bc126135b6db8a5e972f234

**Comment by jeprojects** [comment]
Is it possible top crop directly to base64?

something like a .cropBase64 function?

**Comment by johntitus** [comment]
No, but pull requests are welcome.

https://github.com/johntitus/node-horseman/blob/master/lib/actions.js#L356-L413
