### ISSUE TITLE
Feature Request: ".do"

### ISSUE THREAD

**Issue by peerbolte** [johntitus/node-horseman#53]
In order to run custom functions during a chain i would like to propose a "do" function. The function can be added to actions.js and could be as simple as:

    exports.do = function(fn){
        return fn();
    } 

In the chain the user can use do like this:

    horseman
    .open('http://'example.com')
    .screenshot('test.png')
    .do(function(){
        updateProgress();
        console.log('took a screenshot')
    })
    .type('input[name="Email"]', 'email@example.com')
    .click('input[name="signIn"]')
    .do(function(){
        console.log("signed in")
    })
    .finally(function(){
       console.log('finished');
       horseman.close(); 
    });

The function might need some polishing, but you get the idea. Extra functionality could be to call a next() function within the do function, to continue the chain.

**Comment by johntitus** [comment]
Definitely a good idea.  I think the function needs to be able to handle async stuff, so maybe some kind of 'done' callback needs to get passed in? Then wrap it all with promise that resolves when done is called.

Not sure when I'll have time for this, so if anyone wants to take it on, I'd appreciate it.
