### ISSUE TITLE
Support header footer in pdf

### ISSUE THREAD

**Issue by rohitghatol** [johntitus/node-horseman#55]
Support Header Footer in pdf render part. Something like following

page.paperSize = {
        format: 'A4',
        margin: "1cm",
        /* default header/footer for pages that don't have custom overwrites (see below) */
        header: {
            height: "1cm",
            contents: phantom.callback(function(pageNum, numPages) {
                if (pageNum == 1) {
                    return "";
                }
                return "< h1>Header <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
            })
        },
        footer: {
            height: "1cm",
            contents: phantom.callback(function(pageNum, numPages) {
                if (pageNum == numPages) {
                    return "";
                }
                return "< h1>Footer <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
            })
        }
    };

**Comment by johntitus** [comment]
I opened an issue with `node-phantom-simple`, to see if there's a way to do it.
https://github.com/baudehlo/node-phantom-simple/issues/78

**Comment by starsinmypockets** [comment]
This would help with one of my primary node / phantom use cases as well. Following.

**Comment by rohitghatol** [comment]
Update - Gave patch to node-phantom-simple to fix this issue

https://github.com/baudehlo/node-phantom-simple/pull/83
