### ISSUE TITLE
process.exit() from cmd

### ISSUE THREAD

**Issue by ortexx** [johntitus/node-horseman#59]
Hi! After require('node-horseman') i lose control of the process in cmd (windows 8) 
i have to write e.g. process.on('SIGINT', function() { process.exit(); }) yourself to close the process from terminal on ctrl+c. e.t.c

**Comment by johntitus** [comment]
Can anyone else running horseman on windows confirm/help with this one?

**Comment by johntitus** [comment]
Can you give this a shot with the new version 2.8.0? `node-phantom-simple` closed some issues related to SIGINT - perhaps it helped?

**Comment by ortexx** [comment]
Yes, it works now!
