### ISSUE TITLE
Possible to run node horseman with remote debugger?

### ISSUE THREAD

**Issue by starsinmypockets** [johntitus/node-horseman#60]
Phantomjs supports: --remote-debugger-port=9000

Is there any support for this via nodehorseman?

**Comment by johntitus** [comment]
No. Adding this as a to-do enhancement.

**Comment by awlayton** [comment]
I would consider allowing passing arbitrary arguments to the phantomjs instance. I like options.

**Comment by starsinmypockets** [comment]
This sounds like a fabulous idea @awlayton

**Comment by awlayton** [comment]
resolved by #112
