### ISSUE TITLE
.crop function

### ISSUE THREAD

**Issue by jeprojects** [johntitus/node-horseman#63]
Hi,

I tried passing in the selector to the .crop function, but it would not take the screenshot of the same position every time.

Could this be because the page hasn't fully loaded yet?

**Comment by johntitus** [comment]
I wouldn't think so, but perhaps you could try putting in a `.wait(1000)` and then taking a screenshot?  Or, could the selector not be unique? Or, could the page be moving the selector's DOM object around?

You could also use pass in your own bounding rectangle, if you want. like, `crop({ top: 50, left: 200, width: 400, height: 200})`

**Comment by jeprojects** [comment]
Thanks for your help.

I have found the adding viewport to the job made it stable.

**Comment by johntitus** [comment]
Good tip, thanks.
