### ISSUE TITLE
facebook require to turn on cookies on browser

### ISSUE THREAD

**Issue by takaaptech** [johntitus/node-horseman#64]
Hi,
I am using node-horseman to sign in facbook but it say cookies must be turn on browser. How can i do that? Thanks so much!

**Comment by johntitus** [comment]
Cookies are on by default. There are some examples in the tests:

https://github.com/johntitus/node-horseman/blob/master/test/index.js#L187-L251

**Comment by takaaptech** [comment]
Correct me i am wrong, here is my test, but the screenshot still show can not login, user must be turn on cookies:

var Horseman = require('node-horseman');
var horseman = new Horseman();
			var cookie = {
				name: "test",
				value: "cookie",
				domain: 'httpbin.org'
			};
horseman
		.cookies(cookie)
		.userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
		.open('https://www.facebook.com')
		.type('input[id="email"]', 'email here*****')
		.type('input[id="pass"]', 'Pass here*****')
		.click('label[id="loginbutton"]')
		.waitForNextPage()
		.text('div[id="pagelet_bluebar"]')
		.log() // prints out the number of results
		.screenshot('home.png')
		.close();

**Comment by johntitus** [comment]
When I run your code, I get a facebook page asking me to type in a security code.

**Comment by SinhVienDHQG** [comment]
OK thanks @johntitus I will setup node-horseman on window and test again!

**Comment by johntitus** [comment]
Closing due to lack of info.

**Comment by takaaptech** [comment]
I just install phantomjs 2.0 and this error gone. Thanks!
