### ISSUE TITLE
Shouldn't open() with status=fail reject the promise?

### ISSUE THREAD

**Issue by lynnReilaender** [johntitus/node-horseman#65]
If, for example, open() gets a wrong/unknown URL, the status is 'fail' (but err is null). In this situation I would expect a rejection of the promise. 

By the way: Thanks for node-horseman, it's brillant.

Lynn

**Comment by johntitus** [comment]
Makes sense to me.  I'll tag it as to-do for a future version, as this would likely be an API breaking change and I just feel weird about bumping to 3.0 for just this.

**Comment by lynnReilaender** [comment]
'totally agree, thanks.

**Comment by awlayton** [comment]
Various actions can return Errors. We should probably make those reject the Promises too.

**Comment by awlayton** [comment]
Closed in v3
