### ISSUE TITLE
Can't take array from a function and write to a .json file.

### ISSUE THREAD

**Issue by lockykeaney** [johntitus/node-horseman#66]
I have written a function that goes through a page, such as a sitemap, and grabs a series of links to then save into a .json file, which is to be done with horseman.

The function works fine when I run it in Chrome console, I get the objects in the array. I just can't get that array to be written to the .json file by horseman.

Function looks like this:

    function findAllUrls(selector) {

    var urls = [];

    $(selector).each(function() {

    var url = {
      title: $(this).text(),
      url: $(this).attr("href")
    };

    url.push(urls);
     });

    console.log("Log all urls from findAllUrls", urls);
    return urls;
    };

And the horseman is like this:

    .open( <--URL for site here--> )
    .evaluate(findAllUrls, '.div a')
    .then(function(urls) {
      console.log(urls);
        fs.writeFile('urls.json', urls, function (err) {
        if (err) throw err;
      console.log('saved to urls.json');
    });
    })
    .close();

I get the feeling that phantomJS is not allowing the array to be saved and then written too the .json.

**Comment by johntitus** [comment]
I suspect it's because `fs.writeFile` is async, so you probably need to wrap it in a Promise. Otherwise, `then` finishes immediately and `.close` is called, so your process exits before the file has been written.

```js
.open( <--URL for site here--> )
.evaluate(findAllUrls, '.div a')
.then(function(urls) {
    console.log(urls);
    return new Promise( function(resolve, reject){
      fs.writeFile('urls.json', urls, function (err) {
        if (err) reject(err);
        console.log('saved to urls.json');
        resolve();
      });
    });
})
.close();
```

**Comment by lockykeaney** [comment]
Will test that out now.

We found that it might be a problem with the test server we are hosting on. We tried it on a few other generic sites and got it working.

**Comment by awlayton** [comment]
This was a case of using Promises wrong. What @johntitus said is the correct way. The `.then` must return a Promise, or `.close` will be called immediately.
