### ISSUE TITLE
typo in Readme.md

### ISSUE THREAD

**Issue by bchr02** [johntitus/node-horseman#7]
>.waitForSelector(selector)
Wait until the element selector is present e.g. .wait('#pay-button')

In the above section located within the [waitForSelector section of Readme.md](https://github.com/johntitus/node-horseman#waitforselectorselector), you show an example that uses a different method then what is expected.

Is this a typo? Shouldn't it read:
>Wait until the element selector is present e.g. .waitForSelector('#pay-button')

While we're on the topic, what is the logic behind using different methods and not just using .wait and detecting for number or selector? Is it for speed?

**Comment by johntitus** [comment]
Thanks - I've updated the readme in 1.3.1 https://github.com/johntitus/node-horseman/commit/0b78721b17601ba257d5b81dd41570a9826c25c1

I went with a more verbose API because I find it easier to read.

**Comment by bchr02** [comment]
ok, thanks.
