### ISSUE TITLE
Upgrade to bluebird 3.0

### ISSUE THREAD

**Issue by awlayton** [johntitus/node-horseman#72]
The new version of bluebird has a few [breaking changes](http://bluebirdjs.com/docs/new-in-bluebird-3.html#summary-of-breaking-changes). They are pretty minor and this will probably amount to just updating package.json. However, this will sort of be a breaking change to the chaining API since you can use the bluebird methods in the chains, so we should probably wait and do this as a part of v3.0.

**Comment by johntitus** [comment]
Sounds good.

**Comment by awlayton** [comment]
Closed in 3.0
