### ISSUE TITLE
Create git tag for each release

### ISSUE THREAD

**Issue by ImBobby** [johntitus/node-horseman#78]
Hi,

First time I tried node-horseman I used v1.5.6. After a while, I noticed that node-horseman is now at v2.8.1 and it was difficult for me to find v1.5.6 documentation. I had to run through commit history to [find the documentation](https://github.com/johntitus/node-horseman/tree/d2e200902288a15916d664e13714f9fde59e09e3).

I think it is wise to create git tag for each release so that people that use older version can easily find the docs.

**Comment by awlayton** [comment]
You could have just looked in your node modules, the Readme was in there. We will consider this for future releases.

**Comment by ImBobby** [comment]
Thank you. :+1:
