### ISSUE TITLE
[question] waitForSelector: Reject on timeout?

### ISSUE THREAD

**Issue by pardo-bsso** [johntitus/node-horseman#79]
Hello all and thanks for this module.

This is related to #77 I guess.

Currently I'm using a combination of waitForSelector().exists() and handling there when element is not found. I expected it to reject instead of the current behaviour (that is, resolving even if the element does not exist).

I could use on('timeout', ...) and then unset horseman.page.onTimeout when I'm done but it's dirty.

What do you think?

**Comment by awlayton** [comment]
I would say this is a bug rather than part of changes planned for #77, or at least it is a separate issue. The call doesn't even return an error.

I suppose it's up to @johntitus whether to fix it now or wait for 3.0.

I cannot think of an elegant solution short of changing horseman code.

**Comment by pardo-bsso** [comment]
On 18 November 2015 at 13:22, Alex Layton <notifications@github.com> wrote:
>
> I would say this is a bug rather than part of changes planned for #77, or at least it is a separate issue. The call doesn't even return an error.
>
> I suppose it's up to @johntitus whether to fix it now or wait for 3.0.
>
> I cannot think of an elegant solution short of changing horseman code.

Alright , thanks for the insight.

**Comment by johntitus** [comment]
So if I understand the issue correctly, you currently have to do something like this:

```js
horseman
  .open('http://www.google.com')
  .waitForSelector('blah')
  .exists('blah')
  .then(function(doesExist){
    if (!doesExist){
      throw new Error('Item not found');
    }
  })
```

and you were expecting:

```js
horseman
  .open('http://www.google.com')
  .waitForSelector('blah')
  .catch(function(e){
     //deal with a timeout error
  })
```

**Comment by pardo-bsso** [comment]
On 18 November 2015 at 14:24, John Titus <notifications@github.com> wrote:
>
> So if I understand the issue correctly, you currently have to do something like this:

(snip)

Yes that's right, it took me by surprise that behaviour but I can live
with it if it's not worth changing.

**Comment by johntitus** [comment]
I think it probably makes sense, given the direction we're going to take for #77. Probably needs to be tagged 3.0 though.

**Comment by awlayton** [comment]
In v3, all the `.wait*` actions now reject when a timeout occurs.

**Comment by pardo-bsso** [comment]
On 25 February 2016 at 23:00, Alex Layton <notifications@github.com> wrote:
>
> In v3, all the .wait* actions now reject when a timeout occurs.



That's awesome, thanks!
