### ISSUE TITLE
persistent cookies

### ISSUE THREAD

**Issue by bchr02** [johntitus/node-horseman#8]
It doesn't appear like you have an option to save persistent cookies to a file. Does your api possibly persist them in memory though for each unique object? 

For example, if I login to a website and don't log out, can a subsequent connection that uses the same object use the same website session (stored in a cookie) even after ````horseman.close();```` has been called? Or is this a limitation with the current api?

**Comment by johntitus** [comment]
Just added a `cookiesFile` option. Use it when you login, and on subsequent runs, and it should keep the cookie around. Note that session cookies may expire relatively quickly.

**Comment by bchr02** [comment]
I meant persistent cookie not session cookie. :smile: 

Thank you very much for adding this.
