### ISSUE TITLE
.url() no longer returning value

### ISSUE THREAD

**Issue by Osmosis311** [johntitus/node-horseman#81]
When I do horseman.url() it returns some kind of object instead of the actual URL.

**Comment by johntitus** [comment]
This seems to work ok for me. Can you give an example that doesn't?

```js
var Horseman = require('node-horseman');

var horseman = new Horseman();

horseman
	.open('http://www.google.com')
	.url()
	.log()
	.close();
```

**Comment by awlayton** [comment]
Are you looking at the synchronous return value? Because that is a Promise, which is an object.

**Comment by awlayton** [comment]
Closing, seems like this was a misunderstanding of the API.
