### ISSUE TITLE
Synchronous behavior change

### ISSUE THREAD

**Issue by Osmosis311** [johntitus/node-horseman#82]
It used to be that if I did this:

horseman.pdf('test.pdf').close();
console.log('finished!');

...I wouldn't see the log message until the PDF generation had completed.  Now, the log message is showing before the PDF is completed and my program is shutting down before it has a chance to complete.  I even tried doing horseman.pdf('test1.pdf').then(function() { console.log('test') }); with the same result.

What am I doing wrong?

**Comment by johntitus** [comment]
The first one won't work because the API is now promised based.

Can you give a working/broken example for the second one?

**Comment by Osmosis311** [comment]
Thanks for getting back to me so quickly!

This isn't working for me; cb() is a callback from an enclosed async.waterfall series

horseman.open(itm.url)
		.waitForNextPage()
		.click(blacklistTab)
		.url().then(function(url) {
			console.log('OK Heres the URL: ' + url);
		})
		.pdf('test11.pdf')
                .then(function() { cb() });		

cb() is getting called before the PDF gets generated, and the console log with the URL never appears either.  I'm running Node 5.1.0 and the latest horseman.

**Comment by johntitus** [comment]
I suspect you need to wrap the callback in a Promise (and maybe the log too).

**Comment by Osmosis311** [comment]
Isn't that what I'm doing with the "then"? How do I wrap the PDF command in a promise?

**Comment by Osmosis311** [comment]
Never mind, the .then() worked, I had something else after it, sorry about that!  Thanks for the help!
