### ISSUE TITLE
doesn't work on mac el capitan

### ISSUE THREAD

**Issue by chovy** [johntitus/node-horseman#83]
I did the example and it doesn't log anything. No errors.

```
var Horseman = require('node-horseman');
var horseman = new Horseman();

horseman
  .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
  .open('http://www.google.com')
  .type('input[name="q"]', 'github')
  .click("button:contains('Google Search')")
  .keyboardEvent("keypress",16777221)
  .waitForSelector("div.g")
  .count("div.g")
  .log() // prints out the number of results
  .close();
```

I tried installing phantomjs from brew but that is not compatible with El Capitan.
So I downloaded the 2.x mac binary and moved it to my `~/bin` and added to `$PATH`.

Still nothing.

I tried both node v0.10.40 and node v5.0

**Comment by awlayton** [comment]
Could you run it again with environment variables `DEBUG=horseman` and `BLUEBIRD_DEBUG=1` and post any output @chovy?

**Comment by chovy** [comment]
I got nothin'

`$ DEBUG=horseman; BLUEBIRD_DEBUG=1 node app.js`

I just get the prompt.

**Comment by awlayton** [comment]
I think that command has a mistake. I think you want this.
`$ DEBUG=horseman BLUEBIRD_DEBUG=1 node app.js`

**Comment by chovy** [comment]
This works now....I think at the time phantomjs wasn't available for El Capitan via brew. I just tried again and works...also you were right, the `;` was clobbering my DEBUG env variable. Thanks for pointing tha tout.
