### ISSUE TITLE
Stop chain if condition not met

### ISSUE THREAD

**Issue by nicekiwi** [johntitus/node-horseman#84]
.evaluate(function() {
      if($('#element')) return false;
    })
    .then(function(result) {
      if(result) {
        console.log( 'True.');
      } else {
        return horseman.close();
      }
    }).then... 

If the result form the evaluation is false I want to stop the chain completely, but running horseman.close() where it is, just seems to kill phantom, it doesn't  stop the chain that goes on after that "then" function and throws an error.

**Comment by awlayton** [comment]
You would have to have a chain within the chain.

```javascript
.evaluate(function() {
  if($('#element')) return false;
})
.then(function(result) {
  if(result) {
    return horseman.then...
  } else {
    return horseman.close();
  }
});
```

**Comment by awlayton** [comment]
Actually, what you should probably do is reject the Promise when the condition fails.

```javascript
.evaluate(function() {
  if($('#element')) return false;
})
.then(function(result) {
  if(!result) {
    return Promise.reject();
  }
}).then... 
```
