### ISSUE TITLE
Click each element then scrape

### ISSUE THREAD

**Issue by Majed93** [johntitus/node-horseman#85]
Is there a way I could loop through each element, say each h2 element, click it then scrape? This would be because the h2 elements are closed and it would be good to expand them to see the data and then extract the data.

**Comment by awlayton** [comment]
I cannot think of a good way to do this sort of thing. Below is the first way of achieving it I thought of, but it is rather gross.

```javascript
var SELECTOR = 'h2'; // Thing to click each of
var ATTR = 'foo'; // Dummy attribute

horseman.open(url)
    // Add blank dummy attribute to each
    .evalutate(function(selector, attr) {
        var els = document.querySelectorAll(selector);
        for(var i = 0; i < els.length; i++) {
           els[i].setAttribute(attr, '');
        }
        return els.length;
    }, SELECTOR, ATTR)
    .then(function(nels) {
        var blankSel = SELECTOR + '[' + ATTR + '=""]';
         var chain = horseman;
         for(var i = 0; i < nels; i++) {
             chain = chain
                  // Click first one with blank dummy attribute
                  .click(sel)
                  // Make dummy attribute of clicked one not blank
                  .evaluate(function(selector, attr) {
                      document.querySelector(selector).setAttribute(attr, true);
                  }, blankSel, ATTR);
         }
         return chain;
    })
    // Do whatever
    .then(...
```

Do we want to think about making a better way to operate on sets of elements @johntitus?

**Comment by johntitus** [comment]
Maybe I misread. Can't we just have jQuery click everything so they expand, then afterwards scrape each?? 

```js
horseman
  .open(url)
  .evaluate(function(selector){
     $(selector).click();
  }, selector)
  // Do whatever
  .then(
```

**Comment by awlayton** [comment]
It was maybe understanding that only some DOM elements have a `.click` (e.g., button), and that h2 was not one of them. Perhaps I am wrong, or JQuery adds a click to them?

**Comment by johntitus** [comment]
It will fire a click event on all matching selectors I believe - but that doesn't mean the item will respond in any way.

**Comment by awlayton** [comment]
Yeah, do his one then.

**Comment by Majed93** [comment]
I assume i would just put 'h2' in place of selector? Because it does not seem to be working. I inspect the body after scrape and the h2 elements haven't expand to show the other data.

**Comment by johntitus** [comment]
If the expansion is animated, you may want to put in a delay.

**Comment by Majed93** [comment]
Can't seem to get it working still.

<addr>
.open(url)
.evaluate(function (selector) {
            $(selector).click();
            wait(1000);
        }, selector)
 .wait(10000)
.then(scrape)
.finally(//prints to page here)
My code
</addr>

**Comment by Majed93** [comment]
So during evaluate it will wait, then finally before scraping it will wait again. I inspected the body after scrape and it still seems to be the same.

**Comment by Majed93** [comment]
Trying something else now..
```
.evaluate(clickItems())
```

This will call the following function which to my thinking should work(clicking a span element now)?

```

function clickItems() {
    return horseman
        .evaluate(function () {
        $('span.title').each(function (index, item) {
            return horseman.
                click('span.title');
        });
    })
}

```

**Comment by awlayton** [comment]
The function given to `.evaluate` runs inside the browser, so it can access things in node (like `horseman`).

What exactly didn't work about what @johntitus suggested?

**Comment by Majed93** [comment]
What do you mean?

It didn't seem to click anything..
I used his exact code and made a variable called selector, assigning it the value i need of "h2" and then later "span.title". I inspected the body and nothing seemed to change.

**Comment by awlayton** [comment]
The code you posted was different from what he posted. Can you post the exact code (or as close as possible) that you are running?

**Comment by Majed93** [comment]
``` 
var selector = 'span.accordion__title';
    
        .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
        .open(testurl)
        .evaluate(function (selector) {
            $(selector).click();
        }, selector)
.then(scrape)
.finally(//other stuff here)

```

**Comment by awlayton** [comment]
Maybe try it without using `$`? I found a page once that have a `$` variable that didn't seem to be JQuery, perhaps that is happening...

```javascript
var selector = 'span.title';

horseman
        .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
        .open(testurl)
        .evaluate(function (selector) {
            Array.prototype.forEach.call(document.querySelectorAll(selector), function(el) {
                el.click();
            });
        }, selector)
.then(scrape)
.then(/*other stuff here*/);
```

Both versions seem to work for me when I try them.

**Comment by Majed93** [comment]
What's the Array.prototype line?

**Comment by awlayton** [comment]
The thing return by `document.querySelectorAll` is "array-like", but not an actual `Array`, so it has no `.forEach`. That is just me stealing it off the `Array` `prototype`.

**Comment by Majed93** [comment]
Same result as last time..doesn't seem to click it..

**Comment by awlayton** [comment]
Can you give a url for which this happens?

**Comment by Majed93** [comment]
Unfortunately i can't give you the exact url, so i'll find something which can replicate the behaviour.

**Comment by awlayton** [comment]
It would seem that while the elements do have a `.click`, in this case it does not reveal them.

However, dispatching click events (what `horseman.click` does, and therefor the code in my original post) does revel them.

A much less gross way of doing so is below:
```javascript
var Horseman = require('node-horseman');

var SELECTOR = 'h2';
var URL = /* The URL */;

var horseman = new Horseman();

horseman.open(URL)
    .evaluate(function(selector){
        var els = $(selector);
        $.each(els, function(i, el) {
            var event = document.createEvent('MouseEvent');
            event.initEvent('click', true, true);
            el.dispatchEvent(event);
        });
    }, SELECTOR)
    .then(/* other stuff */)
```

Please confirm if this works for you as well, @Majed93.

**Comment by Majed93** [comment]
Slightly works..I can them expanding now but some are still loading..which i assume i can just put a delay in, after evaluate, waitForSelector('h2')? or wait(1000) or any number of seconds.

I tried changing the selector to 'h2:has(table)' to check if the element has a table then click on it..but this didn't seem to work?

**Comment by awlayton** [comment]
To wait after the evaluate you want
```javascript
    .evaluate(/* stuff from above*/)
    .delay(/* time in ms */)
    .then(/* other stuff */)
```

`.waitFor('h2')` waits for an `h2` to exist, which is already true so it won't actually wait.

As for the `'h2:has(table)'`, I don't use a lot of JQuery so I probably won't be much help figuring that out.

**Comment by Majed93** [comment]
Ah ok thanks for your help. As for the ```h2:has(table)``` i meant if the element does NOT contain a table element within it then click it..

**Comment by Majed93** [comment]
Got it, h2:not(:has(table)). Thanks for all your help.
