### ISSUE TITLE
Different CSS Selector implementation?

### ISSUE THREAD

**Issue by mlengse** [johntitus/node-horseman#86]
Hi,
I'm sorry for asking here. Is there any different CSS selector implementation between *.waitForSelector(selector)* and *.click(selector)*?

For example:
I can use
```
   horseman.click('td.MenuItem:contains("some text")');
```
but I can not use
```
    horseman.waitForSelector('td.MenuItem:contains("some text")');
```
instead I must use
```
    horseman.waitForSelector('div.MenuBar td.MenuItem:nth-child(2)');
```

**Comment by awlayton** [comment]
Yes, they are slightly different. The implementation called by `.waitForSelector` does not use JQuery, even if it's available. See [this line](https://github.com/johntitus/node-horseman/blob/bc1ac24b0c7796653b2ff2963ff68dc4fef16cd1/lib/actions.js#L1053).

**Comment by johntitus** [comment]
Good catch. It's a hold over from nightmare. Need to fix it.

**Comment by mlengse** [comment]
Can we borrow some code from [this](https://gist.github.com/buu700/4200601) jQuery `.waitUntilExists()` plugin's?
I'm trying to use it, but I can't [debug](https://github.com/johntitus/node-horseman/blob/f2c374a9284b5a171aef084176b64fce00778d93/lib/actions.js#L684) `.evaluate()`

**Comment by awlayton** [comment]
You can debug the function given to `.evaluate` with `console.log` etc., but you have to be sure to respond to the `'consoleMessage'` events in node.

For example, the following with log "foo" to the node console.
```javascript
// Receive things sent to Phantom's console
horseman.on('consoleMessage', function(msg, lineNum, sourceId) {
    // Log something to the node console
    console.log(msg);
})

horseman.open(/* Some URL */)
    .evaluate(function() {
        // Log lo Phantom's console
        console.log('foo');
    })
```

**Comment by awlayton** [comment]
Closed in v3
