### ISSUE TITLE
default for ignoreSSLErrors should be false (IMHO)

### ISSUE THREAD

**Issue by alxlo** [johntitus/node-horseman#91]
I know it's inconvenient for getting started, but on the other hand, users will be passing sensitive information like passwords to web pages. And they will have running scripts for maybe months unsupervised. Therefore this is a considerable attack vector. So for the sake of security, this little inconvenience is better than  getting credentials stolen by an easy to set up MITM (think ARP spoofing).

**Comment by awlayton** [comment]
I agree. Do you want to change this for 3.0 @johntitus?

**Comment by johntitus** [comment]
Yeah I think that makes sense.

**Comment by awlayton** [comment]
Fixed in 3.0
