### ISSUE TITLE
Add support for .includeJs?

### ISSUE THREAD

**Issue by awlayton** [johntitus/node-horseman#93]
Is there a particular reason why horseman has no action for Phantom's [`.includeJs`](http://phantomjs.org/api/webpage/method/include-js.html)?

**Comment by johntitus** [comment]
I think the `clientScripts` option is supposed to do this, but I'm not sure it works in the 2.x line.

**Comment by awlayton** [comment]
But those are local files, and `.includeJs` works with URLs.

**Comment by johntitus** [comment]
I guess I just missed it then.

**Comment by awlayton** [comment]
Closed in v3 by #114
