### ISSUE TITLE
Click doesnt work

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#94]
var Horseman = require('node-horseman');
      var horseman = new Horseman();

      horseman
       .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
       .open('http://www.google.com')
       .type('input[name="q"]', 'github')
       .click("button:contains('Google Search')")
       .keyboardEvent("keypress",16777221)
       .waitForSelector("div.g")
       .count("div.g")
       .log() // prints out the number of results
       .close();
   
This is not called in click function: 
    
    self.page.evaluate(function(selector) {
                console.log('log selector', selector);
    },....

**Comment by awlayton** [comment]
I do not understand what that second block of code is. Could you try to state how `.click` does not work more clearly?

**Comment by mato75** [comment]
Sorry, not an issue.
