### ISSUE TITLE
on('loadFinished', function () { console.log('Status'); }) callback is not called

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#95]
Question:  
Do we first open a url and then listen for events or the other way around?

In both cases the code gets to here:

       debug('jQuery not injected - already exists on page');
       if (that.page.onLoadFinished2) {
            // we get here 
            that.page.onLoadFinished2();
       }

I have a log inside the callback, but I never see that log, so I presume that the callback is never called. Any suggestions?

**Comment by mato75** [comment]
Got it to work, but please add arguments when calling onLoadFinished2

      that.page.onLoadFinished2(status || arguments);

**Comment by awlayton** [comment]
I think you are using horseman wrong. If `that` is a Horseman instance, you shouldn't be messing with `that.page`.
