### ISSUE TITLE
waitForResource

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#96]
How would someone use waitFor to create a function that will wait for a resource?

**Comment by mato75** [comment]
this is what I currently have, but it doesn't work correctly. 

        waitForResource: function (test) {
        debug('.waitForResource()');
        var that = this;
        var start;
        return this.ready.then(function() {
            return new GuardianPromise(function(resolve, reject) {
                    start = Date.now();
                    var checkInterval = setInterval(function() {
                        var diff = Date.now() - start;
                        if (diff > that.options.timeout) {
                            clearInterval(checkInterval);
                            reject('Timeout occurred before url changed.')
                        } else { 
                            var res = that.resourceExists(test);
                            console.log(res);
                            if (res === true) {
                                debug('.waitFor() completed successfully');
                                clearInterval(checkInterval);
                                resolve();
                            }
                        }
                    }, that.options.interval)
                })
                .catch(function(err) {
                    if (err === 'Timeout occurred before url changed.') {
                        debug('Timeout during waitFor()');
                        if (typeof that.page.onTimeout === 'function') {
                            that.page.onTimeout();
                        }
                    }
                });
        });
    },

**Comment by mato75** [comment]
Why in waitFor function, when using evaluate, resolve() that is called is not the correct one, because when using it with waitForSelector and adding in resolve some response:   

        resolve('Got Something');

.then doesnt return Got Something. Why is promise resolved before it should actually be?

**Comment by awlayton** [comment]
I'm sorry, but I can never follow your questions. I need more complete example code.

**Comment by mato75** [comment]
Would you maybe know, why current function is not ok?

Now, when using evaluate in the function, sure we are checking the for responses and getting true/false if response is in or not. But the issue is, that resolve is to fast,

      waitForResource: function (test) {
        debug('.waitForResource()');
        var that = this;
        var start;
        return this.ready.then(function() {
            return new GuardianPromise(function(resolve, reject) {
                    start = Date.now();
                    var checkInterval = setInterval(function() {
                        var diff = Date.now() - start;
                        if (diff > that.options.timeout) {
                            clearInterval(checkInterval);
                            reject('Timeout occurred before url changed.')
                        } else { 
                              that
                                .evaluate(function () {}, '')
                                .then(function() {
                                    var res = that.resourceExists(test);
                                    console.log(res);
                                    if (res === true) {
                                        debug('.waitFor() completed successfully');
                                        clearInterval(checkInterval);
                                        resolve("we-got-the-response');
                                    }
                                })
                        }
                    }, that.options.interval)
                })
                .catch(function(err) {
                    if (err === 'Timeout occurred before url changed.') {
                        debug('Timeout during waitFor()');
                        if (typeof that.page.onTimeout === 'function') {
                            that.page.onTimeout();
                        }
                    }
                });
        });

So now when I call 

              horseman.waitForResource(/test.js/i)
                              .then(function (res) { 
                                       res is undefined, but it should be "we-got-the-response'. I believe that the reason for this issue is, that resolve is called by someone else. Now the question is by who?
                               }

**Comment by awlayton** [comment]
Perhaps the `.waitForResource` is timing out, then `res` would be undefined.

Promises don't "resolve too fast" unless bluebird (the Promise library horseman uses) is seriously broken, which I doubt.

**Comment by mato75** [comment]
No, added logs to the timeouts, and it is not. I do not think Promise lib is broken, but something is strange. Have you gave any though on implementing this kind of function to the library?

**Comment by awlayton** [comment]
Yes, this is *very* similar to [`.waitFor`](https://github.com/johntitus/node-horseman/blob/e419fd56e7774577bdb9cfb7a8c6a3fcb57fcf98/lib/actions.js#L1061). In fact, you **should** implement this *using* `.waitFor`.

**Comment by mato75** [comment]
I tried, but I cannot get it to work. .then gets called to fast and res in waitFor .then is null all the time.


    waitForResource2: function (test) {
        var that = this;
        return this.waitFor(function () {
                return that.resourceExists(test);
            }, true).then(function() {
            debug('.waitForSelector() complete');
        });
    },
    resourceExists: function (test) {
        var that = this;
        var testFn;
        
        if (util.isRegExp(test)) {
            testFn = function _testResourceExists_Regexp(res) {
                return test.test(res) && that.responses[res] !== 404;
            };
        } else if (util.isString(test)) {
            testFn = function _testResourceExists_String(res) {
                return res.indexOf(test) !== -1 && that.responses[res] !== 404;
            };
        } else {
            throw Error ('Wrong type');
        }        
        
        return Object.keys(that.responses).some(testFn);
    },

**Comment by awlayton** [comment]
I see, your test needs to run in NodeJS, not in PhantomJS (which is where `.waitFor` runs its function). So nevermind, you cannot implement this with `.waitFor`.

I would double check that your logs are working. The *only* way `res` is `undefined` is if that `GuardianPromise` you made is rejecting for some reason.

It looks like your catch only logs when it was a timeout error, but perhaps something else made the Promise reject. Try running your code with the environment variable `BLUEBIRD_DEBUG=1` and see what prints.

**Comment by mato75** [comment]
No you are right, it was a reject('Timeout occurred before url changed.'), what do you recommend on how to fix this?

**Comment by awlayton** [comment]
Are you saying it *was* a timeout error?

**Comment by mato75** [comment]
Yes.

**Comment by awlayton** [comment]
Then you just need to increase your timeout. Also, you should make that `.catch` *only* catch timeout errors.

**Comment by mato75** [comment]
Timeout errors?

**Comment by mato75** [comment]
Thx man. That was the key.

**Comment by awlayton** [comment]
If the Promise reject for something besides a timeout, your `.catch will make it resolve to undefined. You need to put a filter on your catch.

```javascript
.catch(
    function filter(err) {
        return err === 'Timeout occurred before url changed.'
    }, function handler(err) {
        debug('Timeout during waitFor()');
        if (typeof that.page.onTimeout === 'function') {
            that.page.onTimeout();
        }
    }
);
```
