### ISSUE TITLE
waitForSelector promise is resolved too fast

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#97]
Why in waitFor function, when using evaluate, resolve() that is called is not the correct one, because when using it with waitForSelector and adding in resolve some response:

    resolve('Got Something');
.then(res), res = undefined (why?). Promise is resolved by something else and I cannot find what.

**Comment by awlayton** [comment]
Is this the same thing you are talking about is #96?

**Comment by mato75** [comment]
yes it is connected, I found the issue when I was trying to implement waitForResource.

**Comment by mato75** [comment]
It is connected to timeout, increase timeout and issue will not be present.
