### ISSUE TITLE
Options prevent use with SlimerJS

### ISSUE THREAD

**Issue by w33ble** [johntitus/node-horseman#99]
There are 2 options being [passed to the binary](https://github.com/johntitus/node-horseman/blob/master/lib%2Findex.js#L53-L58) that stop it from working, `ignore-ssl-errors` and `web-security`. If you remove those options, slimer works as a drop-in replacement when you use it via the `phantomPath` option (at least in my use case it does). 

As a possible solution, it seems reasonable to put both of those flags behind a user-passed option, as horseman already does with a number of other options. That way, both flags (and potentially others) won't be used by default, but can be set by the user. 

This is probably a breaking change though, and if you're following semver, would call for a major version change. But, it's a simple and it would allow the use of slimer with a very small amount of work on your part.

BTW, If you're curious what options are supported, you can find the list [right here](https://docs.slimerjs.org/current/configuration.html#command-line-options). I don't know if you intended to support [slimer](https://slimerjs.org/), but `node-phantom-simple` does, so it's not out of the realm of reason. Of course, if you don't care about support slimer, that up to you, and you can close this issue if that's the case...

**Comment by johntitus** [comment]
Thanks! I've been meaning to see how much trouble Slimer would be. As we already have some issues queued up for version 3.0, I think this would fit in nicely.

**Comment by awlayton** [comment]
Why can't you pass those options to slimer? They are listed in its [documentation](http://docs.slimerjs.org/current/configuration.html#command-line-options)

**Comment by w33ble** [comment]
That list is a collection of Phantom options, the middle column is the support in Slimer. Note that both `–ignore-ssl-errors` and `–web-security` are both not listed in the middle column.

If you run horseman with Slimer, passing it in as the `phantomPath`, you will get an error message that says (paraphrasing, but very close to the output) `–ignore-ssl-errors is not implemented yet`, likewise with `–web-security is not implemented yet`.

**Comment by awlayton** [comment]
When I run it with `--ignore-ssl-errors` I get a "not supported *yet*" message, but it still runs just fine.

**Comment by w33ble** [comment]
Yeah, that's the message. For me, the promise chain fails with the error message *Unexpected output from PhantomJS: --ignore-ssl-errors not supported yet*.

slimerjs@0.9.6
node-horsemane@2.8.2
node-phantom-simple@2.2.2

**Comment by awlayton** [comment]
I see. Unfortunate.

**Comment by w33ble** [comment]
Yeah... it's an upstream problem. There's currently no way to NOT pass those options with node-horseman though, so it also seems like an issue here. 

#102 at least allows you to use Slimer if you want to.

**Comment by awlayton** [comment]
Fixed in 3.0
